### ISSUE TITLE
Timestamps can't be formated properly  

### ISSUE THREAD

**Issue by DaveTaboola** [doitintl/bigquery-grafana#10]
## Expected Behavior
Timestamps fields won't translate to readable value (even after playing around with the Column styles

## Actual Behavior 
When the column type is date, the result will be Invalid date
When the column type is number it will show a number (1.54224E9)
When the column type is string it will show a number (1.54224E9)

## Steps to Reproduce the Problem

  1. Create bigquery data source
  2. Create new table visualisation
  3.  Create a query of SELECT * FROM <table which consist with nested fields> (no time series) 

## Specifications

  - Version: 1.0 
  - Platform: container over k8s
  - Grafana Version: 5.4.2

**Comment by avivl** [comment]
@DaveTaboola can you send me the schema and a few records so I can test?

**Comment by DaveTaboola** [comment]
you can download a sample from here: https://ufile.io/put0f

**Comment by DaveTaboola** [comment]
@avivl if its ok lets sync, as the issue still persist so maybe i'm doing something wrong on the grafana side and we need to enrich the documentation?

**Comment by avivl** [comment]
@DaveTaboola did you `git pull` the plugin repo?

**Comment by DaveTaboola** [comment]
yap, as i'm using the plugin over a kube cluster I've just restarted the container and it cloned the repo when the pod was restarted

**Comment by avivl** [comment]
cat you share the outpust of `git log` and the table schema?

**Comment by DaveTaboola** [comment]
I've verified that the new code exist in the container itself by just running grep against several lines in the pull request that was merged (as its a container i have limited options of what i can do, git is not installed and i can't login as root) 

i've uploaded images to represent the issue 
https://ibb.co/SJ5CyfB - Shows the BQ schema 
https://ibb.co/J7C16G3 - Shows a sample of the data (same data i've sent here before) 
https://ibb.co/JCJ1bd7 - Shows the query in grafana (and the value as a STRING) 
https://ibb.co/N115Wx5 - Shows the column configuration as TIME
https://ibb.co/wwN12kj - Shows the column configuration as NUMBER with data configuration

**Comment by avivl** [comment]
@DaveTaboola thanks! I'll reopen the issue and will work on it later today

**Comment by DaveTaboola** [comment]
If you need help I'm here to assist the best that I can

**Comment by avivl** [comment]
@DaveTaboola this should be fixed now. Can you check?
