### ISSUE TITLE
Set minimum interval

### ISSUE THREAD

**Issue by JorritSalverda** [doitintl/bigquery-grafana#105]
## Feature Request

**Is your feature request related to a problem? Please describe.**

To be able to see a wide selection of time ranges, from 1 hour to 1 year I use the following grouping in my queries:

```
$__timeGroupAlias(measured_at,$__interval)
```

I like to prevent `$__interval` to go below a certain configurable threshold. It would be nice to have a text box just like _max data points_, _relative time_ and _time shift_ that accepts values like `15min`, `1d` or `7d` which ensures that `$__interval` never goes below that value.

**Describe the solution you'd like**

The `_getInterval` function would check if there's a `minInterval` configured and if so turns that into seconds as well and takes the larger of the 2.

**Describe alternatives you've considered**

An alternative would be a _resolution_ select field like the _Prometheus_ data source uses, however that always reduces the resolution, regardless of the time range. Also very useful for another reason of course.

**Comment by avivl** [comment]
@JorritSalverda I'm not sure I understand why do you need this. The minInterval is per graph so why not just set the correct $__intervalvalue?

**Comment by JorritSalverda** [comment]
@avivl what I'm trying to achieve is to have a minimum time interval for when I select 1 day, but to automatically have a larger interval when I look at 5 years for the same graph. If that's the current behaviour of for example `$__timeGroupAlias(measured_at,1h)` then we're already good, but I guess it keeps grouping in 1 hour intervals even if you look at a time range of 5 years.

Using `$__timeGroupAlias(measured_at,$__interval)` on the other hand solves the 5 year range issue, but runs the risk of going below 1 hour if a short range is selected. Hope this make sense.

**Comment by avivl** [comment]
![image](https://user-images.githubusercontent.com/3265061/60433589-deeb9600-9c0d-11e9-9d41-bab4cba501e7.png)
