### ISSUE TITLE
Executor Not Found for Annotation Query

### ISSUE THREAD

**Issue by kylie-a** [doitintl/bigquery-grafana#106]
## Bug Report

After installing the plugin and configuring it to be able to use the Big Query API I set up an annotation query and got an error. I can successfully query Big Query in a panel, only the annotation query fails (same query). From the logs:

```
t=2019-06-27T18:28:33+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="Could not find executor for data source type: doitintl-bigquery-datasource"
t=2019-06-27T18:28:33+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/tsdb/query status=500 remote_addr=172.17.0.1 time_ms=14 size=34 referer="http://localhost:3000/d/c4QzQT4Zz/new-dashboard-copy?orgId=1"
```

## Expected Behavior

The annotations should appear on the graphs.

## Actual Behavior

Received the above error.

## Steps to Reproduce the Problem

  1. Install plugin according to documentation
  1. Add random walk Grafana graph 
  1. Add annotation query using Big Query as the datasource:

```
#standardSQL
SELECT
 TIMESTAMP_SECONDS(header.timestamp) AS time,
 pd_incident_id as text
FROM `my_project.my_dataset.my_table`
where
 pd_event_type="EVENT_TYPE_TRIGGER"
```

## Specifications

  - Version: 1.0.0
  - Platform: Docker/Ubuntu
  - Grafana Version: Docker image grafana/grafana:6.2.5

**Comment by avivl** [comment]
@kylie-a I'm not sure I understand. Random walk if for the grafana demo data source. How do you add an annotation from the BQ data source?

**Comment by kylie-a** [comment]
@avivl I meant add graph panel, set the data source to `--grafana--` and use the default graph it provides. Sorry for being unclear

**Comment by avivl** [comment]
@kylie-a 
How can you have an annotation from BQ where the data source of grafana?
Can you share a screen recording so I understand better?

Thanks
Aviv

**Comment by kylie-a** [comment]
If I'm not mistaken the data source for the graph panel and the data source for the annotations doesn't need to be the same. Most of the dashboards on our Grafana instance use Prometheus as a datasource for metrics and Elastic Search as a datasource for annotations. I used the Grafana datasource for a graph on a test dashboard so the annotations would be visible.

**Comment by avivl** [comment]
Can you share a screen recording so I understand better?

**Comment by kylie-a** [comment]
https://www.youtube.com/watch?v=aCpy1uM7O8g
