### ISSUE TITLE
Infer project implicitly for dashboard export definition

### ISSUE THREAD

**Issue by 3dprintscanner** [doitintl/bigquery-grafana#110]
## Feature Request

**Is your feature request related to a problem? Please describe.**

We want to use the grafana export dashboard functionality so we can use the same dashboard across multiple environments. As such, the exported dashboard JSON definition should abstract all environment specific variables.

We have multiple environments with the same table names, defined as different GCP projects. The projectid is persisted when the dashboard is exported in the publicly shareable format.

Our goal is to use non fully qualified queries and let the project id be implicitly picked up from the service account.

eg. 

Instead of 
```select * from `proj.dataset.table` ``` 

We would like

```select * from `dataset.table` ``` 

Here is a snippet of part of the exported panel, you can get this by clicking on the panel   `header > more > panel json`

```"targets": [
   
     "dataset": "monitoring",
     "format": "time_series",
     "group": [
       
         "params": [
           "1d",
           "none"
         ],
         "type": "time"
       
     ],
     "metricColumn": "Topic",
     "partitioned": false,
     "partitionedField": "",
     "project": "gcp-project-id",
     "rawQuery": false,
     "rawSql": "#standardSQL\nSELECT\n $__timeGroupAlias(__Metadata.IngestedTimestamp,1d),\n  Topic AS metric,\n  count(*) AS count\nFROM `monitoring.justsayingpoisonmessages`\nWHERE\n  $__timeFilter(__Metadata.IngestedTimestamp)\nGROUP BY 1,2\nORDER BY 1,2",
     "refId": "A",
     "select": [
       
         
           "params": [
             "*"
           ],
           "type": "column"
         },
         {
```

The target object has a `project` property. If we try to import this panel into another grafana instance which references another big query project, it will complain about the project being wrong, even if our new query references the correct new project in the raw SQL.

**Describe the solution you’d like**
- For the exported panel JSON to not have an explicit project.

- The project to query on should first look if the query is fully qualified and use that. If the query doesn’t have a project id then it could pick up the project from the service account.

- It may be possible for a service account to have access permissions to multiple projects. In that case a variable should be hoisted out and placed into the __inputs section of the template defintion

**Describe alternatives you’ve considered**

The alternative is we do additional templating on our side but ideally we could avoid this

**Comment by avivl** [comment]
@3dprintscanner we are not going to do it. As you mention you can always do additional templating in order to solve this
