### ISSUE TITLE
Save & Test fails with 3 requests to a job called no-such-jobs

### ISSUE THREAD

**Issue by jakobholmelund** [doitintl/bigquery-grafana#112]
When i press save & test in add datasource it just times out. When i check the console i get the following

`
GET http://localhost:3000/api/datasources/proxy/1/bigquery/v2/projects/example-245520/jobs/no-such-jobs 404 (Not Found)
GET http://localhost:3000/api/datasources/proxy/1/bigquery/v2/projects/example-245520/jobs/no-such-jobs 404 (Not Found)
GET http://localhost:3000/api/datasources/proxy/1/bigquery/v2/projects/example-245520/jobs/no-such-jobs 404 (Not Found)
`
and inspecting the 404 i get

`
{
  "error": {
    "code": 404,
    "message": "Not found: Job example-245520:no-such-jobs",
    "errors": [
      {
        "message": "Not found: Job example-245520:no-such-jobs",
        "domain": "global",
        "reason": "notFound"
      }
    ],
    "status": "NOT_FOUND"
  }
}
`

**Comment by kpeters-cbsi** [comment]
What did you do to solve this problem? I'm experiencing a similar issue.

**Comment by kpeters-cbsi** [comment]
To answer my own question, in case someone else comes on this like I did: the key I had didn't have the correct permissions for use with Grafana. I ended up having to create a key on the app engine default service account for Grafana to work.
