### ISSUE TITLE
invalidQuery: Unrecognized name: service.id; Did you mean service? at [4:3]

### ISSUE THREAD

**Issue by marcuspink** [doitintl/bigquery-grafana#116]
## Bug Report
After Upgrading the Plugin from Version 0.6.0 to 1.0.0 my previously working queries don't work anymore.

## Expected Behavior
Return data for the following query:
`#standardSQL
SELECT
 $__timeGroupAlias(usage_start_time,1d),
  `service.id` AS metric,
  sum(`cost`) AS cost
FROM `gcp-project.gcp_billing.gcp_billing_export_v1_...`
WHERE
  $__timeFilter(usage_start_time) AND _PARTITIONTIME >= '2019-07-01 00:00:00' AND _PARTITIONTIME < '2019-07-19 17:10:41'
GROUP BY 1,2
ORDER BY 1,2`

## Actual Behavior
`invalidQuery: Unrecognized name: service.id; Did you mean service? at [4:3]`
This error message also appears for other metric names like: project.id, sku.id etc.

## Steps to Reproduce the Problem
  1. Query a GCP Billing export with plugin version 1.0.0.

## attempted solutions
1. reinstalled Plugin
2. reinstalled grafana and plugin
3. sucessfully tested query in gcp bigquery 
## Specifications

  - Version: 1.0.0
  - Platform: Linux
  - Grafana Version: 6.2.5

**Comment by avivl** [comment]
@marcuspink please add quotes to the fields that include dots `service.id`

**Comment by marcuspink** [comment]
@avivl there are quotes, but they were removed by my bad markdown skills
```SELECT
 $__timeGroupAlias(usage_start_time,1d),
  `service.id` AS metric,
  sum(`cost`) AS cost
FROM `gcp-project.gcp_billing.gcp_billing_export_v1_...`
WHERE
  $__timeFilter(usage_start_time) AND _PARTITIONTIME >= '2019-07-01 00:00:00' AND _PARTITIONTIME < '2019-07-19 17:10:41'
GROUP BY 1,2
ORDER BY 1,2

**Comment by avivl** [comment]
@marcuspink can you open the developer console and copy the generated query ?

**Comment by marcuspink** [comment]
@avivl
```{
  "xhrStatus": "complete",
  "request": {
    "method": "POST",
    "data": {
      "query": "#standardSQL\nSELECT\n TIMESTAMP_SECONDS(DIV(UNIX_SECONDS(`usage_end_time`), 86400) * 86400),\n  `service.id` AS metric,\n  sum(`cost`) AS cost\nFROM `gcp-project.gcp_billing.gcp_billing_export_v1_...`\nWHERE\n  `usage_end_time` BETWEEN TIMESTAMP_MILLIS (1561932000000) AND TIMESTAMP_MILLIS (1563783731937) AND _PARTITIONTIME >= '2019-07-01 00:00:00' AND _PARTITIONTIME < '2019-07-22 10:22:11'\nGROUP BY 1,2\nORDER BY 1,2\n  LIMIT 1920",
      "useLegacySql": false,
      "useQueryCache": true
    },
    "url": "api/datasources/proxy/14/bigquery/v2/projects/gcp-administration/queries"
  },
  "response": {
    "error": {
      "code": 400,
      "message": "Unrecognized name: `service.id`; Did you mean service? at [4:3]",
      "errors": [
        {
          "message": "Unrecognized name: `service.id`; Did you mean service? at [4:3]",
          "domain": "global",
          "reason": "invalidQuery",
          "location": "q",
          "locationType": "parameter"
        }
      ],
      "status": "INVALID_ARGUMENT"
    }
  }
}

**Comment by avivl** [comment]
Try
\`service\`.\`id\` AS metric, instead of \`service.id\` AS metric,

**Comment by marcuspink** [comment]
@avivl that solves the problem. Thank you!

**Comment by avivl** [comment]
@marcuspink you are welcome
