### ISSUE TITLE
Syntax error: Missing whitespace between literal and alias at [11:10]

### ISSUE THREAD

**Issue by m4vr0x** [doitintl/bigquery-grafana#117]
## Bug Report

Hi all,
I'm trying to replicate the Demo use case described in the global README.md in order to export billing data in BigQuery and then use it as source thanks to the plugin.

I followed the steps and think I configured properly using the JSON key file auth method but my query send return error (see the screenshot below)

![Screen Shot 2019-07-22 at 11 31 27 am](https://user-images.githubusercontent.com/7030303/61600638-f6e69080-ac74-11e9-811c-4b66f96ede6d.png)

This is the query in SQL format:
```
#standardSQL
SELECT
 $__timeGroupAlias(usage_start_time,1d),
  `service.description` AS metric,
  sum(`cost`) AS cost
FROM `thanos-211223.billing_data_export.gcp_billing_export_v1_019DA3_01E359_92B8CD`
WHERE
  $__timeFilter(usage_start_time) AND _PARTITIONTIME >= '2019-07-22 04:48:47' AND _PARTITIONTIME < '2019-07-22 10:48:47'
GROUP BY 1,2
ORDER BY 1,2
```

And this is the Query Inspector content:
```
query:"#standardSQL SELECT TIMESTAMP_SECONDS(DIV(UNIX_SECONDS(`usage_start_time`), 86400) * 86400), `service.description` AS metric, sum(`cost`) AS cost FROM `thanos-211223.billing_data_export.gcp_billing_export_v1_019DA3_01E359_92B8CD` WHERE `usage_start_time` BETWEEN TIMESTAMP_MILLIS (1563737930129) AND TIMESTAMP_MILLIS (1563759530129) AND _PARTITIONTIME >= '2019-07-22 05:38:50' AND _PARTITIONTIME < '2019-07-22 11:38:50' GROUP BY 1,2 ORDER BY 1,2 LIMIT 1h"
useLegacySql:false
useQueryCache:true
url:"api/datasources/proxy/2/bigquery/v2/projects/thanos-211223/queries"
response:Object
error:Object
code:400
message:"Syntax error: Missing whitespace between literal and alias at [11:10]"
errors:Array[1]
0:Object
message:"Syntax error: Missing whitespace between literal and alias at [11:10]"
domain:"global"
reason:"invalidQuery"
location:"q"
locationType:"parameter"
status:"INVALID_ARGUMENT"
```

The error mentioned is clear:
`Syntax error: Missing whitespace between literal and alias at [11:10]`

But there's no line 11 (?!)... so I'm sure I'm missing something ... but I'm not able to figure out what

## Specifications

Grafana Version: v6.2.5 (6082d19)
Platform: Docker container in GCP instance

**Comment by avivl** [comment]
@m4vr0x  which version of the datasource are you using?

In the latest version the query should look like this
```
#standardSQL
SELECT
 $__timeGroupAlias(usage_start_time,1d),
  `CAST (`service`.`id`AS String ) AS metric,
  sum(`cost`) AS cost
FROM `thanos-211223.billing_data_export.gcp_billing_export_v1_019DA3_01E359_92B8CD`
WHERE
  $__timeFilter(usage_start_time) AND _PARTITIONTIME >= '2019-07-22 04:48:47' AND _PARTITIONTIME < '2019-07-22 10:48:47'
GROUP BY 1,2
ORDER BY 1,2


```

**Comment by m4vr0x** [comment]
@avivl It's v1.0.0, installed with:
grafana-cli plugins install doitintl-bigquery-datasource

**Comment by avivl** [comment]
can you try to change  \`service.description\` AS metric, to \`service\`.\`description\` AS metric,

**Comment by m4vr0x** [comment]
Yes it works and also just service.description without quotes
BTW `service.description` was the Query Builder syntax

Thanks for your time :-)
