### ISSUE TITLE
Error 1064 in Grafana for making a graph (using mysql database)

### ISSUE THREAD

**Issue by javanman** [doitintl/bigquery-grafana#119]
I am using Grafana(version 5.4.0) to visualize my data on my mysql database. I want to make a graph of my data. I have four columns: id , int1(has float as type), int2(also float) and also date&time.

I would like to make a graph. On the x-axis the time and on the y-axis the value of int1. My tables name is data5.

This is my querry code:

`SELECT
  f AS "time",
  int1
FROM data5
WHERE
  $__timeFilter(f)
ORDER BY f`

this is the error:

Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'int1 FROM data5 WHERE f BETWEEN FROM_UNIXTIME(1563793531) AND FROM_UNIXTIME(15' at line 3

Here is a picture of my Grafana Dashboard:
https://drive.google.com/file/d/1m3kvixaAt6WLtlnN1RmNfBNQToEbbsHL/view?usp=sharing

Here is a picture of my database:
https://drive.google.com/file/d/1AMlvUVAU3bhSGAEvzDQ2jcjWtgrKkK6P/view?usp=sharing

I would be thankful for any kind of help.

**Comment by avivl** [comment]
@javanman the data source  is for BigQuery and not for mysql
