### ISSUE TITLE
Query gets automatically changed on refreshed in grafana dashboard

### ISSUE THREAD

**Issue by SunnySinhaBabu** [doitintl/bigquery-grafana#120]
## Bug Report

The queries are updating with its variable value in query editor itself. I imported a dashboard JSON file containing BigQuery queries. Then I found a few queries are working but most of the queries are not working. I checked that it is updating the value of its variable like __from and __to etc. But it shouldn't happen I think. So I thought as I imported because of that it may be behaving like this. so I created a new dashboard and started writing query but there was also the same thing. 

I installed the BigQuery by garafana-cli as per your instructions. But it was working sometimes when I cloned the BigQuery project from your repo to grafana plugin folder.

So we are surprised about its behavior. Can you please look into this issue?

If have any doubt please post it

## Specifications

  - Version: 1.0.0
  - Platform: Linux(amazon ec2)
  - Grafana Version: 6.1.3

**Comment by avivl** [comment]
@SunnySinhaBabu can you share the queries and specify what exactly is changing?

**Comment by SunnySinhaBabu** [comment]
I am using two query - query A and query B in Grafana. There two issues.

**Issue 1 :** I write Query A in first Query Section in grafana. It is working fine, I am getting data too. Then whenever I am trying to write Query B, it is replacing with Query A.

**Issue 2 :** I am using variables in my query the variable's value is automatically updating For example, 
I am using this one in my query `UNIX_MILLIS(TIMESTAMP_MICROS(event_timestamp)) between $__from and $__to` but it is automatically changing to `UNIX_MILLIS(TIMESTAMP_MICROS(event_timestamp)) between 1563820200000 and 1564425000000` in grafana query editor itself.
