### ISSUE TITLE
Not able to create different panels with bigquery as datasource

### ISSUE THREAD

**Issue by knave07** [doitintl/bigquery-grafana#123]
## Bug Report
I am making a dashboard in grafana, using bigquery as datasource. I made one panel using a query and it worked fine, but when I try to make second panel with different query it gives error `Cannot read property '1' of null`. I tried the same query but still the error was same.  

Query that I am using for first panel:
`SELECT
TIMESTAMP(CONCAT(day, ' 00:00:00+08:45')) as time,
`model_name` as metric ,
model_precision
FROM
    `my_table_name`
WHERE
   _TABLE_SUFFIX
        BETWEEN FORMAT_TIMESTAMP("%Y%m%d", TIMESTAMP('2019-07-20 00:00:00'))
        AND FORMAT_TIMESTAMP("%Y%m%d", TIMESTAMP('2019-08-30 00:00:00'))
ORDER BY
    1`

##ScreenShots
![Untitled_Artwork 2](https://user-images.githubusercontent.com/37116431/62352802-081c8080-b544-11e9-9a9f-a30db9a83539.png)

## Specifications

  - Version: 1.0.0
  - Platform: GKE 
  - Grafana Version: Grafana:6.2.0

**Comment by avivl** [comment]
@knave07 can you try with the latest version 1.0.1?

**Comment by knave07** [comment]
version 1.0.1 worked!!!
Thanks for your time :-)
