### ISSUE TITLE
Documentation and examples

### ISSUE THREAD

**Issue by kevin-whalley-gc** [doitintl/bigquery-grafana#126]
## Feature Request

I'm having some trouble understanding the relationship between a BigQuery query result set and a time series or gauge chart in Grafana. 

**Describe the solution you'd like**
I think samples / walkthrough w/ screenshots would be very helpful from both a wizard and raw SQL POV.

In particular, I am struggling with how I might take a data set of 

time | hostname | response code | response time

And run a chart of response codes grouped by host name, response time, so that I be able to easily distinguish which hosts threw response codes, and on average how long those took. I can write the BigQuery query, but I am not confident in how that feeds into Grafana

My rough attempt is:

SELECT event_timestamp, event_name, response_code, response_completed_time
 FROM database_foo
 group by 1,2,3,4
 WHERE event_name = 'someevent' AND event_timestamp >= '2019-08-09' AND event_timestamp < '2019-08-10'

**Comment by avivl** [comment]
@kevin-whalley-gc we just recruited a new technical writer to our team. He will start working on improving the documents in the next couple of weeks.

For the time being, you can use the metric column in the query builder

**Comment by HugoPuntos** [comment]
Any news about this topic "Documentation and examples"?

**Comment by Tamirk** [comment]
@HugoPuntos we'll soon add more details to the extensive [README.md](https://github.com/doitintl/bigquery-grafana/blob/master/README.md) file which already exists in the repo to include more details per the above

**Comment by LiorRacer** [comment]
Hi @HugoPuntos 
We added query builder and troubleshooting section to the [readme.md](https://github.com/doitintl/bigquery-grafana/blob/master/README.md) file. If you need more please open a new issue
