### ISSUE TITLE
Allow the user of other variables in big query driven variable

### ISSUE THREAD

**Issue by LukeDefeo** [doitintl/bigquery-grafana#127]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I have the same dashboard in multiple envs and there is a corresponding big query project for each env. For all our panel queries we create a Constant variable called $projectId and refer to that in the query. We have automation that sets this variable for each dashboard. I would like to also have a grafana list variable powered by a big query query such as

```select distinct foo from `$projectId.dataset.table` ```

unfortunately, it doesn't pick up this constant variable that I have setup. 

**Describe the solution you'd like**
I would like the above query to pick up my constant variable when used as a variable query

**Describe alternatives you've considered**
Not sure there's anything clean.  We like the templating of the project id via the constant variable as it gives us an easy thing to alter in our automation templating

**Teachability, Documentation, Adoption, Migration Strategy**
its a new feature and will be naturally picked up by people that need it

**Comment by avivl** [comment]
@LukeDefeo I have tested using custom var and constant var and both worked just find

**Comment by avivl** [comment]
@LukeDefeo closing this. Feel free to reopen if you think we still got an issue with this
