### ISSUE TITLE
Limit added to query even if not specified

### ISSUE THREAD

**Issue by kevin-whalley-gc** [doitintl/bigquery-grafana#128]
## Bug Report

A LIMIT is added to my raw BigQuery

## Expected Behavior

The only LIMIT in the query is specified by myself

## Actual Behavior

When writing a raw BigQuery vs using Query Builder I noticed I was not receiving all of the data. Upon using the Query Inspector I noticed a LIMIT # that I did not write.

When I added my own LIMIT, the query still had the LIMIT # appended to it

E.g.

SELECT `event_timestamp`, CONCAT(CAST (`name`AS String ),CAST (`network_info`.`response_code` AS String)) AS metric, (network_info.response_completed_time_us / 1000) AS thing FROM `table` WHERE `event_timestamp` BETWEEN TIMESTAMP_MILLIS (1565814489427) AND TIMESTAMP_MILLIS (1566419289427) AND network_info.response_code >= 1 ORDER BY `event_timestamp` LIMIT 5000 LIMIT 1536"

Raw BigQuery

SELECT `event_timestamp`, 
CONCAT(CAST (`name`AS String ),CAST (`network_info`.`response_code` AS String)) AS metric, 
(network_info.response_completed_time_us / 1000) AS thing
FROM `table` 
WHERE $__timeFilter(event_timestamp) AND network_info.response_code >= 1
ORDER BY `event_timestamp` LIMIT 5000

## Specifications

  - Version:
  - Platform:
  - Grafana Version: 6.3.2 Enterprise

**Comment by kevin-whalley-gc** [comment]
In looking for how the LIMIT is added to the query I see it runs off of the options like so:

![image](https://user-images.githubusercontent.com/11445405/63474340-a908a800-c42d-11e9-8d77-d35f72ec8c48.png)

I believe a bug still exists for where the raw query doesn't overwrite the options, and there may also be a bug in calculating the one pixel per data point - there was empty space in my chart

**Comment by kevin-whalley-gc** [comment]
specified 5000 data point max

![image](https://user-images.githubusercontent.com/11445405/63474413-e53c0880-c42d-11e9-8643-e8fe7943c3a3.png)

Auto data points

![image](https://user-images.githubusercontent.com/11445405/63474439-069cf480-c42e-11e9-98da-65e40f130118.png)

**Comment by avivl** [comment]
@kevin-whalley-gc LIMIT is added to hone the maxdatapoint value.
I'll make a fix that the LIMIT will not be added if it was already specified in the raw query
