### ISSUE TITLE
Add macros $__timeFrom() and $__timeTo()

### ISSUE THREAD

**Issue by fermuch** [doitintl/bigquery-grafana#130]
## Feature Request

**Is your feature request related to a problem? Please describe.**
The only way I could find to get the start and end time is by using the macro `$__timeFilter()`, but in some occasions I need to extract only the start or the end of the range.

**Describe the solution you'd like**
Adding `$__timeFrom()` and `$__timeTo()` (or `$__from` and `$__to`) would resolve my problem.

**Describe alternatives you've considered**
I've tried creating a function in javascript to transform the output of `$__timeFilter()` into an string, to then regex and extract the start and end, but it is too cumbersome and prone to failure.

**Teachability, Documentation, Adoption, Migration Strategy**
On grafana docs `$__from` and `$__to` variables [are covered](https://grafana.com/docs/reference/templating/#time-range-variables)

**Comment by avivl** [comment]
@fermuch I added 2 macros
- $__timeFrom(column) ; column > '2017-04-21T05:01:17Z'
- $__timeTo(column); column < '2017-04-21T05:01:17Z'

They are in the master branch and will be part of the 1.0.2 release.
Thank you for suggesting this!
