### ISSUE TITLE
ORDER BY in query builder

### ISSUE THREAD

**Issue by artjomzab** [doitintl/bigquery-grafana#137]
## Feature Request

**Is your feature request related to a problem? Please describe.**

![Screenshot 2019-09-11 17 17 40](https://user-images.githubusercontent.com/524580/64710358-169d7680-d4b8-11e9-9de0-360de87e0cac.png)

I created this graph with query builder. By default you do ORDER BY 1,2 1 being timestamp and 2 the metric. This causes the order of the metrics in the graph to change on every refresh.

**Describe the solution you'd like**

Change the order in the query builder. Be able to ORDER BY metric1 ASC/DESC, metric2 ASC/DESC...

**Describe alternatives you've considered**

Create a raw query. But raw query is less fun and flexible.

**Comment by avivl** [comment]
@artjomzab 
![image](https://user-images.githubusercontent.com/3265061/68105587-ac1d1b80-fee7-11e9-9ce0-b4a5bbd5393b.png)
