### ISSUE TITLE
Publish new version to grafana's repository

### ISSUE THREAD

**Issue by fermuch** [doitintl/bigquery-grafana#138]
Hello! It's been quite some time, features and fixes since ver 1.0.1 (latest published on grafana).

Is it possible that you release a new version?

**Comment by avivl** [comment]
@fermuch Yiu can always get the latest code from the master branch.
The latest version is [1.0.2](https://github.com/doitintl/bigquery-grafana/archive/1.0.2.zip).
I submitted a [request](https://github.com/grafana/grafana-plugin-repository/pull/472) for the Grafana site 9 days ago and I'm waiting for their approval.

cc: @daniellee @alexanderzobnin @schmidtl

**Comment by fermuch** [comment]
Thanks!
