### ISSUE TITLE
Query builder ignores column argument

### ISSUE THREAD

**Issue by fermuch** [doitintl/bigquery-grafana#139]
## Bug Report

The macros `$__timeFilter`, `$__timeFrom` and `$__timeTo` ignore the column argument.

As an example, the query:
```sql
SELECT $__timeFrom(column)
```

should be converted to:
```sql
SELECT `column` > TIMESTAMP_MILLIS (1568360548569)
```

but instead it is converted to:
```sql
SELECT `time` > TIMESTAMP_MILLIS (1568360548569)
```

The same happens to the other macros.

If instead the `column` argument is provided as an string `'column'` or in any other form (with backticks, for example), the query builder fails to convert it and just passes the string literal to bigquery (`$__timeFrom(column)`)

## Specifications

  - Version: 1.0.2
  - Platform: Firefox 69.0 (since it is a frontend bug)
  - Grafana Version: 5.4.2

**Comment by avivl** [comment]
@fermuch I'm not sure I understand the issue.
The $__timeFilter, $__timeFrom and $__timeTo are only relevant to the Time column

**Comment by fermuch** [comment]
But what if I have events, which have a `created_at` column (when it was created on the server, which is the time partition) but also two timestamps, `started_at` and `ended_at`, for which I want to filter by those instead of `created_at`?

**Comment by avivl** [comment]
You will have to do it without the macro

**Comment by fermuch** [comment]
I can't filter without the macro, since I can't get the milliseconds for the start and end of the user chosen time filter

**Comment by fermuch** [comment]
Adding `$__from` and `$__to` which only get translated into the millis would solve this problem, and it already is a global [built-in](https://grafana.com/docs/reference/templating/#global-built-in-variables) in grafana. What's your opinion on that?

An example query would be:

```sql
SELECT `started_at` > TIMESTAMP_MILLIS ($__from)
```

Which is translated into:

```sql
SELECT `started_at` > TIMESTAMP_MILLIS (1568360548569)
```

And if those two are added, also supporting `$__interval_ms` (returning the $__interval as milliseconds) would be useful, for cases where `$__interval()` is not enough.

[Here](https://grafana.com/docs/reference/templating/#the-interval-ms-variable) are the docs for `$__interval_ms`

**Comment by avivl** [comment]
Adding $__millisTimeTo and $__millisTimeFrom
