### ISSUE TITLE
Only first column from the raw query is visualized   

### ISSUE THREAD

**Issue by ontofractal** [doitintl/bigquery-grafana#143]
## Bug Report

Only the first column from the raw SQL query result set is charted in Graph panel, no other series are visualized. 

I may be missing something very obvious here, thanks!

## Expected Behavior

Multiple series that correspond to columns are expected to be visualized as multiple series.

## Actual Behavior

Only one of series (the first column) is visualized.

## Steps to Reproduce the Problem

The query in question is as follows
```
SELECT
  timestamp AS time,
  f1.vm__memory__last_values__atom as atom,
  f1.vm__memory__last_values__atom_used as atom_used
FROM
 `...` AS t0
INNER JOIN
  UNNEST(t0.metadata) AS f1
ON
  TRUE
WHERE
  f1.vm__memory__last_values__total IS NOT NULL
ORDER BY
  timestamp DESC
```
## Specifications

  - Version: 1.0.1
  - Platform: default Grafana Docker container
  - Grafana Version: 6.3.5

**Comment by avivl** [comment]
@ontofractal  Assuming that` f1.vm__memory__last_values__atom ` is your value coulmn and `f1.vm__memory__last_values__atom_use` is your metric 
you should use `f1.vm__memory__last_values__atom_use as metric`

**Comment by ontofractal** [comment]
@avivl both atom and atom_use value columns, there are about 10 more in the query, I've removed them for simplicity.

**Comment by avivl** [comment]
If you want to visualize multiple values in the same graoph you can use multiple queries
