### ISSUE TITLE
documentation: note that alerting isn't supported by the plugin

### ISSUE THREAD

**Issue by aerickson** [doitintl/bigquery-grafana#144]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Lots of people would like to use this plugin with alerting, but it doesn't work. Ideally, save them time by documenting that it doesn't work.

see #67 and #133

**Describe the solution you'd like**
Documentation indicating that alerting doesn't work with the bigquery plugin.

**Describe alternatives you've considered**
I can't think of any. Having users search through tickets or finding out after they've configured bigquery queries and go to set alerts is... not ideal.

**Teachability, Documentation, Adoption, Migration Strategy**
not applicable

**Comment by spark2ignite** [comment]
@aerickson we have updated our README file to reflect lack of support for alerts.
