### ISSUE TITLE
Show errors in Grafana UI

### ISSUE THREAD

**Issue by weeco** [doitintl/bigquery-grafana#145]
## Expected/Actual Behavior

If your query is invalid it shows an infinite loading loading spinner on the dashboard and you have no chance to see what is going on. If you open the query inspector there's a response code (e. g. 400) along with an error message which explains why the query has failed. This should be shown as error.

## Steps to Reproduce the Problem

  1. Send an invalid BigQuery query

## Specifications

  - Version: 1.0.1
  - Platform: Docker/Kuebrnetes
  - Grafana Version: 6.3.5

**Comment by avivl** [comment]
@weeco Errors should appear in red in the upper left corner, Please LMK if this is not the case

**Comment by weeco** [comment]
This is not the case for me. I always have to open the query inspector to check details

**Comment by avivl** [comment]
can you share a screen shoot?

**Comment by weeco** [comment]
Closed as I could not replicate this behaviour anymore. I'll reopen it with the requested screenshot once I stumble across it again.
