### ISSUE TITLE
Canceled:Query Changed while running

### ISSUE THREAD

**Issue by JorritSalverda** [doitintl/bigquery-grafana#149]
## Bug Report

I very frequently see Grafana showing the following error in graphs:

```
Canceled:Query Changed while running
```

This wasn't always the case. It's like the running job no longer gets cancelled before a new one is created.

## Expected Behavior

If a refresh happens while queries are still running it should cancel the running query job and start a new one.

## Actual Behavior

It shows the red exclamation mark with the error mentioned above and no longer finishes the query but waits for a next refresh instead.

## Steps to Reproduce the Problem

  1. Create a graph based on a BiqQuery query
  1. Click refresh in the Grafana dashboards twice in a short period while the first occurence is still running
  1. The error shows, no refresh of the graphs happens

## Specifications

  - Version: `1.0.2`
  - Platform: docker image `grafana/grafana`
  - Grafana Version: `6.3.6`

**Comment by avivl** [comment]
@JorritSalverda  we are on holiday for the next few days (Jewish new year).
I'll look at it once I'm back in the office

**Comment by avivl** [comment]
@JorritSalverda It might be related to this. https://github.com/grafana/grafana/issues/19332

There aren't any changes in 1.0.2 that may cause this change of behavior

**Comment by JorritSalverda** [comment]
I'm not sure at what version upgrade of either the plugin or grafana this started happening. It's been there for quite a while now, but it was always the case.

But it could indeed be caused by a change in Grafana. After it shows the error, it stops showing the spinner as well even though it continuous to run the last query in the background and eventually updates the graphs. However it doesn't happen in edit mode only, also when just viewing the dashboard.

But perhaps it's fixable in the plugin? Do you receive a cancel event from Grafana that can be used to cancel any running queries?

**Comment by JorritSalverda** [comment]
In Grafana version 6.4.1 this no longer seems to happen, the old query requests are cancelled when ones start before they're finished, without every showing the error. I'll close this ticket.
