### ISSUE TITLE
Duplicate Limit in manual Queries

### ISSUE THREAD

**Issue by weeco** [doitintl/bigquery-grafana#150]
## Bug Report

I want to create a Table which shows the most expensive BigQuery jobs ran by our users/services. Therefore I am forced to use the manual query anyways. My query looks like this:

```sql
SELECT UserId, Query, TotalCost
FROM `projectname.billing.bigquery_audit`
WHERE
  $__timeFilter(JobCreateTime)
ORDER BY TotalCost DESC
LIMIT 10
```

The query fails because of: "invalidQuery: Syntax error: Unexpected keyword LIMIT at [6:10]". That didn't make sense for me and hence I opened the query inspector. There I can see the generated query and that there's a second LIMIT parameter:

`query:"SELECT UserId, Query, TotalCost FROM `projectname.billing.bigquery_audit` WHERE `JobCreateTime` BETWEEN TIMESTAMP_MILLIS (1567415998923) AND TIMESTAMP_MILLIS (1570007998923) ORDER BY TotalCost DESC LIMIT 10 LIMIT 795"`

## Expected Behavior

It shouldn't attach any further LIMIT parameter when I have specified an own one.

## Actual Behavior

It always appends LIMIT 795, no matter whether I have specified a limit or not. I assume this is only the case when I use "Format as table".

## Steps to Reproduce the Problem

Described above.

## Specifications

  - Version: 1.0.2
  - Platform: Kubernetes
  - Grafana Version: 6.4.0

**Comment by avivl** [comment]
It looks you  are missing a time field in the query

**Comment by weeco** [comment]
Can you eloborate that? I am using the time filter macro and it seems like it does what I expected (see the where condition)

**Comment by weeco** [comment]
@avivl bump

**Comment by avivl** [comment]
In your select statement you should have a time filed(timestamp, datetime etc)

**Comment by weeco** [comment]
@avivl Why is that necessary? If I remove the LIMIT in my query it works completely fine (but I get hundreds of rows).

**Comment by avivl** [comment]
I tried it without any problems.
Can you try to recreate the visualization?

**Comment by weeco** [comment]
I have recreated the visualization but the issue is still exactly the same. I have attached a screenshot.

<img width="1625" alt="Screenshot 2019-10-10 at 14 50 40" src="https://user-images.githubusercontent.com/23424570/66570372-c1638c00-eb6d-11e9-87eb-ee752bed1b94.png">
