### ISSUE TITLE
With send anonymous usage data disabled mixpanel requests are still made

### ISSUE THREAD

**Issue by JorritSalverda** [doitintl/bigquery-grafana#151]
## Bug Report

I spotted requests being made to api.mixpanel.com from my private Grafana setup and tracked in back to originate from this plugin.

Fortunately collecting data can be disabled from the data source settings, however it still seems to send requests to mixpanel, although now just 2 instead of 3.

I still see the following 2 requests being made:

- https://api.mixpanel.com/decide/?verbose=1&version=1&lib=web&token=86fa5c838013959cc6867dc884958f7e&ip=1&_=1570456515078
- https://api.mixpanel.com/track/?data=***&ip=1&_=1570456515086

## Expected Behavior

No requests to be made towards mixpanel.

## Actual Behavior

Still sending 2 requests.

## Specifications

  - Version: `1.0.2`
  - Platform:  `grafana/grafana` container
  - Grafana Version: `6.4.1`

**Comment by avivl** [comment]
@JorritSalverda The calls to the mixpanel send data are only made in this case
`if (this.jsonData.sendUsageData !== false)`. Can you share the payload so I better understand the data that is sent? (You can email it to me if you don't want to share it on github)

**Comment by JorritSalverda** [comment]
@avivl I've mailed you the 2 full requests still getting sent to mixpanel.
