### ISSUE TITLE
Explore not working on Grafana 6.4.3

### ISSUE THREAD

**Issue by eladamitpxi** [doitintl/bigquery-grafana#156]
## Expected Behavior
Explore tab in grafana 6.4.3 to work with no errors

## Actual Behavior
When loading the explore tab and changing to the big-query datasource a 404 error is received from .../api/datasources/proxy/45/bigquery/v2/projects/px-bq-adhoc/jobs/no-such-jobs and an error message of "Cannot read property 'indexOf' of undefined" is visible in the UI

## Steps to Reproduce the Problem

  1. Access grafana
  2. Click the Explore button
  3. Choose a big-query connection

## Specifications

  - Version: 1.0.2
  - Platform: docker over coreos
  - Grafana Version: 6.4.3

**Comment by avivl** [comment]
@eladamitpxi Did you try to create a query?

**Comment by eladamitpxi** [comment]
Yes, didn't help

**Comment by avivl** [comment]
@eladamitpxi Once there is a valid query everything should work. Can you share a screen cast?
