### ISSUE TITLE
Allow overwritting the "running in" project

### ISSUE THREAD

**Issue by eladamitpxi** [doitintl/bigquery-grafana#157]
## Feature Request

**Is your feature request related to a problem? Please describe.**
When using multiple projects which host data (e.g. public projects) or flat-rate pricing and we need to run the grafana queries under a specific project for slot usage to go to a specific allocation, we can't use the drop down menu UI and are forced to manually input the query as it controls both the table being queried as well as the project it runs in

**Describe the solution you'd like**
We suggest adding an option to overide the "running in" project for this use case

**Comment by avivl** [comment]
@eladamitpxi We thinking of adding a field to the plugin configuration that will be the name of the project that will run the queries. WDYT?
