### ISSUE TITLE
Support using $__timeFilter in variable query

### ISSUE THREAD

**Issue by JorritSalverda** [doitintl/bigquery-grafana#158]
## Feature Request

**Is your feature request related to a problem? Please describe.**

Variable queries are currently across the entire data set it queries; it would be nice to be able to use the selected time range to limit the number of partitions to be queried to keep costs down and have results returned that are actually present inside the time range.

**Describe the solution you'd like**

I can limit the queried partitions by adding a static condition like

```sql
WHERE
  _PARTITIONTIME > TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 30 DAY)
```

It would be nice though if i can use either

```sql
WHERE
  $__timeFilter(_PARTITIONTIME)
```

or 

```sql
WHERE
  $__timeFrom(_PARTITIONTIME)
```

**Comment by fermuch** [comment]
This is not exactly what you're asking for, but you can get the same result doing:

`_PARTITIONTIME > $__millisTimeFrom(time)`

See #139 for more context

**Comment by avivl** [comment]
@JorritSalverda is @fermuch suggestions work for you?

**Comment by JorritSalverda** [comment]
Unfortunately this doesn't get resolved and gets sent to BQ as `_PARTITIONTIME > $__millisTimeFrom(time)`, resulting in a failing query.

**Comment by JorritSalverda** [comment]
What actually does seem to work is

```sql
_PARTITIONTIME >= TIMESTAMP_MILLIS ($__from) AND _PARTITIONTIME <= TIMESTAMP_MILLIS ($__to)
```

Seems good enough for what I'm trying to accomplish, so will close the issue.
