### ISSUE TITLE
Unable to query partitioned tables

### ISSUE THREAD

**Issue by karasarvani** [doitintl/bigquery-grafana#162]
Unable to query a partitioned table here .

Initially it has hit this URL 
**URL** : https://grafana.internal.svc.k8s.mum.juspay.net/api/datasources/proxy/32/bigquery/v2/projects/project_id/queries
**RESPONSE**: {
  "kind": "bigquery#queryResponse",
  "jobReference": {
    "projectId": "project_id",
    "jobId": "job_id",
    "location": "asia-south1"
  },
  "jobComplete": false
}
It returned 200 even though the jobComplete was false then it started hitting the other API 
**URL:**
https://grafana.internal.svc.k8s.mum.juspay.net/api/datasources/proxy/32/bigquery/v2/projects/project_id/queries/job_id
**RESPONSE:** It throws a 404 not found error 
Sample error code : error: {code: 404, message: "Not found: Job project_id:job_id",…}}
error: {code: 404, message: "Not found: Job project_id:job_id",…}

**Comment by avivl** [comment]
@karasarvani 
Retruning jobComplete - false is normal.
You should wait until the query is done and not navigate away from the page or change the query

**Comment by karasarvani** [comment]
I haven't changed the query or navigated from the page. This plugin works for sharded tables in my case but not partitioned tables

**Comment by avivl** [comment]
Can you share your table schema/definition?

**Comment by karasarvani** [comment]
Hi avivl,

The same query works on the bigquery console. I am sharing the table info 

<img width="410" alt="Screenshot 2019-11-04 at 5 44 02 PM" src="https://user-images.githubusercontent.com/13009325/68120354-1b682f00-ff2b-11e9-877b-8c08d5ca6a51.png">

**Comment by avivl** [comment]
Thanks,

From the Grafan UI, it is working on all kinds of partitioned tables.
Can you go to your browser console and copy the log output?

**Comment by karasarvani** [comment]
Please find it here. Have trimmed/replaced sensitive information

**Comment by avivl** [comment]
Nothing attached

**Comment by karasarvani** [comment]
Apologies
[grafana.internal.svc.k8s.mum.juspay.net-1572873107425.log](https://github.com/doitintl/bigquery-grafana/files/3804158/grafana.internal.svc.k8s.mum.juspay.net-1572873107425.log)

**Comment by avivl** [comment]
Which version of the plugin are you using?

**Comment by karasarvani** [comment]
1.0.2

**Comment by avivl** [comment]
I can not see the query in the log

**Comment by karasarvani** [comment]
I have trimmed it in the log sent to you but I was able to view it on my
console

**Comment by avivl** [comment]
@karasarvani I can't reproduce the problem on my end

**Comment by karasarvani** [comment]
Hi Aviv

I found that regardless of whether it's partitioned or any table if the
/queries endpoint doesn't return query results then it hits the
queries/job_id endpoint which fails at times. Will create a separate issue
as the current heading is misleading
