### ISSUE TITLE
Is it possible to install plugin on GCP VM hosted Grafana?

### ISSUE THREAD

**Issue by AlienDeg** [doitintl/bigquery-grafana#164]
Sorry guys, but I have no idea where to ask it. I have Grafana hosted on my GCP https://console.cloud.google.com/marketplace/details/click-to-deploy-images/grafana?filter=category:monitoring&id=7f529a97-13af-4bcd-8050-3c5a63369d33&authuser

But I can't find a way to do it. grafana-cli: command not found when I try to use it, and I can't access plugins folder (or I don't know where it is). 

Any hope?

**Comment by avivl** [comment]
How did you installed Grafana?
Grafan cli is part of the installation
https://grafana.com/docs/administration/cli/
You can also install from here
https://grafana.com/grafana/plugins?type=datasource
