### ISSUE TITLE
$__timeFilter does not respect timezone selected in dashboard

### ISSUE THREAD

**Issue by jpuerto96** [doitintl/bigquery-grafana#165]
When attempting to use the raw SQL editor, it appears that the filter does **not** respect the selected timezone for the dashboard, if the timepicker is using a pre-defined range.

For example, using Last 12 hours, the raw SQL sent through to BigQuery is as follows:
`WHERE time BETWEEN '2019-11-06 01:50:03' AND '2019-11-06 13:50:03'`

On the other hand, if I use a custom time range for 2019-11-06 00:00:00 to 2019-11-06 23:59:00, the raw SQL sent through to BigQuery is as follows:
`WHERE time BETWEEN '2019-11-05 19:00:00' AND '2019-11-06 18:59:00'`

The time column in BigQuery is stored in UTC time. The ultimate question here is how can I force the $__timeFilter() to use UTC time.

Edit: The machine's timezone is EST. Therefore, if it is 13:50:03 and UTC is selected, it should set the time to 18:50:03.

**Comment by jpuerto96** [comment]
Potential work around for anyone having issues with this, rather than relying on $__timeFilter() use the following where clause to force UTC time in your query:

`WHERE TIMESTAMP(time) > TIMESTAMP_MILLIS($__from) AND TIMESTAMP(time) < TIMESTAMP_MILLIS($__to)`

**Comment by avivl** [comment]
![image](https://user-images.githubusercontent.com/3265061/68384598-99614b80-0160-11ea-95be-77bc13597880.png)
