### ISSUE TITLE
Allow specifying processing location

### ISSUE THREAD

**Issue by nauris-sadovskis** [doitintl/bigquery-grafana#172]
## Feature Request

**Is your feature request related to a problem? Please describe.**
When running queries on metatables that are available in multiple locations (`INFORMATION_SCHEMA`), there should be an option to choose override processing location as in our case, running the same query in 2 locations returns different values. 

**Describe the solution you'd like**
A selector in the UI that allows specifying processing location for each query. 

**Describe alternatives you've considered**
N/A

**Teachability, Documentation, Adoption, Migration Strategy**
This could be set to default (`US`), so existing users should not be affected. 

Let me know if you need more info.

Thanks,
Nauris

**Comment by nauris-sadovskis** [comment]
Just to add to the previous comment, in our case BigQuery Flat Rate is tied to a specific region (EU), so running queries across global meta tables (US) actually cost us money. Hope this helps!

**Comment by nauris-sadovskis** [comment]
@avivl , blazing fast! :D thanks - works like a charm :)

**Comment by JorritSalverda** [comment]
Hi @avivl it would be good to be able to set the default location on the data source. Since we store everything in the EU I now have to go through hundreds of graphs to change the location.

I'm also missing the ability to set the location for variable queries.

**Comment by avivl** [comment]
@JorritSalverda #178
