### ISSUE TITLE
The bigquery plugin does not have support for alerting.

### ISSUE THREAD

**Issue by cherryguille** [doitintl/bigquery-grafana#176]
## Feature Request

**Is your feature request related to a problem? Please describe.**
The bigquery plugin does not have support for alerting.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

**Describe alternatives you've considered**
The developers would have to change the query part of the plugin to add alerting support (by converting some of it to be a backend plugin).

**Comment by avivl** [comment]
Still in Alpha
https://github.com/grafana/grafana-plugin-sdk-go/

**Comment by z13smehb** [comment]
Hello, 

First, all thanks for your work.
When do you plan to integrate this feature ?

Thanks in advance.
Rgs,

Sophian Mehboub

**Comment by smehboub** [comment]
Hello, 

First, all thanks for your work.
When do you plan to integrate this feature ?

Thanks in advance.
Rgs,

Sophian Mehboub

**Comment by avivl** [comment]
I do not have a date.
I'm waiting for the Grafana team to provide the relevant information

**Comment by ICiscoStu** [comment]
Hello,

Have you received the relevant information from the Grafana team for you to integrate this feature?

thanks in advance

**Comment by avivl** [comment]
Not yet

**Comment by LukeDefeo** [comment]
hey @avivl  this pr indicates alerting can be done since grafana 7.0? https://github.com/grafana/grafana/issues/6841

Am i reading this right, Im not familiar with the internals of grafana (beyond this library)

**Comment by ptomasroos** [comment]
Nice, great news!

**Comment by avivl** [comment]
Hi @LukeDefeo 
I'm not the maintainer of this any more.
@Tamirk @LiorRacer

**Comment by smehboub** [comment]
Hello,

Have you any news ?

Thanks in advance 
Rgs,

Sophian Mehboub

**Comment by stefan345** [comment]
I would also like to have a rough idea on when this could be used realistically?
I have a grafana/bigquery setup and I would love to setup alerting.

**Comment by cyrilou242** [comment]
Would be very interested in this feature too. (this message just to push this feature request)

**Comment by LiorRacer** [comment]
Hi all,

The [documentation](https://github.com/grafana/grafana/issues/16066) was finally released 10 days ago, and I already started working on it.
Here is a small teaser:
![image](https://user-images.githubusercontent.com/13584904/83972819-056c8380-a8eb-11ea-91ef-1454136b300c.png)

Will update when it is production ready.

**Comment by ptomasroos** [comment]
So excited !

**Comment by ICiscoStu** [comment]
this is amazing, thank you!

**Comment by smehboub** [comment]
Woohoo, great !!!
Thank you very much

**Comment by amosshahar** [comment]
exciting!

**Comment by Tamirk** [comment]
Merged to V2.0.0
