### ISSUE TITLE
v1.0.4 is not available on public plugin directory

### ISSUE THREAD

**Issue by ptomasroos** [doitintl/bigquery-grafana#177]
## Expected Behavior

I can install the latest version

## Actual Behavior
https://grafana.com/grafana/plugins/doitintl-bigquery-datasource
1.0.2 is the latest

Is there any reason why official plugin directory is not insync with the releases (available on the Github / releases page)

**Comment by avivl** [comment]
We don't have control on when Grafana will update there repo
https://github.com/grafana/grafana-plugin-repository/pull/514

**Comment by ptomasroos** [comment]
Ah ok!
Will install from source moving on then! Thanks for the explanation :)
