### ISSUE TITLE
Applying _table_suffix filter based on the range selected

### ISSUE THREAD

**Issue by Prashanthreddya** [doitintl/bigquery-grafana#179]
I noticed that the time filter option available in grafana-bigquery only permits time filter on a specific field. But in case we have date-sharded tables (that have the same prefix and the suffix follows the date), we would want to apply a filter based on the date range which the user selects. 

Example:
select 
     fields
from
     dataset.table*
where
    $__time_filter(time_column)

But this would not restrict the tables which the query would run, because the filter is not applied on the table suffix. That would extensively query all the tables which would increase the run time and cost of the query. 
Is there an alternative available to apply a filter on the table suffix. 

Example:
select 
     fields
from
     dataset.table*
where
    _table_suffix between '20190101' and '20190125' --the values for this should be decided based on the range user is selecting
    and $__time_filter(time_column)

Please let me know if a function is already available for this.

**Comment by avivl** [comment]
1. Which version are you using?
2. Please open the developer console in your browser and copy the generated query

**Comment by Prashanthreddya** [comment]
1: 1.0.2
2: The query generated currently:

```
select
  timestamp_seconds(div(unix_seconds(`time_column`), 3600)*3600) as time
  metric1,
  metric2,
  metric3,
  ...
from
  dataset.table20191115
where
  `time_column` between timestamp_millis (1573729889696) and timestamp_millis (1573816289696) 
group by time 
order by time 
limit 720

```
This works fine if I want to fetch the visualizations for that particular day, but when I want to fetch for a range of days, it is necessary that I use regex in the from clause and _table_suffix in the where clause. My question was if a feature exists where in I can apply filter on _table_suffix based on the range selected by user. 

For Example: 
This is what I would want to achieve. 

```
select
  timestamp_seconds(div(unix_seconds(`time_column`), 3600)*3600) as time
  metric1,
  metric2,
  metric3,
  ...
from
  dataset.table*
where
  _table_suffix between '20191010' and '20191018'
   and  `time_column` between timestamp_millis (XYZ) and timestamp_millis (ABC) 
group by time 
order by time 
limit 720

```

**Comment by avivl** [comment]
If you are using the query builder your query should look like this

```
#standardSQL
SELECT
 TIMESTAMP_SECONDS(DIV(UNIX_SECONDS(`time`), 86400) * 86400),
  count(`total_ms`)
FROM `jzzz.yy.events_*`
WHERE
  `time` BETWEEN TIMESTAMP_MILLIS (1259224251241) AND TIMESTAMP_MILLIS (1574757051241) AND  _TABLE_SUFFIX BETWEEN '20091126' AND '20191126' 
GROUP BY 1
ORDER BY 1
  LIMIT 960
```

**Comment by Prashanthreddya** [comment]
Yes. This is how I want the query to look like. How do I generate a query like this wherein _TABLE_SUFFIX BETWEEN **'20091126' AND '20191126'**  part is altered based on the time range user selects?

**Comment by avivl** [comment]
If  you are using the query builder this is done for you

**Comment by Prashanthreddya** [comment]
Using the query builder, and $__timeFilter I only obtain the below filter in where clause in the constructed query:
 ``fulfillment_created_at` BETWEEN TIMESTAMP_MILLIS (1574687114950) AND TIMESTAMP_MILLIS (1574773514950)` 
And not the filter you mentioned earlier in the thread.

**Comment by avivl** [comment]
Can you attach screenshots of how it looks in the query builder?

**Comment by Prashanthreddya** [comment]
Screenshot of the query builder:

![ss](https://user-images.githubusercontent.com/14885699/69643631-9f748900-1089-11ea-953a-f93bec0be0cd.png)

Generated SQL:
```
#standardSQL
SELECT
 TIMESTAMP_SECONDS(DIV(UNIX_SECONDS(`timefield`), 3600) * 3600),
  CAST (`metric1`AS String ) AS metric,
  count(`id`) AS total
FROM `project_id.dataset.tablename*`
WHERE
  `timefield` BETWEEN TIMESTAMP_MILLIS (1574519842238) AND TIMESTAMP_MILLIS (1574865442240)
GROUP BY 1,2
ORDER BY 1,2 LIMIT 683
```

I would want an additional filter which would generate the where clause:
``timefield` BETWEEN TIMESTAMP_MILLIS (1574519842238) AND TIMESTAMP_MILLIS (1574865442240) AND _TABLE_SUFFIX BETWEEN '20191123' AND '20191127'`

**Comment by avivl** [comment]
What's the naming of your tables? it should be something like tablename_YYYYMMDD.
Did you enter table* manually?

**Comment by Prashanthreddya** [comment]
Yes. I entered table* manually. 
Table format: tablenameYYYYMMDD. There is no underscore in the name.

**Comment by avivl** [comment]
The plugin supports only this format tablename_YYYYMMDD which is detected automaticly

**Comment by Prashanthreddya** [comment]
Oh. That's the issue then. If there is underscore, I don't have to manually mention tablename*?

**Comment by avivl** [comment]
correct

**Comment by Prashanthreddya** [comment]
Thank you for your help. Appreciate it.

**Comment by Prashanthreddya** [comment]
Are you planning to add support to the format tableYYYYMMDD?

**Comment by Prashanthreddya** [comment]
Is it possible to add support for the table name following the nomenclature tablenameYYYYMMDD?

**Comment by avivl** [comment]
We are not planning to add this,
