### ISSUE TITLE
BigQuery: Not found: Dataset XXX was not found in location US (wrong region)

### ISSUE THREAD

**Issue by sfindeisen** [doitintl/bigquery-grafana#183]
## Bug Report

It looks the queries are going to the wrong region (US), while my dataset is in EU. But I can't see the way to configure that. What am I missing?

I can't see the region setting in the dashboard, nor in the service account key.

## Expected Behavior

Ability to configure BigQuery dataset region.

## Actual Behavior

My dashboard doesn't work, apparently because the queries are going to the wrong region.

## Specifications

  - Version: 1.0.4
  - Platform: Ubuntu
  - Grafana Version: 6.5.1

**Comment by sfindeisen** [comment]
It seems to work after downgrading the plugin version to `1.0.1`.

**Comment by avivl** [comment]
@sfindeisen On version 1.04 you can set the processing location for each query
![image](https://user-images.githubusercontent.com/3265061/70177641-6ec4cd00-16e3-11ea-81d6-341f26f918b7.png)

The version in the master branch (which will become 1.0.5 someday) supports also a global processing location for a datasource
