### ISSUE TITLE
Timeseries and metrics

### ISSUE THREAD

**Issue by filemon** [doitintl/bigquery-grafana#186]
## Bug Report
I have a table with temperatures per session. Using a query builder I configured a query retrieving all temperatures with the session as a metric column. Even though I have a couple of sessions in my db for the given day, I'm only able to see a single session at a time. 

## Expected Behavior

I can see temperatures for all sessions per day with different colour for each session. 

## Actual Behavior

I can only see a single session for the whole day (the first one). If I drill down the time window, I can see other session for the given day. 

## Steps to Reproduce the Problem

  1.

## Specifications

  - Version:
  - Platform:

  - Grafana Version: cloud version e.g. grafana.net

<img width="1226" alt="Screenshot 2019-12-16 at 17 48 54" src="https://user-images.githubusercontent.com/35973/70927096-abbb8880-202e-11ea-8a11-fa81440c2e92.png">

<img width="1348" alt="Screenshot 2019-12-16 at 17 48 39" src="https://user-images.githubusercontent.com/35973/70927097-abbb8880-202e-11ea-8ec0-117d19081b8c.png">

<img width="1133" alt="Screenshot 2019-12-16 at 17 49 30" src="https://user-images.githubusercontent.com/35973/70927139-c0981c00-202e-11ea-9f54-2fcd4f940dd2.png">

<img width="354" alt="Screenshot 2019-12-16 at 17 50 06" src="https://user-images.githubusercontent.com/35973/70927165-caba1a80-202e-11ea-87e2-1d593806965b.png">

**Comment by avivl** [comment]
Could you open the browser console and copy the generated query?

**Comment by filemon** [comment]
Thanks @avivl for pointing me to the right direction. The generated query contained LIMIT param based on the datasource max data points. I have much more data to be retrieved, so adjusting the max data points value solved my problem. I can see all sessions now. :)
