### ISSUE TITLE
refId for the query wasn't found for the bigquery plugin.

### ISSUE THREAD

**Issue by wkm97** [doitintl/bigquery-grafana#188]
## Bug Report
I tried to query with bigquery plugin and the refId for the query wasn't found.

## Expected Behavior
I was expecting there is refId for the query.

## Actual Behavior
The image below is the results.
![image](https://user-images.githubusercontent.com/31875755/71945282-56276580-3201-11ea-8b08-c6db0e01a0a3.png)

## Steps to Reproduce the Problem

  1. Any query will do.

  - Version: 1.0.4
  - Grafana Version: 6.5.1

**Comment by avivl** [comment]
And why do you need it?

**Comment by wkm97** [comment]
I was trying to create a panel for geospatial visualization, I wish to map different query with respective layers.

**Comment by avivl** [comment]
I'm not sure I understand.
Could you list the steps to reproduce?

**Comment by wkm97** [comment]
I just query like the instruction like the plugin demo shown. The code template I used is from https://github.com/grafana/simple-react-panel

From my understanding, the data queried is obtained through this variable. So, I tried to show the content of this variable in ./src/SimplePanel.tsx
![image](https://user-images.githubusercontent.com/31875755/71967188-e2577e00-323d-11ea-954f-d91fce9453a7.png)

**Comment by avivl** [comment]
Still, I don't understand why do you need the refid.

**Comment by wkm97** [comment]
I tried to make a multi-layer geospatial analysis, each query is mapped to one layer. For example, refId 'A' is the hexbin layer and refId 'B' is for the arc layer. I got 2 query here, I need to map user option to respective query. Sorry for my unclear explanation.
![image](https://user-images.githubusercontent.com/31875755/71969457-a7efe000-3241-11ea-9bec-158528f10617.png)

**Comment by avivl** [comment]
No need for refID
2 series same graph

![image](https://user-images.githubusercontent.com/3265061/71971370-25502c00-3213-11ea-9cf6-2f898b7d5d12.png)

**Comment by wkm97** [comment]
Okay, thanks for telling.
