### ISSUE TITLE
Can't select the location in variable editor

### ISSUE THREAD

**Issue by Eraac** [doitintl/bigquery-grafana#189]
## Bug Report

US location is choose by default when you create a variable based on BigQuery query

## Expected Behavior
Select the location

## Actual Behavior
Default location is choose

## Steps to Reproduce the Problem

1. Have a dataset anywhere but US
2. Implement BigQuery datasource into Grafana
3. Create dashboard
4. Add variable using BigQuery datasource
5. boom query doesn't work (wrong location)

## Specifications
  - Grafana Version: 6.5.2

## Information
If you create panel in the dashboard with the good location, the variable editor seems to use the good location but if you reload the dashboard, variable can't load because US location is use again

**Comment by avivl** [comment]
Did you try to change the location in the data source configuration?

**Comment by Eraac** [comment]
I don't have the option? Either in datasource configuration or variable editor
![image](https://user-images.githubusercontent.com/5497623/72427590-589f3780-378c-11ea-90b8-9b9eeb88a5f6.png)
![image](https://user-images.githubusercontent.com/5497623/72427608-65bc2680-378c-11ea-874c-db992ee64a60.png)

**Comment by avivl** [comment]
![image](https://user-images.githubusercontent.com/3265061/72428984-88a00800-3797-11ea-8a36-16ae55a0e4fd.png)
Which version of the plugin are you using?

**Comment by Eraac** [comment]
I don't find the information, but i install the plugin via environment variable
`export GF_INSTALL_PLUGINS="doitintl-bigquery-datasource"` and the container run since 11 days

**Comment by Eraac** [comment]
I guess, I use the 1.0.4 version https://github.com/doitintl/bigquery-grafana/blob/1.0.4/src/partials/config.html (the latest tag)

**Comment by avivl** [comment]
It's due in 1.0.5 #178
Also available in the master branch

**Comment by Eraac** [comment]
Good, any way to force install master instead of a tag? (with environment variable) or have you a release date for the 1.0.5?

**Comment by avivl** [comment]
https://raw.githubusercontent.com/doitintl/bigquery-grafana/master/INSTALL.md
Just clone the repo to the plugin directory

**Comment by Eraac** [comment]
Thanks, if someone search the information, we can use the latest build with
`export GF_INSTALL_PLUGINS="https://github.com/doitintl/bigquery-grafana/archive/master.zip;doitintl-bigquery-datasource"`
