### ISSUE TITLE
Dataset not found in region US

### ISSUE THREAD

**Issue by AFMiziara** [doitintl/bigquery-grafana#192]
## Bug Report
After upgrading to version 1.0.5, I am having an error related to the location of the cluster. My cluster is on "us-east1" and there isn't this option. Error:
`notFound: Not found: Dataset xxxxxxx:yyyyyyyy was not found in location US
`
I already tried all options of locations and also selection none.

## Expected Behavior
It should be possible to select all available locations in new filter "Processing location"

## Actual Behavior
It is not possible to select "us-east1" location.

## Steps to Reproduce the Problem

  1. Add BigQuery datasource
  1. Try to make a query with a dataset in "us-east1" location

## Specifications

  - Version: 1.0.5
  - Grafana Version: 6.6.0

**Comment by avivl** [comment]
@AFMiziara Thank you for reporting this.
Fixed and merged into master
