### ISSUE TITLE
Only a single value is plotted

### ISSUE THREAD

**Issue by nielsbasjes** [doitintl/bigquery-grafana#193]
## Bug Report
When selecting multiple values in a query only the first one is shown in the line graph.

## Expected Behavior
I would like to see a line for each retrieved value.

## Actual Behavior
Only the first one is plotted.

## Steps to Reproduce the Problem

I have a test project with a table with several numerical columns.
I also have columns created with the HyperLogLogPlus functions Google has provided.
Although these are `BYTES` columns they can be aggregated and a number can be extracted.
In the example below the countDistinctSessionIdSketch column is such a column.

When running this query I ONLY get the first column. In this example it is the output of the HLL_Count.merge. If I change the query to be a basic selection of several numerical values the effect is the same. If I build a simple multi value query using the query builder the effect is the same.

```
    #standardSQL 
    SELECT 
        TIMESTAMP_SECONDS(DIV(UNIX_SECONDS(`windowTimestamp`), 60) * 60) AS groupTimeStamp,
        HLL_Count.Merge(countDistinctSessionIdSketch)        AS distinctSessionId,
        SUM(measurements)                                    AS measurements
    FROM `myproject.mydataset.mytable` 
    WHERE `windowTimestamp` BETWEEN TIMESTAMP_MILLIS($__from) AND TIMESTAMP_MILLIS($__to)
    GROUP BY groupTimeStamp
    ORDER BY groupTimeStamp 
```

## Specifications

  - Version: 1.0.5
  - Platform: Linux
  - Grafana Version: Version 6.6.0 (5c11bbdfb4)

**Comment by avivl** [comment]
@nielsbasjes I'm not a Grafana expert, however, I think that the way to display multiple values in Grafana is to create multiple queries

**Comment by nielsbasjes** [comment]
I have Grafana attached to the data from my electricity meter and I can simply select multiple values from the database (in this case InfluxDB) and see them in a single graph in one query (see screenshot).
Also when I look at the data coming back from BigQuery into Grafana using the query inspector I actually see the values I requested coming back into grafana. So the query I specified is being executed correctly, it somehow only shows the first value as a line instead of all the returned values.

![image](https://user-images.githubusercontent.com/240096/73832940-6e42d280-4809-11ea-95f3-4469269b537e.png)

**Comment by MassyB** [comment]
@nielsbasjes thanks for openning this issue. I have the same one.

**Comment by nielsbasjes** [comment]
Yes, I installed it locally. Works great.
Thanks.

**Comment by MassyB** [comment]
Thanks again ! 
Can you do a release ?

**Comment by avivl** [comment]
Not yet. I need more testing done

**Comment by MassyB** [comment]
When should we expect one ?

**Comment by avivl** [comment]
Probably in a couple of weeks, in the meantime, you can use the version that is in master
