### ISSUE TITLE
Function `$__timeGroupAlias` doesn't support space in argument

### ISSUE THREAD

**Issue by Eraac** [doitintl/bigquery-grafana#196]
## Expected Behavior
Query like this should work
```
SELECT
  $__timeGroupAlias(usage_start_time, 1d), -- space just before '1d'
  sku.description AS metric,
  SUM(cost) AS cost
FROM
  `$from_dataset`,
  UNNEST(project.labels)
WHERE
  $__timeFilter(usage_start_time)
GROUP BY 1, 2
ORDER BY 1, 2 ASC
```

If I remove space, that work perfectly fine, but I lost so much time on it ...

## Actual Behavior
From query inspector
```
SELECT TIMESTAMP_SECONDS(DIV(UNIX_SECONDS(`usage_start_time`), 0) * 0), sku.description AS metric, SUM(cost) AS cost FROM `*****`, UNNEST(project.labels) WHERE `usage_start_time` BETWEEN TIMESTAMP_MILLIS (1577833200000) AND TIMESTAMP_MILLIS (1580511599999) GROUP BY 1, 2 ORDER BY 1, 2 ASC LIMIT 1440
```

Error: `invalidQuery: division by zero: 1580328000 / 0`

## Steps to Reproduce the Problem

  1. Create simple query with `$__timeGroupAlias(column,<space>1d)`

## Specifications

  - Version: Latest (master)
  - Platform: Linux
  - Grafana Version: 6.5.2

**Comment by avivl** [comment]
@Eraac I'm not sure I  understand why are you losing time on removing space. I would think that you will be losing time on typing it

**Comment by Eraac** [comment]
I lost time to find the issue, I was stuck with "invalidQuery" for a while due of the "extra" space

**Comment by Eraac** [comment]
Any reason to not fix this? Is two lines of code and all official datasources with `__timeGroupAlias` function support this space; what about consistency?

**Comment by avivl** [comment]
You are more than welcome to issue a pull request

**Comment by ptomasroos** [comment]
Same here. Had such problems getting it working. And didn’t release it was the space that was causing a issue. Well spotted

**Comment by avivl** [comment]
@Eraac   I'll stop maintaining this data source in a couple of weeks.
@Tamirklein and his team will take over.
I would also like to thank you for your involvement and contribution to this project
