### ISSUE TITLE
Provisioning datasource do not work. Is the yml format wrong？

### ISSUE THREAD

**Issue by chenmeng111** [doitintl/bigquery-grafana#204]
![image](https://user-images.githubusercontent.com/29196565/74724590-6b1efc00-5277-11ea-8e67-cc4769a3590a.png)

**Comment by avivl** [comment]
@chenmeng111 please take a look at the yaml code at master branch

**Comment by chenmeng111** [comment]
![image](https://user-images.githubusercontent.com/29196565/74745878-81d94900-529f-11ea-84b6-4875da864813.png)

**Comment by chenmeng111** [comment]
It is running on K8S. 
grafana:5.4.3

**Comment by chenmeng111** [comment]
I am sorry. 
What do you mean "the yaml code at master branch"?
My yaml code looks like the picture above.

**Comment by avivl** [comment]
![image](https://user-images.githubusercontent.com/3265061/74811072-67cc5480-52f9-11ea-957a-99da8fea0a74.png)

**Comment by chenmeng111** [comment]
I follow the example given above. But it do not work. If I manually configure the datasource in grafana, it will work.

**Comment by avivl** [comment]
What is the error that you are getting?

**Comment by chenmeng111** [comment]
I can see the datasource in grafana, but I can not connect to bigquery

**Comment by chenmeng111** [comment]
![image](https://user-images.githubusercontent.com/29196565/74813094-aa108880-532f-11ea-954d-006381252e38.png)

**Comment by chenmeng111** [comment]
![image](https://user-images.githubusercontent.com/29196565/74815980-32455c80-5335-11ea-8606-154f0191064c.png)

**Comment by chenmeng111** [comment]
Datasource settings of grafana in the container is also same with the demo.

**Comment by chenmeng111** [comment]
Sorry to bother you. The reason for the problem is the existence of \n in my private key.

**Comment by avivl** [comment]
Thanks
