### ISSUE TITLE
Choose region in Template Variable

### ISSUE THREAD

**Issue by sbenzakountradelab** [doitintl/bigquery-grafana#213]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I wan to use a template variable with a bigquery datasource, my dataset is location is in the region EU (european union), i can not choose the region. The region used the default region with is US. then the query is in an error state.

**Describe the solution you'd like**
I would like to have the possibility to choose the region like it is done in the classic query editor in a panel.

**Describe alternatives you've considered**

**Teachability, Documentation, Adoption, Migration Strategy**
Below query, i would lke to have the region.
![image](https://user-images.githubusercontent.com/43436835/76316973-aee7ad00-62db-11ea-81ac-12543dfc9886.png)

**Comment by avivl** [comment]
Which version are you using?
There are options for processing location in the data source setting and in the query itself

**Comment by sbenzakountradelab** [comment]
i use the last version, i am gonna check it.

**Comment by sbenzakountradelab** [comment]
it's ok i choose the correct region in the datasource setting. thank you
