### ISSUE TITLE
Illegal input character "$" in query builder.

### ISSUE THREAD

**Issue by SvetoforColumb** [doitintl/bigquery-grafana#215]
## Bug Report

Something went wrong when I made request in query builder with $__timefilter. Time column is in INT64 type, but I transformed it into timestamp with TIMESTAMP_MICROS()

## Expected Behavior

$__timefilter macro should replaced with sql

## Actual Behavior

`invalidQuery: No matching signature for operator BETWEEN for argument types: INT64, TIMESTAMP, TIMESTAMP. Supported signature: (ANY) BETWEEN (ANY) AND (ANY) at [7:21]`
`invalidQuery: Syntax error: Illegal input character "$" at [7:3]`

## Steps to Reproduce the Problem

  1. open query editor
  2. do same things as on screenshot

![20200316100509-1115x439_edited](https://user-images.githubusercontent.com/12786707/76725847-4d0ec380-6771-11ea-9d42-46cd98305aaf.png)
![20200316100527-976x293_edited](https://user-images.githubusercontent.com/12786707/76725850-4f711d80-6771-11ea-99c8-7f608fdbbd69.png)

## Specifications

  - Version: v.1.0.6
  - Platform: Linux
  - Grafana Version: Grafana v6.3.6 (fdd2117)

**Comment by avivl** [comment]
The macro only works on time types.

**Comment by SvetoforColumb** [comment]
> The macro only works on time types.

So I can't convert column with TIMESTAMP_MICROS() ?

**Comment by avivl** [comment]
No, you can't

**Comment by SvetoforColumb** [comment]
Can you say why, please? I can transform that column to time type in regular query. It happends because I can't use convert functions in macros?

**Comment by avivl** [comment]
I'm checking against columns that are from time types and not converted ones

**Comment by SvetoforColumb** [comment]
Can you add option to use convert functions? Technically query should work if I will convert column type to timestamp (and it works in raw query)

**Comment by avivl** [comment]
Please open a detailed feature request and I'll take a look
