### ISSUE TITLE
Support macros is raw SQL

### ISSUE THREAD

**Issue by avivl** [doitintl/bigquery-grafana#216]
ref #97

**Comment by avivl** [comment]
@ptomasroos it ready in master

**Comment by ptomasroos** [comment]
@avivl it seems "regular" variables got broken because of the update at least in my dashboards

**Comment by ptomasroos** [comment]
Also get the following when trying to use $__timeGroup(timestamp, $__interval)

```
null is not an object (evaluating 'strInterval.match(/\d+/)[0]')
```

**Comment by avivl** [comment]
@ptomasroos "invalidQuery: Syntax error: Illegal input character "$" at [10:6]" is it for query builder or raw sql?
Also, what do you mean by "regular variable"?

**Comment by ptomasroos** [comment]
For a raw sql query.

Regular variable as in dashboard variable. That was working previously. I use them in a WHERE clause in order to filter out partial type of data

Like 
WHERE
device = $device

**Comment by ptomasroos** [comment]
Example:

```
#standardSQL
SELECT
$__timeGroup(timestamp, 1min),
blah as metric
FROM `xx`,
WHERE device = $device
AND $__timeFilter(timestamp)
GROUP BY 1,2
ORDER BY 1,2
```

**Comment by avivl** [comment]
> Also get the following when trying to use $__timeGroup(timestamp, $__interval)
> 
> ```
> null is not an object (evaluating 'strInterval.match(/\d+/)[0]')
> ```
> 
> $__timeGroup(timestamp, 1min) works as expected
$__interval is not a macro it a vaiable that is set by the ui - you will need to specfu the interval and not use a varabile

**Comment by ptomasroos** [comment]
But how would that solve Appropriate dynamic resolution then? 

Sorry I’m not understanding clearly here

**Comment by ptomasroos** [comment]
Sorry I'm probably messing this up with the *auto* option that Grafana provides for the MySQL implementation https://grafana.com/docs/grafana/latest/reference/templating/#interval-variables

**Comment by avivl** [comment]
@ptomasroos The options of the interval are  "1s", "1min", "1h", "1d", "1w", "1m", "1y" and they are set by the user in the query builder.
