### ISSUE TITLE
Allow to convert to time data types for "Time column"

### ISSUE THREAD

**Issue by SvetoforColumb** [doitintl/bigquery-grafana#217]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I have an issue when I try to use column that stores Unix microseconds as time column. Even if I use TIMESTAMP_MICROS() on column.

![image](https://user-images.githubusercontent.com/12786707/76823504-40a06e80-6836-11ea-8efa-ce6431fa334c.png)
![image](https://user-images.githubusercontent.com/12786707/76823510-45fdb900-6836-11ea-8ac1-37813a9c1e01.png)

also the same problem with raw request 

![image](https://user-images.githubusercontent.com/12786707/76824000-9590b480-6837-11ea-8e94-de3ec3c3970a.png)

**Describe the solution you'd like**
Maybe macros should be allowed to have convert functions in it. Or the solution can be adding convert finctions to query builder.  

**Describe alternatives you've considered**
I've tryed to use aliases and inserting convert functions into macros, but it didn't help.

**Comment by avivl** [comment]
@SvetoforColumb what's the data type of the column that stores Unix microseconds?

**Comment by SvetoforColumb** [comment]
@avivl integer (INT64)

**Comment by avivl** [comment]
I did not find any other Grafana data source that supports a calculated column as a time column
