### ISSUE TITLE
Dynamic time resolutions for manual sql queries

### ISSUE THREAD

**Issue by ptomasroos** [doitintl/bigquery-grafana#220]
## Feature Request

**Is your feature request related to a problem? Please describe.**
In order to not need to transmit several million rows from the BigQuery adapter it would be great to allow manual sql queries to get dynamic resolution with some kind of macro.

Say for instance that you have a query with 
$__timeGroup(timestamp, 1min)

That makes sense for up to 24h, but if you select 30days as a range, then it creates a serious amount of rows and a very hard to use graph.

**Describe the solution you'd like**
Allow $__timeGroup to construct the interval dynamically depending the interval selected in the dashboard.

$__timeGroup(timestamp, auto) ?

Ref https://grafana.com/docs/grafana/latest/reference/templating/#interval-variables

**Comment by avivl** [comment]
What is the expected behavior when using auto?

**Comment by ptomasroos** [comment]
This is what I can find in the documentation hence I think its pretty freely up for us to define

```
This $__interval variable is similar to the auto interval variable that is described above. It can be used as a parameter to group by time (for InfluxDB, MySQL, Postgres, MSSQL), Date histogram interval (for Elasticsearch) or as a summarize function parameter (for Graphite).

Grafana automatically calculates an interval that can be used to group by time in queries. When there are more data points than can be shown on a graph then queries can be made more efficient by grouping by a larger interval. It is more efficient to group by 1 day than by 10s when looking at 3 months of data and the graph will look the same and the query will be faster. The $__interval is calculated using the time range and the width of the graph (the number of pixels).

Approximate Calculation: (from - to) / resolution

For example, when the time range is 1 hour and the graph is full screen, then the interval might be calculated to 2m - points are grouped in 2 minute intervals. If the time range is 6 months and the graph is full screen, then the interval might be 1d (1 day) - points are grouped by day.

In the InfluxDB data source, the legacy variable $interval is the same variable. $__interval should be used instead.

The InfluxDB and Elasticsearch data sources have Group by time interval fields that are used to hard code the interval or to set the minimum limit for the $__interval variable (by using the > syntax -> >10m).


```

**Comment by avivl** [comment]
I used maxDataPoints and not screen resolution

**Comment by ptomasroos** [comment]
Well done, nice work!

**Comment by LukeDefeo** [comment]
looking forward to trying to this one out, it will help a lot, thanks

**Comment by ptomasroos** [comment]
Just wanna say that using interval auto, works flawless @avivl 🤟
Always full graphs and no need to LIMIT queries manually
