### ISSUE TITLE
Variable aren't render anymore

### ISSUE THREAD

**Issue by Eraac** [doitintl/bigquery-grafana#221]
## Expected Behavior
Variables should be replace with the content

## Actual Behavior
Variables name are sent to bigquery, instead of their content

## Steps to Reproduce the Problem
1. create query with a variable
2. run the query

## Specifications
  - Version: 4f9ccfb6f0ed5360f3b38f65ab27154b1d99d538 (latest commit)
  - Grafana Version: 6.7.0

**Comment by ptomasroos** [comment]
I mentioned this yesterday as well https://github.com/doitintl/bigquery-grafana/issues/216#issuecomment-601130549

Having the same issue. I reverted to earlier commit
