### ISSUE TITLE
Support dashboard time range macros in variables

### ISSUE THREAD

**Issue by LukeDefeo** [doitintl/bigquery-grafana#224]
## Feature Request

**Is your feature request related to a problem? Please describe.**
We use variables to give the user dropdowns, currently we have to hard code the timerange in the variable to some fixed amount, when the user changes the grafana time range the drop down doesnt correspond the correct data for whats in the charts and is confusing

**Describe the solution you'd like**
Support the macros related to timeFiltering in variable queries e.g $__timeFilter $__timeFrom $__timeTo

**Comment by avivl** [comment]
@LukeDefeo are you aware of any data source that supports this?

**Comment by LukeDefeo** [comment]
The variables have an option to refresh on time range change so i assume some support it.

Anyway i just discovered in the docs that the variables $__from and $__to are always available to i was able to achieve my goal using them.

**Comment by LukeDefeo** [comment]
```SELECT     DISTINCT x   FROM     `table`   WHERE     pt between TIMESTAMP_MILLIS($__from) and  TIMESTAMP_MILLIS($__to)```

Ill just leave this here if anyone else needs an example

**Comment by avivl** [comment]
@LukeDefeo Thank you!

**Comment by avivl** [comment]
@LukeDefeo  I'll stop maintaining this data source in a couple of weeks.
@Tamirklein and his team will take over.
I would also like to thank you for your involvement and contribution to this project
