### ISSUE TITLE
Support date type

### ISSUE THREAD

**Issue by ptomasroos** [doitintl/bigquery-grafana#230]
## Feature Request

I have date in a table which uses the date type not timestamp.

**Is your feature request related to a problem? Please describe.**
The current problem is that it can't render any graphs when using date, because of following error is yielded

```
date.getDate is not a function. (In 'date.getDate()', 'date.getDate' is undefined)
```

**Describe the solution you'd like**
Support for the date type that exist in BigQuery

**Comment by ptomasroos** [comment]
To note I'm using it as the Time column, maybe that's not possible?

**Comment by avivl** [comment]
We support 3 field types as time fields "DATE", "TIMESTAMP", "DATETIME".
What is your query?

**Comment by ptomasroos** [comment]
```
#standardSQL
SELECT
$__timeGroup(`date`), 1d),
requests
FROM `*`
WHERE $__timeFilter(date)
GROUP BY 1,2
ORDER BY 1,2
```

Want it to return

2019-01-01, 123123123

**Comment by ptomasroos** [comment]
I can use the following

```
SELECT
  CAST(date as TIMESTAMP),
  requests
FROM `*`
GROUP BY 1,2
ORDER BY 1,2
```

But time filtering doesn't work with a date example since TIMESTAMP_MILLIS does not work with date objects.

It works to cast this though, if we were to support $__dateFilter(
```
AND `date` BETWEEN CAST(TIMESTAMP_MILLIS(1584419717509) as DATE)
  AND CAST(TIMESTAMP_MILLIS(1584441317509) as DATE)
```

**Comment by avivl** [comment]
@ptomasroos I'll stop maintaining this data source in a couple of weeks.
@Tamirk and his team will take over. So in this transition period please work with him on this. I'll be here to advise.
I would also like to thank you for your involvement and contribution to this project

**Comment by Tamirklein** [comment]
Hi, @ptomasroos looking forward to our mutual work.

Can you please clarify why using [1] in your SQL can't help solve your issue and why do you think we need to add support in the code for your request 

[1] https://cloud.google.com/bigquery/docs/reference/standard-sql/datetime_functions
