### ISSUE TITLE
Invalid date on graph chart 

### ISSUE THREAD

**Issue by UrosKovacevic** [doitintl/bigquery-grafana#231]
## Bug Report
I have a dataset where the only time column is a date field in big query.  I would like a time series chart from this. My query designer looks like this:
![invaliddate](https://user-images.githubusercontent.com/63073578/78296373-ec7fd480-752d-11ea-8acf-939bbcd0a79a.png)

I have also tried many variants along equivalent SQL scripts getting the same invalid date result.

## Expected Behavior
Timeseries chart displaying results according to the time column.

## Actual Behavior
Graph doesnt draw anything because of invalid date. 

## Steps to Reproduce the Problem

  1. see my screenshot above, try to set a date column as the time column in grafana

## Specifications

  - Version: 1.0.6
  - Platform:  Windows 
  - Grafana Version:  v6.6.2

**Comment by liorsuperquery** [comment]
Hi @UrosKovacevic,
I tried to reproduce this on my local environment.

Can you please share the schema of this query and the query itself?
You can fetch the query from the browser console

**Comment by LiorRacer** [comment]
Hi @UrosKovacevic,
I tried to reproduce this on my local environment.

Can you please share the schema of this query and the query itself?
You can fetch the query from the browser console

**Comment by LiorRacer** [comment]
Hi @UrosKovacevic,
Thanks for sharing the schema, it seems the 'time' field is nullable can please verify there are no  nulls values.
And can you share the SQL? It is being print to the console

**Comment by UrosKovacevic** [comment]
Hey @LiorRacer 
Thanks for quick response,

Here is the SQL code from the console:

#standardSQL
SELECT
 `date` AS time,
  CAST (`source`AS String ) AS metric,
  avg(`transaction_revenue`) AS transaction_revenue
FROM `kuhl-analytics-256018.g_analytics_supermetrics.GA_TRAFFIC_*`
WHERE
  `date` BETWEEN '2020-03-23' AND '2020-04-06'
GROUP BY 1,2 
ORDER BY 1,2 LIMIT 950

and the screenshot:

![console](https://user-images.githubusercontent.com/63073578/78704692-879cf380-790c-11ea-9e51-9fb344efe72f.png)

Concerning the null values in the database, there appears to be none, screenshot: 

![query](https://user-images.githubusercontent.com/63073578/78704733-9aafc380-790c-11ea-8811-37275696f023.png)

**Comment by Tamirklein** [comment]
Hi @UrosKovacevic,

As we are unable to reproduce this can you please limit your time range in your SQL to try and pinpoint the day you have an invalid value and share with us your findings (Maybe value is not nullable rather empty or another un-expected value)

**Comment by tgtwm1github** [comment]
I am getting a Invalid Date error in v2.0.1.
The table has bunch of columns in addition to one column that is a DATE datatype.
select date_column, other_col1 from table, shows "Invalid Date" in grafana table view.
However, select cast(date_column as string), other_col1 from table, shows the date.

Any help appreciated.
