### ISSUE TITLE
Chart missing data influencing other charts

### ISSUE THREAD

**Issue by Thijxx** [doitintl/bigquery-grafana#241]
## Expected Behavior
Show multiple charts.

## Actual Behavior
If I have a chart with no data for a couple of days, other charts will also drop data for those days.

## Steps to Reproduce the Problem

  1. Create a chart for a period with some missing data
  1. Create another chart for some other SQL filtered selection
  1. Notice the disappeared data

![Screenshot_20200504_164327](https://user-images.githubusercontent.com/41118940/80979082-30187780-8e27-11ea-908f-3bb266df7721.png)

The right chart has all data, the left chart misses a couple of days.

## Specifications

- Version: 1.0.7
- Platform: Centos 8
- Grafana Version: 6.2.2-2

**Comment by Thijxx** [comment]
SQL within grafana
```
#standardSQL
SELECT
 $__timeGroupAlias(timestamp,10m,1h),
  avg(`sensorvalue`) /100 AS sensorvalue
FROM `hypercloud-252112.hyperwarehouse.staging_tickle2019`
WHERE
  $__timeFilter(timestamp) AND
  nodeid = 749 AND
  sensorid = 1
GROUP BY 1 
ORDER BY 1 DESC
```

SQL as logged by BigQuery
```
#standardSQL
SELECT
 TIMESTAMP(  (PARSE_DATE( "%Y-%m-%d",CONCAT( CAST((EXTRACT(YEAR FROM `timestamp`)) AS STRING),'-',CAST((EXTRACT(MONTH FROM `timestamp`)) AS STRING),'-','01')))) AS time,
  avg(`sensorvalue`) /100 AS sensorvalue
FROM `hypercloud-252112.hyperwarehouse.staging_tickle2019`
WHERE
  `timestamp` BETWEEN TIMESTAMP_MILLIS (1587999590573) AND TIMESTAMP_MILLIS (1588604390573) AND
  nodeid = 749 AND
  sensorid = 1
GROUP BY 1 
ORDER BY 1 DESC LIMIT 1280
```

**Comment by Thijxx** [comment]
Fix: `$__timeGroupAlias(timestamp,1h),`

Maybe, the GUI query builder resulted in an odd parameter for `$__timeGroupAlias`?

**Comment by LiorRacer** [comment]
Hi @Thijxx, 
Can you reproduce it on public dataset?
I tried it with my own data and it didn't reproduce:
<img width="814" alt="image" src="https://user-images.githubusercontent.com/13584904/83353932-8f9e7000-a35e-11ea-896f-3bd4b92abf54.png">

**Comment by Tamirk** [comment]
@Thijxx closing this for now but if you have any information on this feel free to let us know
