### ISSUE TITLE
__timeGroup does not use my time variable

### ISSUE THREAD

**Issue by marcbichon** [doitintl/bigquery-grafana#242]
## Expected Behavior
I try to build a timeline with the following query:
```
SELECT
  $__timeGroup(input.timestamp, 1h),
  COUNTIF(metric)
FROM table
GROUP BY time
```

## Actual Behavior
- The panel displays "no data" instead of the expected timeline
![image](https://user-images.githubusercontent.com/45167429/81925499-ed9e2a00-95e0-11ea-81a3-c4a085b7d626.png)
- There is no error (no red icon in the top left corner)
- In my browser console the query which run is the following:
```
SELECT
  TIMESTAMP_SECONDS(DIV(UNIX_SECONDS(`-- time --`), 3600) * 3600) AS time,
  COUNTIF(metric)
FROM table
GROUP BY time LIMIT 1856
```
- The surprise is this `--time--` parameter instead of my input.timestamp parameter

## Specifications

  - Version: 1.0.7
  - Grafana Version: 6.7.1

**Comment by LiorRacer** [comment]
Hi @marcbichon, 
I believe that you used the query builder, right?
If so can you verify that you select `Time Column`, for example:
<img width="556" alt="image" src="https://user-images.githubusercontent.com/13584904/83430581-913f6500-a43e-11ea-976c-ee7417d77a8c.png">

**Comment by Tamirk** [comment]
@marcbichon if @LiorRacer answer is not solving your issue please open with more details
