### ISSUE TITLE
Issues graphing data

### ISSUE THREAD

**Issue by vpetersson** [doitintl/bigquery-grafana#243]
## Bug Report

Not sure if this is a bug or if it's user error, but I'm having issues getting my graphs to work properly. It's unclear to me if it's an issue with my data structure or something else.

I have a Kubernetes cronjob that pushes data every hour to a BigQuery table that looks as follows:

Field name | Type | Mode | Policy tags
-- | -- | -- | --
timestamp | DATETIME | REQUIRED |   | Data point timestamp
active_users_7_days_free | INTEGER | NULLABLE |   | Active free users in the last 7 days
active_users_7_days_paid | INTEGER | NULLABLE |   | Active paid users in the last 7 days
active_users_30_days_free | INTEGER | NULLABLE |   | Active free users in the last 30 days
active_users_30_days_paid | INTEGER | NULLABLE |   | Active paid users in the last 30 days

I'm able to query the data just fine from BigQuery's interface with something simple like: 
```
SELECT timestamp,active_users_30_days_paid FROM `my-project.bi_metrics.webapp` LIMIT 1
```

This results in something like:
```
1 | 2020-05-12T00:20:05.915185 | 1024 |  
```

I'm also able to select (at least partially) the data in Grafana, which leads me to believe the connection works fine:

<img width="1341" alt="Screen Shot 2020-05-22 at 5 41 25 PM" src="https://user-images.githubusercontent.com/357664/82690213-b1f40780-9c53-11ea-82f4-758b1c6ceb5d.png">

## Expected Behavior

The expected behavior would be that if I pick the above query (in the screenshot) would yield a graph.

## Actual Behavior

The graph simply shows 'no data' as of right now.

## Steps to Reproduce the Problem

  1. Create a table as per the structure above
  1. Insert some data
  1. Get No Data instead of a graph

## Specifications

  - Version: 1.0.7
  - Platform: Kubernetes / GKE
  - Grafana Version: v6.7.3

**Comment by vpetersson** [comment]
Looking closer, I see now that I get `e.getDate is not a function` if I manually specify a query, thus it seems related to #240.

**Comment by LiorRacer** [comment]
Please see this issue:https://github.com/doitintl/bigquery-grafana/issues/240
