### ISSUE TITLE
Add support for range annotation

### ISSUE THREAD

**Issue by evanyin88** [doitintl/bigquery-grafana#246]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I am creating an annotation using BQ as data source. while my query returns the list of columns/fields required for range annotation, the actual graphed annotation is not range annotation, as timeend field is not passed from the query result to the grafana annotation events. 

**Describe the solution you'd like**
Adding range support, like other data sources (e.g. MySQL, here is the PR change: https://github.com/grafana/grafana/pull/20752)

**Describe alternatives you've considered**
Currently I'm just using normal annotations with individual events. 

**Teachability, Documentation, Adoption, Migration Strategy**
```
SELECT
  extract(epoch from time_column) AS time,
  extract(epoch from time_end_column) AS timeEnd,
  text_column as text,
  tags_column as tags
FROM
  metric_table
WHERE
  $__timeFilter(time_column)
```

**Comment by Tamirk** [comment]
Thank you @evanyin88 for this idea, I like it. We are currently working on the alert feature and will have to review this a bit later on. If anyone has an interest in contributing and make the effort to write the code for this we'll be happy to support this and help

**Comment by ofir5300** [comment]
We are retiring the [DoiT International BigQuery DataSource plugin](https://grafana.com/grafana/plugins/doitintl-bigquery-datasource/) for Grafana. We recommend that you migrate to the official [Google BigQuery data source](https://grafana.com/grafana/plugins/grafana-bigquery-datasource/) maintained by Grafana. In August 2022, we will cease all development and archive the GitHub project.

We are sorry for any inconvenience.
