### ISSUE TITLE
Release 1.0.8 missing not visible from the plugins page

### ISSUE THREAD

**Issue by davidepedranz** [doitintl/bigquery-grafana#248]
## Bug Report
Amazing work with this data source! 💪  I see version [1.0.8](https://github.com/doitintl/bigquery-grafana/releases/tag/1.0.8) includes some improvements and bug fixes and I would love to use it on my instance of Grafana. Unfortunately, I cannot see it in the [list of plugins available](https://grafana.com/grafana/plugins/doitintl-bigquery-datasource) from Grafana: the latest version available to install is `1.0.7`. Unfortunately, this prevents to install the latest version in Grafana with a simple
```bash
grafana-cli plugins install doitintl-bigquery-datasource
```

## Expected Behavior
Version `1.0.8` should be available for download and use in Grafana.

## Actual Behavior
Version `1.0.7` is the latest version available for download.

## Steps to Reproduce the Problem
Visit [this page](https://grafana.com/grafana/plugins/doitintl-bigquery-datasource) and verify that the latest version is `1.0.7`.

Alternatively, run Grafana locally, install the latest version of the plugin, and verify it is version `1.0.7`:
```bash
docker run -d -p 3000:3000 --name=grafana -e "GF_INSTALL_PLUGINS=doitintl-bigquery-datasource" grafana/grafana
```

## Specifications
  - Platform: Docker (`grafana/grafana:7.0.3`)
  - Grafana Version: `7.0.3`

**Comment by Tamirk** [comment]
@davidepedranz thank you for the kind words, Yes we saw the plugin wasn't published as well and already ping Grafana team on this. I hope they will publish the version as well

**Comment by davidepedranz** [comment]
Thanks for the update @Tamirk 🙏  Looking forward to seeing it live!
