### ISSUE TITLE
Only beginning of data for BigQuery plugin

### ISSUE THREAD

**Issue by sarahb511** [doitintl/bigquery-grafana#249]
My team and I are trying to utilize Grafana pulling data from BigQuery (sourced from Firebase). When we do, only the first small portion of the data is returned, regardless of the time duration declared or the amount of time we group by.
 
When I recreate the query within Big Query, all information for the given time range is returned.
 
Is there something we’re doing wrong within Grafana?  If not, is there a way to resolve this?

Please look at screenshot for further context. 

![B73E43EB-23BB-4002-BC72-62261EA73250_1_201_a](https://user-images.githubusercontent.com/51332153/84828468-ba89f480-afeb-11ea-931c-4170fce43b36.jpeg)
![0031C98E-1EFA-4CDF-B0C0-F3895A526601](https://user-images.githubusercontent.com/51332153/84828473-bbbb2180-afeb-11ea-96e7-7c6c5a928e0f.jpeg)

**Comment by Tamirk** [comment]
Hi @sarahb511 can you please check on your browser console, by using devtools, the SQL printed there and let us know if it's the same as the one you are running directly in BigQuery UI

**Comment by sarahb511** [comment]
Hi @Tamirk ! Do you know if there is a way to raise that `LIMIT` of a query? I'm working with time series data, so that limit will not be very functional for my use case.

**Comment by Tamirk** [comment]
You have 2 option:
1. Use the Query Editor and not builder to set your own LIMIT
2. Use the Query option to over-ride the default

![image](https://user-images.githubusercontent.com/895577/84924275-f77be700-b0d0-11ea-8466-affebac083ff.png)

![image](https://user-images.githubusercontent.com/895577/84924315-05316c80-b0d1-11ea-8d1b-87c82b830c96.png)

**Comment by Tamirk** [comment]
@sarahb511 I hope my answer helped you. For now closing the issue if you need anything else let me know will be happy to further assist where possible.
