### ISSUE TITLE
Annotations are not working if the query returns zero rows

### ISSUE THREAD

**Issue by davidepedranz** [doitintl/bigquery-grafana#254]
## Expected Behavior

When used for annotations, a query returning zero results (but with the correct schema) should not cause errors to Grafana. Instead, Grafana should simply not show any annotation for that query.

## Actual Behavior

Grafana crashes when the query returns zero rows. In addition, other annotations stop working (even if the respective queries do return non-empty results).

The UI shows the following error message:

```
Annotation Query Failed
Cannot read property `length` of undefined
```

The console reports the following error:

```
AnnotationSrv.query error TypeError: Cannot read property 'length' of undefined
    at ResponseParser.transformAnnotationResponse (response_parser.ts:295)
    at eval (datasource.ts:519)
    at async Promise.all (/d/nu0CHYGMk/index 3)
```

## Steps to Reproduce the Problem

Create a new `Annotation` using BigQuery as a data source with the following query (any query returning zero rows will do the job):

```
SELECT
  0 AS time,
  "x" AS text,
  "a,b" AS tags
FROM UNNEST([])
```

## Additional information

Checking the API response for the query without results, I see that the fields `totalRows` and `rows` are missing. The frontend raises an error since it tries to iterate on the rows field [here](https://github.com/doitintl/bigquery-grafana/blob/7aa958d50f810249e095c3ac606250fa3384e952/src/response_parser.ts#L295).

Response for a query with zero rows:
```
{
  "kind": "bigquery#queryResponse",
  "schema": {
    "fields": [
      {
        "name": "time",
        "type": "INTEGER",
        "mode": "NULLABLE"
      },
      {
        "name": "text",
        "type": "STRING",
        "mode": "NULLABLE"
      },
      {
        "name": "tags",
        "type": "STRING",
        "mode": "NULLABLE"
      }
    ]
  },
  "jobReference": {
    "projectId": "some-project-id",
    "jobId": "some-job-id",
    "location": "US"
  },
  "totalRows": "0",
  "totalBytesProcessed": "5643",
  "jobComplete": true,
  "cacheHit": false
}
```

Response for a query with some rows:
```
{
  "kind": "bigquery#queryResponse",
  "schema": {
    "fields": [
      {
        "name": "time",
        "type": "INTEGER",
        "mode": "NULLABLE"
      },
      {
        "name": "text",
        "type": "STRING",
        "mode": "NULLABLE"
      },
      {
        "name": "tags",
        "type": "STRING",
        "mode": "NULLABLE"
      }
    ]
  },
  "jobReference": {
    "projectId": "some-project-id",
    "jobId": "some-job-id",
    "location": "US"
  },
  "totalRows": "2",
  "rows": [
    {
      "f": [
        {
          "v": "1594014313"
        },
        {
          "v": "End job"
        },
        {
          "v": "end"
        }
      ]
    },
    {
      "f": [
        {
          "v": "1594019749"
        },
        {
          "v": "End job"
        },
        {
          "v": "end"
        }
      ]
    }
  ],
  "totalBytesProcessed": "5643",
  "jobComplete": true,
  "cacheHit": false
}
```

## Specifications

  - Version: 1.0.8
  - Platform: Docker - Ubuntu 20.04 LTS, x86_64, Linux a04678e86806 4.19.112+ (`grafana/grafana:7.0.5-ubuntu`)
  - Grafana Version: 7.0.5

**Comment by Tamirk** [comment]
@davidepedranz can you please download version 2.0.0 and confirm the bug also exists there, Once confirmed I'll assign this to one of our developers

**Comment by davidepedranz** [comment]
Thanks for the quick answer. Tested with version `2.0.0`, and the error is still there. Both the error in the UI and the console are identical. You can reproduce the issue as described above. @Tamirk, let me know if I can provide any additional information or help somehow 🙏 .

**Comment by Tamirk** [comment]
Got you @davidepedranz, We plan next week to do some work on the plugin I'll see if we can also review your case,,,, Stay tune.
