### ISSUE TITLE
How can I add Seoul (asia-northeast3) Location?

### ISSUE THREAD

**Issue by ldh0227** [doitintl/bigquery-grafana#256]
Hello.

I want use this plugin for our data.
But 1.0.8 version doesn't have Seoul (asia-northeast3) localtion.

May I add custom location? or Any plan?

Thanks.

**Comment by Tamirk** [comment]
We'll need to add this region and deploy a new version. I'm assigning this issues for our next drop plan in the coming couple of weeks
