### ISSUE TITLE
invalidQuery: Syntax error: Unexpected identifier "String" at

### ISSUE THREAD

**Issue by clemishow** [doitintl/bigquery-grafana#257]
## Bug Report
<img width="1057" alt="Screenshot 2020-07-16 at 15 45 17" src="https://user-images.githubusercontent.com/9325482/87679151-204cd600-c77c-11ea-8d1d-69deaa6e3dae.png">

I'm trying to make this query work, but I'm getting an error message.
`invalidQuery: Syntax error: Unexpected identifier "String" at [4:36]`

```sql
#standardSQL
SELECT
 TIMESTAMP(PARSE_DATE('%Y%m%d', _TABLE_SUFFIX)) AS time,
  CAST (param.value.string_valueAS String ) AS metric,
  count(*) AS nb
FROM `neocity.analytics.events_*`, UNNEST(event_params) as param
WHERE
  event_name = 'screen_view' AND
  param.value.string_value != 'null'
GROUP BY 1,2 
ORDER BY 1,2 LIMIT 686
```
## Expected Behavior
`CAST (param.value.string_valueAS String ) AS metric,`

Put a space between value and AS

## Actual Behavior
Error message

## Specifications

  - Version: efbcbb838b
  - Platform: AWS Docker
  - Grafana Version: 7.0.5

**Comment by Tamirk** [comment]
Hi @clemishow can you let us know which version of our plugin you are using

**Comment by clemishow** [comment]
1.0.6

**Comment by Tamirk** [comment]
Ok, We are waiting for 2.0.0 to be officially published, Once publish please test your issue with the latest version and if you still face an issue we'll fix this

**Comment by spark2ignite** [comment]
@Tamir Klein <tamir@doit-intl.com> I don't see anything on 2.0 that fixes
this issue.

Vadim Solovey | GM // DoiT International

**Comment by Tamirk** [comment]
@clemishow We see an error in your SQL (missing space) can you replace this line

`CAST (param.value.string_valueAS String ) AS metric,`

With this
`  CAST (param.value.string_value AS String ) AS metric,`

Note: I added a space between `param.value.string_value` and the `AS` keyword

**Comment by clemishow** [comment]
The error comes from Query Builder which doesn't put the space
