### ISSUE TITLE
How to create a new column based on an existing bigquery column

### ISSUE THREAD

**Issue by sarahb511** [doitintl/bigquery-grafana#259]
In Grafana, is there a way to create a new column based on an existing BigQuery column?

The example my team is working with is to group response codes into tiers (200, 201, 204 would be 2XX).

**Comment by Tamirk** [comment]
@sarahb511 If I correctly understand your question you can use BigQuery SQL to create an additional column which is the group columns using [CASE](https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#case) or [IF](https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#if) functions

**Comment by Tamirk** [comment]
@sarahb511 closing the issue for now if you have additional information or need some more assistance let us know
