### ISSUE TITLE
Is it possible to use Grafana's Macros variables?

### ISSUE THREAD

**Issue by clemishow** [doitintl/bigquery-grafana#262]
https://grafana.com/docs/grafana/latest/features/datasources/mysql/#macros

Can I use this variables inside my SQL query?

Like `_TABLE SUFFIX BETWEEN $__timeFrom() AND $__timeTo()`

Because I get a bug every time I try to use one `invalidQuery: Syntax error: Illegal input character "$" at`

**Comment by strideynet** [comment]
I can't get this working either?

**Comment by LukeDefeo** [comment]
yes it possible. you can use $__from and $__to

**Comment by clemishow** [comment]
Not working for me :
"invalidQuery: No matching signature for operator BETWEEN for argument types: STRING, INT64, INT64. Supported signature: (ANY) BETWEEN (ANY) AND (ANY) at [5:21]"

`WHERE _TABLE_SUFFIX BETWEEN $__from AND $__to`

**Comment by clemishow** [comment]
Someone has a solution?
