### ISSUE TITLE
Bug when replicating previously working panel

### ISSUE THREAD

**Issue by sarahb511** [doitintl/bigquery-grafana#263]
## Expected Behavior
Creating a graph vizualization panel utilizing an exact query that has worked before.

## Actual Behavior
Throws the following error: 
`invalidQuery: Syntax error: Expected end of input but got "." at [5:66]`

## Steps to Reproduce the Problem

  1. Occurs when creating a graph vizualization panel

![79A29CF7-937A-46B5-A28F-59B8533F2BF5_4_5005_c](https://user-images.githubusercontent.com/51332153/88727743-ce01a280-d0f5-11ea-98f4-b28109cbe50f.jpeg)

**Comment by Tamirk** [comment]
@sarahb511 can you please provide us with the detail of the query and if you used a custom query or the query builder.
In addition, Can you please provide the plugin version you are using to help troubleshoot this.

**Comment by sarahb511** [comment]
Hi @Tamirk 
Here is a screenshot of the query I was trying to run when I encountered the error
![479A1895-FD29-4E39-942C-02314730EC5C](https://user-images.githubusercontent.com/51332153/88814765-27161880-d180-11ea-8af0-19bc0d9bc5de.jpeg)

We are using the plugin version 1.0.8.

**Comment by sarahb511** [comment]
I figured out this issue. Sorry for the confusion.
