### ISSUE TITLE
How to delete console.log?

### ISSUE THREAD

**Issue by Ruifeng-Wu** [doitintl/bigquery-grafana#264]
## Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I have an issue when [...]

When opening the Console, there are many logs for datasource.ts.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

How do I delete these logs?

**Describe alternatives you've considered**

Or what configuration grafana has to do that.

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version of the docs.
Maybe a screenshot or design?

**Comment by Tamirk** [comment]
@Ruifeng-Wu can you please let us know on which environment you run Grafana so we'll understand to which console you refer to

**Comment by Tamirk** [comment]
Closing as no response to follow-up question
