### ISSUE TITLE
add support for count distinct aggregation

### ISSUE THREAD

**Issue by nicks** [doitintl/bigquery-grafana#268]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I want to be able to count the number of unique users per day

**Describe the solution you'd like**
Add a COUNT(DISTINCT column) option to the query builder

I think it needs a custom option in the query builder, because the syntax is slightly different than other aggregation functions.

**Describe alternatives you've considered**
I also tried to do this with the SQL editor, but couldn't figure out how. I actually couldn't find a working example of the raw query editor, or how to use it effectively.

I also tried to use the hyperloglog functions for this, but they also gave me cryptic errors like: "Invalid NUMERIC value: USERID". I think there might be bugs in the implementation of the querybuilder, such that it assumes the inputs are numbers

**Teachability, Documentation, Adoption, Migration Strategy**
I expect it would be alongside the 'count' aggregation function

**Comment by ofir5300** [comment]
We are retiring the [DoiT International BigQuery DataSource plugin](https://grafana.com/grafana/plugins/doitintl-bigquery-datasource/) for Grafana. We recommend that you migrate to the official [Google BigQuery data source](https://grafana.com/grafana/plugins/grafana-bigquery-datasource/) maintained by Grafana. In August 2022, we will cease all development and archive the GitHub project.

We are sorry for any inconvenience.

**Comment by nicks** [comment]
Thanks for the update @ofir5300 . Ya that seems like a good plan.
