### ISSUE TITLE
Not all series are displayed

### ISSUE THREAD

**Issue by spark2ignite** [doitintl/bigquery-grafana#27]
## Bug Report
vendor_id has three distinct values (CMT, VTS and DDS). The chart displays only two of them

<img width="1681" alt="Screen Shot 2019-03-30 at 21 23 30" src="https://user-images.githubusercontent.com/5726975/55280117-338f2480-5332-11e9-9ec8-507d859ca5a1.png">

## Expected Behavior
All series should be displayed

## Actual Behavior
One series doesn't get displayed

## Steps to Reproduce the Problem

Query
```
#standardSQL
SELECT
 $__timeGroupAlias(pickup_datetime,1d),
  vendor_id AS metric,
  avg(passenger_count) AS passenger_count
FROM `nyc-tlc.yellow.trips`
WHERE
  $__timeFilter(pickup_datetime)
GROUP BY 1,2
ORDER BY 1,2
```

**Comment by avivl** [comment]
@varelasavela please give the service account that I'm using(and for me) permissions to the project

**Comment by spark2ignite** [comment]
@avivl that is a public dataset. You can copy/paste the query to your Grafana setup.

**Comment by avivl** [comment]
What's the name of the dataset?

**Comment by spark2ignite** [comment]
@avivl `yellow`
