### ISSUE TITLE
Issue when using $__interval : receiving "Data outside time range" error 

### ISSUE THREAD

**Issue by IvanIlnytskyi** [doitintl/bigquery-grafana#270]
## Bug Report
I am using $__interval parameter in 'group by' section to change the level of aggregation from raw data to appropriate interval.
I have tried different time values of $__interval ( Interval in Query Options) and the issue exists only  __minutes__. Seems like '2m' is treated like 2 months but not 2 minutes 

## Expected Behavior
time series aggregated by time interval

## Actual Behavior
receiving "Data outside time range" error

## Steps to Reproduce the Problem
1)Select time range so Interval in Query Options is equal to couple of __minutes__.
2)Use $__interval in group by section - time ($__interval, none)

Query inspector:
 [query_inspector_with_interval_issue.pdf](https://github.com/doitintl/bigquery-grafana/files/5096326/query_inspector_with_interval_issue.pdf)

Attaching screenshots below 
<img width="1176" alt="Screen Shot 2020-08-19 at 3 09 42 PM" src="https://user-images.githubusercontent.com/14282832/90633788-5d026600-e22f-11ea-9835-27964dc852fc.png">
<img width="637" alt="Screen Shot 2020-08-19 at 3 10 00 PM" src="https://user-images.githubusercontent.com/14282832/90633794-5ffd5680-e22f-11ea-950b-e72120ba0b84.png">

## Specifications

  - Version: 1.0.7
  - Platform: macOS
  - Grafana Version: Grafana v7.0.3 (00ee734baf)

Thanks in advance.

**Comment by anasm-17** [comment]
Hi, I just wanted to follow up on this issue.

**Comment by LiorRacer** [comment]
Hi all, 
Can you please try with our latest version and let us know if you still experience this issue

**Comment by anasm-17** [comment]
Hi, with v 1.0.8 or with version 2.0.X?
