### ISSUE TITLE
Record limit set by grafna to 534 ??

### ISSUE THREAD

**Issue by OrangePieiep** [doitintl/bigquery-grafana#271]
## Bug Report
Find the grafna add a limit into my sql query, the limit number is 534 in my version. Is there some way to get rid of this ?

``.....(my sql query)....LIMIT 534``
                                                                                     ^^^^^^^^^^^^^
## Expected Behavior
shouldn't have this limitation

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version: Grafana v6.3.5 (67bad72)
  - Platform:
  - Grafana Version:

**Comment by Tamirk** [comment]
@OrangePieiep please refer to the [troubleshooting](https://github.com/doitintl/bigquery-grafana#troubleshooting) section in our readme file to check how to resolve this
