### ISSUE TITLE
$__timeGroupAlias(timestamp,1h) AS XYZ, give error

### ISSUE THREAD

**Issue by OrangePieiep** [doitintl/bigquery-grafana#272]
## Bug Report
select 
$__timeGroupAlias(timestamp,1h) AS XYZ, give error

```invalidQuery: Syntax error: Expected end of input but got keyword AS at [1:43]```

## Expected Behavior
shouldn't give error. Works fine for some old version

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version: Grafana v6.3.5 (67bad72)
  - Platform:
  - Grafana Version:

**Comment by Tamirk** [comment]
Hi @OrangePieiep this error looks similar to #257 and other issues recently closed, Can you please use the latest version and let us know if this solve your problem.

**Comment by OrangePieiep** [comment]
what is the stable release version number ? latest might be risky ?

**Comment by LiorRacer** [comment]
Hi @OrangePieiep 
Currently Grafana didn't provide a way to sign plugins, you can install the plugin by following the instructions [here](https://github.com/doitintl/bigquery-grafana/issues/255#issuecomment-661720241)
