### ISSUE TITLE
Release to Grafana

### ISSUE THREAD

**Issue by smehboub-dkt** [doitintl/bigquery-grafana#273]
Hello,

Firstly, thank you very much for your work.

When will you officially release version 2.0.1 to Grafana ?

Thanks in advance.
Rgs,

Sophian Mehboub

**Comment by LiorRacer** [comment]
Hi Sophian,
Currently Grafana didn't provide a way to sign plugins, you can install the plugin by following the instructions [here](https://github.com/doitintl/bigquery-grafana/issues/255#issuecomment-661720241)
