### ISSUE TITLE
Plugin (2.0.0) not showing up in Grafana 7 Plugin list

### ISSUE THREAD

**Issue by bond445566** [doitintl/bigquery-grafana#274]
I have installed Grafana 7.1.4 and the BigQuery Plugin in Version 2.0.0 via:

1) `grafana-cli --pluginUrl https://github.com/doitintl/bigquery-grafana/archive/2.0.0.zip plugins install doitintl-bigquery-datasource`

2) `service grafana-server restart`

The Plugin is not showing up in the Plugin list in Grafana (/plugins)

Did i miss something?

  - Version: 2.0.0
  - Platform: Ubuntu 18.04.5 LT
  - Grafana Version: 7.1.4 (82a235b54c)

**Comment by LiorRacer** [comment]
Hi @bond445566 
You will have to add it to your grafana.ini since Grafana have issue signing a back-end plugin
Follow the instruction here
https://github.com/doitintl/bigquery-grafana/issues/255#issuecomment-661720241

**Comment by bond445566** [comment]
Hi @LiorRacer,

thank you so much! :)

It's working now 👍
