### ISSUE TITLE
Support for external temporary tables

### ISSUE THREAD

**Issue by linar-jether** [doitintl/bigquery-grafana#279]
## Feature Request

Support to pass external table configurations to the query's job configuration: 
https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#jobconfigurationquery
https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#ExternalDataConfiguration

This will allow querying from external datasets without first explicitly defining a table, e.g. a csv/parquet/google sheets file(s)

A simple but very useful use case is using grafana for ad-hoc exploration of large GCS datasets (hive?)

**Comment by Tamirk** [comment]
@linar-jether not sure what you mean in your request. 
Once an external, aka federated table, is defined in your BigQuery, you can run an SQL from Grafana on that table assuming the service account your are using has the right ACL to query the table.

I don't see any change we need to do in our current implementation to support this

**Comment by linar-jether** [comment]
@Tamirk Yes, only *permanent* external tables are supported, i was referring to querying *temporary* external tables, which do not require any table definition to be created before querying: 
https://cloud.google.com/bigquery/external-data-cloud-storage#creating_and_querying_a_temporary_table

**Comment by Tamirk** [comment]
@linar-jether thanks for the detail. Let's see if we have more users looking for such a feature and based on this we'll decide how to advance this CR
