### ISSUE TITLE
Alerting does not include correct values

### ISSUE THREAD

**Issue by johanbaath** [doitintl/bigquery-grafana#281]
Seems like alerting just sets the values to [10, 20]. Should use the correct values. Any pointers on how to do this?

https://github.com/doitintl/bigquery-grafana/blob/cc96ba1a26be63dbc4c092bd2cefad95eedf40b9/pkg/plugin.go#L94

**Comment by BenMizrahiPlarium** [comment]
also hre

**Comment by omer-niv** [comment]
+1
