### ISSUE TITLE
Parse date returns invalid date

### ISSUE THREAD

**Issue by krtk6160** [doitintl/bigquery-grafana#284]
## Expected Behavior

`SELECT PARSE_DATE("%F", "2000-12-30")` should return `2000-12-30`

## Actual Behavior

It returns `Invalid Date`.

## Steps to Reproduce the Problem

  1. Write this query in the query editing box - `SELECT PARSE_DATE("%F", "2000-12-30")` and run the query

## Specifications

  - Version: 2.0.0
  - Platform: GKE
  - Grafana Version: 7.1.1

**Comment by LiorRacer** [comment]
Didn't reproduce 
{
  "request": {
    "data": {
      "priority": "INTERACTIVE",
      "location": "US",
      "query": "SELECT PARSE_DATE(\"%F\", \"2000-12-30\") LIMIT 924",
      "useLegacySql": false,
      "useQueryCache": true
    },
    "method": "POST",
    "url": "api/datasources/proxy/3/bigquery/v2/projects/mydata-1470162410749/queries"
  },
  "response": {
    "kind": "bigquery#queryResponse",
    "schema": {
      "fields": [
        {
          "name": "f0_",
          "type": "DATE",
          "mode": "NULLABLE"
        }
      ]
    },
    "jobReference": {
      "projectId": "xxx",
      "jobId": "job_xxx",
      "location": "US"
    },
    "totalRows": "1",
    "rows": [
      {
        "f": [
          {
            "v": "2000-12-30"
          }
        ]
      }
    ],
    "totalBytesProcessed": "0",
    "jobComplete": true,
    "cacheHit": false
  }
}
