### ISSUE TITLE
Please publish v2.0.0 to grafana.com

### ISSUE THREAD

**Issue by ethirolle** [doitintl/bigquery-grafana#286]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Bigquery datasource plugin v2.0.0 supports alert queries, which is a big deal to us. 

For Grafana Cloud customer, not able to install this latest version of the bigquery datasource because it is not published to plugin repository on grafana.com.

**Describe the solution you'd like**
Please submit changes to https://github.com/grafana/grafana-plugin-repository so plugin changes can be reviewed & published.

Related: please also follow steps to sign the plugin, since Grafana Cloud is moving towards eventually accepting only signed & published plugins.

**Describe alternatives you've considered**
Grafana Support informs us they only support published plugins in their Grafana Cloud instances.

Thanks!

**Comment by ledmonster** [comment]
Released assets seems to be wrong: https://github.com/doitintl/bigquery-grafana/releases/tag/2.0.0

I got "exec format error" with 2.0.0, and I found that these 3 executables under dist directory are same.

- doitintl-bigquery-datasource_darwin_amd64
- doitintl-bigquery-datasource_linux_amd64
- doitintl-bigquery-datasource_windows_amd64.exe

**Comment by zoltrain** [comment]
Hmmm, this seems to have been closed yet and the associated feature https://github.com/doitintl/bigquery-grafana/pull/292 has been merged but the plugins directory still doesn't have the latest version https://github.com/grafana/grafana-plugin-repository/blob/master/repo.json#L3763-L3767 My guess is Grafana need a PR opened to review it?

**Comment by LiorRacer** [comment]
Hi @zoltrain 

There is an open [PR](https://github.com/grafana/grafana-plugin-repository/pull/662) waiting for Grafana team to review.
Waiting for their response.

**Comment by zoltrain** [comment]
@LiorRacer sorry for that, I did a search but didn't find that open PR.

Will keep my 👀 on that PR, thanks for the plugin BTW.
