### ISSUE TITLE
Make processing location parametrizable

### ISSUE THREAD

**Issue by cyrilou242** [doitintl/bigquery-grafana#287]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I have a dashboard with dataset as a variable. Datasets are in different location. (US, EU, etc...)
As of today, I'm obliged to duplicate my dashboard for each location, because I cannot put a variable in the processing location field.

**Describe the solution you'd like**
The processing location can contain a grafana variable.

**Describe alternatives you've considered**
Duplicate dashboard.

**Teachability, Documentation, Adoption, Migration Strategy**
Apart from the dropdown with available processing location, users can also chose to use a free text field. This free text is compatible with grafana variables.

**Comment by LiorRacer** [comment]
Hi @cyrilou242 

Can you elaborate on your need? 
You can choose for each panel in the dashboard a different processing location
