### ISSUE TITLE
released 2.0.1 executables are all mac binaries

### ISSUE THREAD

**Issue by sean-dbk** [doitintl/bigquery-grafana#293]
## Bug Report

released precompiled plugins are all compiled for macos and not their respective platforms

## Expected Behavior

released artifacts are compiled for their respective platforms

## Steps to Reproduce the Problem

1. curl -LO https://github.com/doitintl/bigquery-grafana/releases/download/2.0.1/doitintl-bigquery-datasource-2.0.1.zip
2. unzip doitintl-bigquery-datasource-2.0.1.zip 
3. 
```
12:56:33 ~/tmp/dist 0:00:00
» file doitintl-bigquery-datasource_darwin_amd64 
doitintl-bigquery-datasource_darwin_amd64: Mach-O 64-bit executable x86_64
12:56:38 ~/tmp/dist 0:00:00
» file doitintl-bigquery-datasource_linux_amd64 
doitintl-bigquery-datasource_linux_amd64: Mach-O 64-bit executable x86_64
12:56:42 ~/tmp/dist 0:00:00
» file doitintl-bigquery-datasource_windows_amd64.exe 
doitintl-bigquery-datasource_windows_amd64.exe: Mach-O 64-bit executable x86_64
```

## Specifications

- Version: 2.0.1
- Platform: linux amd64
- Grafana Version: -

**Comment by LiorRacer** [comment]
Thanks, @sean-dbk updated the zip file
