### ISSUE TITLE
Usage Documentation

### ISSUE THREAD

**Issue by TimMurnaghan** [doitintl/bigquery-grafana#295]
## Feature Request

**Is your feature request related to a problem? Please describe.**
There is ZERO usage documentation. The readme stops at installation.
It's very hard to figure out what you are allowed to/have to say in a query.

**Describe the solution you'd like**
Ideally we'd have a syntax cheat sheet, and some real-world examples.
(There are many people searching in vain to see how to translate id's)
Failing that a pointer to the underlying bigquery documents, with the the documentation here about how you hook into the
grafana variables.

Slightly surprised that the last request was closed saying docs have been added. Have they been taken away again?

**Describe alternatives you've considered**
Hours of seeing if stuff on stackoverflow applies...

**Teachability, Documentation, Adoption, Migration Strategy**

**Comment by ofir5300** [comment]
HI @TimMurnaghan,
I apologize in advance if you find this answer obvious, but - are you familiar with that page: [doitintl-bigquery-datasource plugin](https://grafana.com/grafana/plugins/doitintl-bigquery-datasource/) ? 
Contains a short elaboration of _Using the Query Builder_ & _Troubleshooting_ in addition to the installation description
