### ISSUE TITLE
Unable to Use $__timeFrom and $__timeTo in SQL Query

### ISSUE THREAD

**Issue by tgtwm1github** [doitintl/bigquery-grafana#296]
## Bug Report
I have a table in bigquery (col1:string, col2:date, col3:timestamp).
A simple select col1,col2 gives is "Invalid Date" for all rows returned.

I am using 2.0.1 v of this plugin.

So I tried to use col1,col3. Same value but stored as timestamp.
This gives me a Really long "Day YYYY-Mon-DD HH24:MI:SS UTC" etc... 
I do not really need all this. I just need YYYY-MM-DD. This is the default format for bigquery.

Finally, I got around by doing
select col1, col1 as time.

Can you please make sure that a simple DATE column is query'able using a simple SQL statement and not having to
convert them to TIMESTAMP  etc?

Finally, $__timeFrom and $__timeTo does not work in SQLs

select col1,col2 from table1 where col2 between $__timeFrom and $__timeTo.
I expect this to work out of the box but it does not.
## Actual Behavior

Gives Invalid Date error.

The time filters are not being considered when written as freehand SQLs.

## Steps to Reproduce the Problem

1. create table table1(col1:string, col2:date, col3:timestamp)
2.select col1,col2 from table1. It givies Invalid Date for all rows.
3.select col1,col3 as time gives Date in YYYY-MM-DD format. but the default DATE column should return faithfully.
4. select col1,col2 from table1 where col1 between $__timeFrom and $__timeTo does not work.

## Specifications

- Version: v2.0.1
- Platform: Ubuntu Linux 18x
- Grafana Version: 7.3.5

**Comment by LiorRacer** [comment]
Hi @tgtwm1github 
Seems like the timestamp is required by Grafana, found another similar issue:https://community.grafana.com/t/graph-date-on-x-value-on-y/10074/4

I couldn't reproduce your issue with the filters ($__timeFrom and $__timeTo) is you can provide steps to reprduce

**Comment by tgtwm1github** [comment]
Lior,

Here is a sample SQL from postgres. When this is executed in grafana to
show a line graph, it takes the Timefrom() and TimeTo() values from the
"time picker" on the top right.
However, this is not working in bigquery.

select  a.industry  ,sum(b.changepercent) last30Days
from gpsecavg a, data b
where 1=1 and a.symbol=b.symbol
and b.trade_date between date($__timeTo())-30 and $__timeTo()
group by a.industry

You can simply populate the table with data for 5 days and write a query.

select * from table where date_column between $__timeTo()-30 and $__timeTo()

**Comment by tgtwm1github** [comment]
Thanks, I'll check it out.

Can I install a production ready version and test it out?

When will the 3 other bugs I opened be looked at? Any ETA please?
