### ISSUE TITLE
Same Query - Different Results from Google Console vs. Grafana-Doit-bigquery plugin

### ISSUE THREAD

**Issue by tgtwm1github** [doitintl/bigquery-grafana#297]
## Bug Report
Please find enclosed the screenshots that shows the outputs which are vastly different and with an error when using the plugin vs. when accessed via the google console.

Two issues:

1. Date column is not reproduced faithfully
2. Decimal (or NUmeric) values are truncated.
![bigquery_google_console](https://user-images.githubusercontent.com/30915432/103467724-d5218200-4d1f-11eb-8ffc-1d044133bbf3.png)
![bigquery_grafana](https://user-images.githubusercontent.com/30915432/103467725-d81c7280-4d1f-11eb-96c2-7dae7607d3c2.png)

## Expected Behavior
The results should be same, and no reformatting should be necessary
## Actual Behavior
Does not work properly
## Steps to Reproduce the Problem

1.Create a simple table in bigquery with a date,datetime column and Query the values
1. Grafana plugin results in the date column showing as Invalid Date.
1.

## Specifications

- Version: 2.0.1
- Platform: Linux
- Grafana Version: [7.3.5](url)

**Comment by LiorRacer** [comment]
Thanks, @tgtwm1github for your feedback we are looking into it

**Comment by tgtwm1github** [comment]
Just curious, so I can continue with my development activities?

How can I show "DATE" in YYYY-MM-DD format in the current version of the
plugin?
I am ok with doing any conversion if needed until the issue is fixed in
plugin.
I tried a few options and I could not get the desired result.

Appreciate if you provide a path forward in the time being.

-g
