### ISSUE TITLE
A simple Test Case to Validate each release of the Plugin

### ISSUE THREAD

**Issue by tgtwm1github** [doitintl/bigquery-grafana#298]
## Bug Report
Create a table in bigquery with columns for all datatypes (string, integer, date, datetime, timestamp, numeric etc.) and populate a few rows.
Create a Table report in Grafana.
Write a Query to get data from the bigquery table using "SQL". Not the wizard driven SQL but plain SQL from Grafana.
Ensure that the columns are displayed correctly, in the right format, as expected by comparing to Google Bigquery Console.

## Actual Behavior
Many of the data types are not reproduced faithfully.
## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version:2.0.1
- Platform:Ubuntu Linux
- Grafana Version: 7.3.5

**Comment by spark2ignite** [comment]
@tgtwm1github thank you for this very good suggestion! @Tamirk and @LiorRacer - FYI.

**Comment by ofir5300** [comment]
@tgtwm1github thanks again for this. 
We are currently acting as you suggested and will proceed this way.
