### ISSUE TITLE
Cannot create an alert

### ISSUE THREAD

**Issue by tomer-harpaz** [doitintl/bigquery-grafana#301]
## Bug Report
when creating alert I get an error :
"tsdb.HandleRequest() error Could not find executor for data source type: doitintl-bigquery-datasource"
## Expected Behavior
Get alert from Grafana
## Actual Behavior
The alert was fired only for the first time with the error:"tsdb.HandleRequest() error Could not find executor for data source type: doitintl-bigquery-datasource"
## Steps to Reproduce the Problem

1.create a new dashboard
2.create a panel with google bigquery plugin
3.create a bigquery query
4.create an alert
5. test rule: 
![image](https://user-images.githubusercontent.com/57183554/103538645-46d40a00-4e9f-11eb-9539-6c2807fdabf7.png)

## Specifications

- Version:2.0.1
- Platform:GKE
- Grafana Version: Grafana v7.0.3

**Comment by tomashman8** [comment]
I am also having this same problem.

I opened a request for this that has been closed. Am I doing something wrong? I see we are both using Grafana 7.0.3?

Would be really great if someone could let me know.

Thanks Tom

Specifications
Version:2.0.1
Platform:GKE
Grafana Version: Grafana v7.0.3

**Comment by LiorRacer** [comment]
Hi all, 
Seems we have to recompile the plugin for this platform, will do it soon

**Comment by tribuste** [comment]
@LiorRacer Hi, do you have some approximation when it could be done? Next week? Or later?

**Comment by Geoiv** [comment]
I am also very excited for this functionality - any approximation on when it may be completed would be greatly appreciated, so I can try to plan around it.

**Comment by Gigioliva** [comment]
any news?

**Comment by ofir5300** [comment]
Hi everybody,
The plugin should be working on the GKE platform on the coming release (2.0.2), which I hope we will release soon.

**Comment by codeblooded** [comment]
@ofir5300 Just following up. I see this was removed from the 2.0.2 milestone. Is this fix still intended in the upcoming release?

**Comment by ofir5300** [comment]
Hi @codeblooded,
Unfortunately this won't be fixed in the coming release for the reason this issue is most likely not related to the environment (GKE), rather related to the **Alert** feature.
I hope we can put additional effort and solve this on the release which will follow 2.0.2
