### ISSUE TITLE
Problem with reading and interpreting the bigquery datasets.

### ISSUE THREAD

**Issue by tgtwm1github** [doitintl/bigquery-grafana#302]
## Bug Report
I have a dataset named "STOCK".

When I see the Query Output in Grafana, The information does not seem right.
I feel that the plugin is unable to Parse and Read the datasets structure correctly.

Object
request:Object
method:"GET"
url:"api/datasources/proxy/3/bigquery/v2/projects/tock/datasets/aggressive_recommendatio/tables/undefined"
hideFromInspector:false
response:Object
error:Object
code:404
message:"Not found: Project tock"
errors:Array[1]
status:"NOT_FOUND"

## Expected Behavior
Should be

url:"api/datasources/proxy/3/bigquery/v2/projects/**s**tock/datasets/aggressive_recommendatio**n**/tables/undefined"

## Actual Behavior
url:"api/datasources/proxy/3/bigquery/v2/projects/tock/datasets/aggressive_recommendatio/tables/undefined"

The "S" in STOCK and "N" in recommendation are missing.

message:"Not found: Project tock"

Also, it says: Not found: Project tcok. The Dataset Name is "STOCK".

## Steps to Reproduce the Problem

1. I do not have a valid steps to reproduce. Perhaps you can create the same dataset name and table name and try for yourself.
1.
1.

## Specifications

- Version:2.0.1
- Platform: Linux
- Grafana Version: 7.3.5

**Comment by ofir5300** [comment]
Please update to v2.0.3 (Available on [Grafana cloud](https://grafana.com/grafana/plugins/doitintl-bigquery-datasource/)) and let me know if it persist

**Comment by ofir5300** [comment]
We are retiring the [DoiT International BigQuery DataSource plugin](https://grafana.com/grafana/plugins/doitintl-bigquery-datasource/) for Grafana. We recommend that you migrate to the official [Google BigQuery data source](https://grafana.com/grafana/plugins/grafana-bigquery-datasource/) maintained by Grafana. In August 2022, we will cease all development and archive the GitHub project.

We are sorry for any inconvenience.
