### ISSUE TITLE
Occur Query run error when alerting

### ISSUE THREAD

**Issue by sshota0809** [doitintl/bigquery-grafana#303]
Thank you for seeing this issue.

## Bug Report
when alerting I got "Query run error".

## Expected Behavior
Grafana is done with alerting process.

## Actual Behavior
Following logs are outputted.

```
t=2021-01-06T11:53:01+0000 lvl=info msg="Query run error: %v\n" logger=plugins.backend pluginId=doitintl-bigquery-datasource
t=2021-01-06T11:53:01+0000 lvl=eror msg="query BigQueryRun error %v" logger=plugins.backend pluginId=doitintl-bigquery-datasource
t=2021-01-06T11:53:01+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=4 name=test error="tsdb.HandleRequest() error rpc error: code = Unavailable desc = connection error: desc = \"transport: error while dialing: dial unix /tmp/plugin864917002: connect: connection refused\"" changing state to=alerting
```

## Steps to Reproduce the Problem

1. Create an alert
1. When metric exceed threadhold Above errors occur.

## Specifications

- Version:v2.0.1
- Platform: Ubuntu 18.04.2 LTS(Host)
- Grafana Version:v7.3.6(Docker image(grafana/grafana:7.3.6))

## Detail

I reffered to source file where above error is implemented and then it seems Query Running is failed for some reasen.
https://github.com/doitintl/bigquery-grafana/blob/756780ef960c21df941467e597e642a47d5a53f0/pkg/plugin.go#L187

But It seems strange that `err` object is expanded to `%v`. So I had no idea why err is not nil.

```
msg="Query run error: %v\n"
```

I implemented Query running program with BigQuery library in the same way. And I used same query but No Error happned.

Testing rule I used is following one.
```
{
  "firing": true,
  "state": "pending",
  "conditionEvals": " = true",
  "timeMs": "-751.375ms",
  "error": "tsdb.HandleRequest() error rpc error: code = Unavailable desc = transport is closing",
  "logs": [
    {
      "message": "Condition[0]: Query",
      "data": {
        "from": 1609986547778,
        "queries": [
          {
            "refId": "A",
            "model": {
              "format": "time_series",
              "group": [],
              "metricColumn": "none",
              "orderByCol": "1",
              "orderBySort": "1",
              "rawQuery": true,
              "rawSql": "SELECT \n      PARSE_TIMESTAMP('%Y-%m-%d %H:%M:%S',CONCAT(SUBSTR(FORMAT_TIMESTAMP('%Y-%m-%d %H:%M:%S', timestamp), 0, 15), \"0:00\")) AS ctime,\n       count(*) AS error_count\nFROM `GCP_PROJECT_NAME.k8slogs.stdout_*`\nWHERE\n    _TABLE_SUFFIX BETWEEN '${__from:date:YYYYMMDD}' AND '${__to:date:YYYYMMDD}'\n    AND jsonPayload.status like '5%'\nGROUP BY ctime\nORDER BY ctime",
              "refId": "A",
              "select": [
                [
                  {
                    "params": [
                      "-- value --"
                    ],
                    "type": "column"
                  }
                ]
              ],
              "timeColumn": "-- time --",
              "timeColumnType": "TIMESTAMP",
              "where": [
                {
                  "name": "$__timeFilter",
                  "params": [],
                  "type": "macro"
                }
              ]
            },
            "datasource": {
              "id": 11,
              "name": "Google BigQuery"
            },
            "maxDataPoints": 0,
            "intervalMs": 0
          }
        ],
        "to": 1609986847778
      }
    }
  ]
}
```

**Comment by sshota0809** [comment]
I researched this issue more. And I got a clue.

https://github.com/doitintl/bigquery-grafana/blob/204890b6d4caa4109c7f1be052a54415806d6138/pkg/plugin.go#L85-L106

It seems that elements of `req.Queries` isn't contain `json:"project"` in it.
And Query running is failed because of following message from GCP.

```
Error 400: Invalid project ID ''. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.
```
So I think elements of `req.Queries` have to contain `json:"project"` in it.

**Comment by LiorRacer** [comment]
Hi @sshota0809 
Thanks for the logger fix.
Regarding the missing field `project`, seems like it is there see the screenshots below:
Query builder mode
![image](https://user-images.githubusercontent.com/13584904/105636401-f3872300-5e70-11eb-9823-7665fee0c2ea.png)

Raw query mode:
![image](https://user-images.githubusercontent.com/13584904/105636770-7fe61580-5e72-11eb-9953-c5b66806a8dc.png)

**Comment by thomasZen** [comment]
I get the same error  when testing an alert rule in Grafana:
```
"tsdb.HandleRequest() error rpc error: code = Unavailable desc = transport is closing"
Error="googleapi: Error 400: Invalid project ID ''. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash., invalid"
```

The query is the following and includes the project id:
```
SELECT 
 TIMESTAMP_ADD(TIMESTAMP(DATETIME_TRUNC(`datetime`, DAY)), INTERVAL 24 HOUR) as time,
 	FORMAT("%d", modelId) as metric,
 ((SUM(correctAdapted) - SUM(correctUnadapted)) / SUM(total)) * 100 AS adaptationDiff, 
FROM `arched-champion-847.neural.word_prediction_accuracy`
GROUP BY 1,2
HAVING SUM(total) > 1000 AND SUM(correctAdapted)/SUM(total) < 0.6
ORDER BY 1 DESC, 2
LIMIT 10000
```

**Comment by thomasZen** [comment]
@LiorRacer It seems like #304 only improved how this error is logged. Do you have additional insights on it or any tips how to circumvent it?

**Comment by LiorRacer** [comment]
Hi @thomasZen,
What version of the plugin are you using?
Are you using the queryBuilder or SQL editor?

**Comment by thomasZen** [comment]
> What version of the plugin are you using?

We use version `2.0.1`

> Are you using the queryBuilder or SQL editor?

For the query above I used the SQL editor. I also tried the queryBuilder. Using the query builder adds `project: foobar` into the json object. But I end up with the same `tsdb.HandleRequest()` error when testing the alert.

In the SQL editor is there a specific format one has to follow (in addition to including the timestamp, metric and value)?

I also found the following structure in the codebase:
https://github.com/doitintl/bigquery-grafana/blob/236822d09107c8bbd8224abf21e89294659c951f/pkg/plugin.go#L30-L51

bigquery-grafana expect all of these fields in the json object, right?

**Comment by sshota0809** [comment]
Hi, @thomasZen 

>  I used the SQL editor.
In the case of using the SQL editor, I think you should *also* specify the GCP project number in the SQL builder. Because when the backend plugin executes query to BigQuery, it refers to the value of GCP project number specified in SQL builder.
