### ISSUE TITLE
UTC conversion is returning offset data

### ISSUE THREAD

**Issue by tanner-bruce** [doitintl/bigquery-grafana#307]
## Expected Behavior

Conversion to UTC should be performed seamlessly without needing to use a time shift.

## Actual Behavior

When using the `Convert to UTC` option for querying a table based on UTC time with a `TIMESTAMP` type, the created `Date` object returns a time that is offset to UTC but still reported as the browser timezone, leading to the returned data being offset by the browser timezone.

## Steps to Reproduce the Problem

1. Create use a `TIMESTAMP` type time column
2. Fill with UTC based data
3. Have the browser timezone be something other than UTC
4. Check the `Convert to UTC` option

**Comment by ofir5300** [comment]
Hi @tanner-bruce,
I couldn't reproduce the issue - 
My browser indeed isn't set to UTC time, and when I used the `convert to UTC` option it worked well and convert my given time to a valid UTC time.

It might be related to your plugin version, please be sure you are up to date with our most recent version (currently 2.0.1 and soon to release another one).
Beside of that, if the issue still occur, please elaborate and be more specific so I will be able to reproduce it.

**Comment by ofir5300** [comment]
@tanner-bruce please feel free to generate another issue with additional details if the problem still occur.
