### ISSUE TITLE
Unable to install v2.0.2 release

### ISSUE THREAD

**Issue by seuf** [doitintl/bigquery-grafana#320]
## Expected Behavior

Install the plugin, restart grafana, plugin is visible in grafana datasources

## Actual Behavior

Grafana logs an error about manifest listed files

## Steps to Reproduce the Problem

1. Add `doitintl-bigquery-datasource` plugin in grafana plugin list (with environment var) :
```
GF_INSTALL_PLUGINS=https://github.com/doitintl/bigquery-grafana/releases/download/2.0.2/doitintl-bigquery-datasource-2.0.2.zip;doitintl-bigquery-datasource
```
2. restart grafana
3. There is an error in grafana logs :
> Plugin file listed in the manifest was not found" logger=plugins plugin=doitintl-bigquery-datasource filename=MANIFEST1.txt dir=/var/lib/grafana/plugins/doitintl-bigquery-datasource

I can't found MANIFEST1.txt and MANIFEST2.txt in archive.zip.

## Specifications

- Version: 2.0.2
- Platform: linux
- Grafana Version: 7.5.2

**Comment by ofir5300** [comment]
Hi @seuf, version 2.0.2 is yet to be signed by Grafana.
[2.0.1 release](https://github.com/doitintl/bigquery-grafana/releases/tag/2.0.1) is currently the latest release.
I tagged 2.0.2 as a pre-release until approval.

**Comment by peikk0** [comment]
Hi @ofir5300, any ETA for that?

**Comment by ofir5300** [comment]
@peikk0 I wish I could tell..
