### ISSUE TITLE
unable to use the unsigned plugindoitintl-bigquery-datasource

### ISSUE THREAD

**Issue by arunkumarjca** [doitintl/bigquery-grafana#323]
I have updated the allow_loading_unsigned_plugins in grafana.ini

# cat /etc/grafana/grafana.ini|grep -i doitintl-bigquery-datasource
;allow_loading_unsigned_plugins = doitintl-bigquery-datasource

But still i cant able to use the plugin .

**Comment by ofir5300** [comment]
Hi @arunkumarjca,
In order to make it work you should update the relevant line this way:
`allow_loading_unsigned_plugins = "doitintl-bigquery-datasource"`

**doitintl-bigquery-datasource** should be in quotes, and no semicolon (;) at the beginning.
