### ISSUE TITLE
_PARTITIONTIME filter is added to queries on table without partitions

### ISSUE THREAD

**Issue by peikk0** [doitintl/bigquery-grafana#325]
## Bug Report

I have a couple very small tables without any partitioning, and the timerange filter on `_PARTITIONTIME` is added to queries on those tables, causing the query to fail because the column doesn't exist.

Again it would be nice to have an option for disabling any sort of automatic query alteration, I prefer setting the partition filter explicitly when it is needed.

## Expected Behavior

This query using a table without partitioning stays unaltered and works:
```sql
SELECT
  CURRENT_TIMESTAMP() AS time,
  COUNT(state) AS value
FROM
  `$my_table`
WHERE
  state = 'ACTIVE'
GROUP BY 1
ORDER BY 1 ASC
```

## Actual Behavior

The query above is modified to:
```sql
SELECT
  CURRENT_TIMESTAMP() AS time,
  COUNT(state) AS value
FROM
  `$my_table`
where _PARTITIONTIME >= '2021-02-28 11:00:00' AND _PARTITIONTIME < '2021-03-31 10:59:59' AND 
  state = 'ACTIVE'
GROUP BY 1
ORDER BY 1 ASC LIMIT 1248
```
and fails with `Unrecognized name: _PARTITIONTIME; Did you mean _PARTITION_NAME? at [6:7]`

This doesn't happen if the WHERE clause is missing though.

## Steps to Reproduce the Problem

1. Create a table without partition
1. Add a panel querying this table and using a WHERE clause

## Specifications

- Version: 2.0.1
- Platform: n/a
- Grafana Version: 7.5.3

**Comment by peikk0** [comment]
As a workaround I'm currently adding an empty results query at the beginning using another table that does have a time partition so that it gets the `_PARTITIONTIME` filter instead of the actual query:
```sql
SELECT CURRENT_TIMESTAMP(), 0 FROM `$source_table` WHERE 1 = 2 UNION ALL
SELECT ...
```

**Comment by ofir5300** [comment]
Hi @peikk0, I am aware that you are not using any `partition` in your query so I pre assume this solved issue (https://github.com/doitintl/bigquery-grafana/issues/309) won't necessarily handle your case..
But can you please upgrade to our published v2.0.2 and let me know if the issue still occurs?

**Comment by bacheson** [comment]
@ofir5300 this problem still exists in v2.0.2

**Comment by ofir5300** [comment]
Ok, thank you for sharing this information @bacheson

**Comment by ofir5300** [comment]
Well I was using a table with no partition but was not able to reproduce that issue, I might be missing something though.

@peikk0 
Does this happens to you when writing raw sql? If so - no additions should be made to your where clause. 
Are you 100% positive the given tables are not partitioned?

**Comment by peikk0** [comment]
@ofir5300 I have changed jobs in the meantime so I'm no longer able to test this particular issue. That was happening with raw SQL queries with a table using a JSON file as external data, no partition was configured (no need for one as the file was tiny and there wasn't any field that would have been a good fit for that anyway).

Also all my BigQuery panels were using raw SQL and all of them had the WHERE clause automatically modified with the partition filter, which was particularly annoying with some queries that needed to run outside of the selected timerange (eg. time-shifted graphs and table). I still think there need to be an option to explicitly disable this feature, either per query or globally.

**Comment by bacheson** [comment]
@ofir5300 I can reproduce this

You can partition a table by date in two ways:

1) Ingestion time - this works fine
2) By field - this does not work

If you create a table with a timestamp field and partition on the column the plugin blows up with "invalidQuery: Unrecognized name: _PARTITIONTIME"

**Comment by ofir5300** [comment]
Related issue:
https://github.com/doitintl/bigquery-grafana/issues/362

**Comment by mgerasimchuk** [comment]
> Well I was using a table with no partition but was not able to reproduce that issue, I might be missing something though.
> 
> @peikk0
> Does this happens to you when writing raw sql? If so - no additions should be made to your where clause.
> Are you 100% positive the given tables are not partitioned?

Hi @ofir5300 you may try to use graph panel to reproduce this issue.
If I use "single stat" panel, I don't faced this issue, because "single stat" panel send only one request to the database.
But the "graph" panel, sends multiple request for each interval, and during this process inject a _PARTITIONTIME.

![image](https://user-images.githubusercontent.com/13135129/130739004-398ced04-cdce-4db7-9f77-aa605665ccfc.png)

Grafana Query:
```
SELECT
  TIMESTAMP(format("%t %02d:00:00", Date, HourOfDay)) as time,
  c.CampaignName,
  SUM(cs.Impressions) AS Impressions,
  SUM(cs.Interactions) AS Interactions,
  SUM(cs.Clicks) AS Clicks,
  SUM(cs.Conversions) AS Conversions,
  (SUM(cs.Cost) / 1000000) AS Cost,
FROM
  `***.scheduled_transfer_google_ads_formerly_adwords.Campaign_***` c
LEFT JOIN
  `***.scheduled_transfer_google_ads_formerly_adwords.HourlyCampaignStats_***` cs
ON
  (c.CampaignId = cs.CampaignId)
WHERE 
  c.CampaignStatus="ENABLED"
GROUP BY
  time, c.CampaignName
HAVING
  time > TIMESTAMP_SECONDS(${__from:date:seconds}) AND time < TIMESTAMP_SECONDS(${__to:date:seconds})
ORDER BY
  time
LIMIT
  9000
```

Rendered query:
```
SELECT
  TIMESTAMP(format("%t %02d:00:00", Date, HourOfDay)) as time,
  c.CampaignName,
  SUM(cs.Impressions) AS Impressions,
  SUM(cs.Interactions) AS Interactions,
  SUM(cs.Clicks) AS Clicks,
  SUM(cs.Conversions) AS Conversions,
  (SUM(cs.Cost) / 1000000) AS Cost,
FROM
  `***.scheduled_transfer_google_ads_formerly_adwords.Campaign_***` c
LEFT JOIN
  `***.scheduled_transfer_google_ads_formerly_adwords.HourlyCampaignStats_***` cs
ON
  (c.CampaignId = cs.CampaignId)
where _PARTITIONTIME >= '2018-01-25 08:51:56' AND _PARTITIONTIME < '2018-01-25 19:13:42' AND  
  c.CampaignStatus="ENABLED"
GROUP BY
  time, c.CampaignName
HAVING
  time > TIMESTAMP_SECONDS(1516870316) AND time < TIMESTAMP_SECONDS(1516907622)
ORDER BY
  time
LIMIT
  9000
```
