### ISSUE TITLE
Failed to start backend plugin v2.0.2

### ISSUE THREAD

**Issue by tmanh17** [doitintl/bigquery-grafana#331]
## Bug Report

I tried to use alert feature in the PR https://github.com/doitintl/bigquery-grafana/pull/322 but can't not start backend plugin v2.0.2.

some logs:
```
lvl=eror msg="Failed to start plugin" logger=plugins.backend pluginId=doitintl-bigquery-datasource error="fork/exec /var/lib/grafana/plugins/doitintl-bigquery-datasource/dist/doitintl-bigquery-datasource_linux_amd64: permission denied"

lvl=eror msg="Failed to start plugin" logger=plugins.backend pluginId=doitintl-bigquery-datasource error="fork/exec /var/lib/grafana/plugins/doitintl-bigquery-datasource/dist/doitintl-bigquery-datasource_linux_amd64: no such file or directory"
```

## Steps to Reproduce the Problem

1. Install plugin v2.0.2 manually from branch OfirCohen/v2.0.2

    ```cd /var/lib/grafana/plugins/```
    ```git clone -b OfirCohen/v2.0.2 https://github.com/doitintl/bigquery-grafana.git doitintl-bigquery-datasource```

2. restart grafana ```service grafana-service restart```
3. Try to fix some errors as the following

## Tried
1. try to add allow_loading_unsigned_plugins = doitintl-bigquery-datasource to [plugins] in /etc/grafana/grafana.ini
 get error: ```msg="Failed to start plugin" logger=plugins.backend pluginId=doitintl-bigquery-datasource error="fork/exec /var/lib/grafana/plugins/doitintl-bigquery-datasource/dist/doitintl-bigquery-datasource_linux_amd64: permission denied"```

2. then try  ```chmod 755 doitintl-bigquery-datasource_linux_amd64```
get error: 
```
t=2021-05-01T15:24:10+0700 lvl=warn msg="Running an unsigned backend plugin" logger=plugins pluginID=doitintl-bigquery-datasource pluginDir=/var/lib/grafana/plugins/doitintl-bigquery-datasource/dist
t=2021-05-01T15:24:10+0700 lvl=info msg="Registering plugin" logger=plugins id=doitintl-bigquery-datasource
t=2021-05-01T15:24:10+0700 lvl=eror msg="Failed to start plugin" logger=plugins.backend pluginId=doitintl-bigquery-datasource error="fork/exec /var/lib/grafana/plugins/doitintl-bigquery-datasource/dist/doitintl-bigquery-datasource_linux_amd64: no such file or directory"
```

## Specifications

- Version: 2.0.2
- Platform: Debian 8.5
- Grafana Version: Grafana v7.4.2

**Comment by ofir5300** [comment]
Hi @tmanh17,
Branch OfirCohen/v2.0.2 does not currently includes the updated builds of the plugin, thus cannot be run locally on your machine (or anywhere).
I will update you once this branch is useful (should be soon).

**Comment by tmanh17** [comment]
Hi @ofir5300 

Could you please share any news. I saw that there was a pull request to update binary builds at https://github.com/doitintl/bigquery-grafana/pull/332. But when I try to run locally again, I get some other errors

Firstly, I tried to test alert by builder query then get the following error when click Test Rule button

```error="tsdb.HandleRequest() response error &{alerting queries only support raw sql alerting queries only support raw sql A <nil> [] [] 0xc000fe9800}"```

Then tried to create the chart by SQL then get another error when click Test Rule button

```error:"tsdb.HandleRequest() response error &{expected 'query.Location' or 'req.PluginContext.DataSourceInstanceSettings.JSONData.processingLocation' to be set expected 'query.Location' or 'req.PluginContext.DataSourceInstanceSettings.JSONData.processingLocation' to be set A <nil> [] [] 0xc000dcc210}"```

**Comment by ofir5300** [comment]
Hi @tmanh17,
Master branch currently includes all relevant updates (plugin builds as well).
version 2.0.2 isn't signed yet due to its pending status on [grafana-plugin-repository](https://github.com/grafana/grafana-plugin-repository/pull/913).

Regarding your local run, those alert errors are healthy - meaning you are running the last update of the alert feature.  
Exactly like the error mentioned, location should be added in order to activate your alert..
<img width="1011" alt="Screen Shot 2021-05-12 at 18 06 12" src="https://user-images.githubusercontent.com/40420259/117998758-deb19b00-b34c-11eb-8673-17855dff6b24.png">

**Comment by tmanh17** [comment]
@ofir5300 That's good to hear.

I added location. then create a query and it get another errors

<img width="450" alt="portfolio_view" src="https://user-images.githubusercontent.com/29015535/118001472-f4d15280-b370-11eb-8599-1e36148ad176.png">

<img width="450" alt="portfolio_view" src="https://user-images.githubusercontent.com/29015535/118001349-dd926500-b370-11eb-82c9-26bab0223a80.png">

<img width="450" alt="portfolio_view" src="https://user-images.githubusercontent.com/29015535/118001282-c94e6800-b370-11eb-8876-04f604b165c3.png">

**Comment by tmanh17** [comment]
Updated, It works if the macro is removed. Thanks
