### ISSUE TITLE
Note : The partitioned column appear in the where clause even if it's not the time Column.

### ISSUE THREAD

**Issue by zorel** [doitintl/bigquery-grafana#334]
HEllo.

I still have the following issue when using 2.0.2 on partition tables:

Note : The partitioned column appear in the where clause even if it's not the time Column.
```
SELECT
 TIMESTAMP_SECONDS(DIV(UNIX_SECONDS(`buildTime`), 86400) * 86400) AS time,
  `name` AS metric,
  count(`id`) AS id
FROM `redacted`
WHERE
  `buildTime` BETWEEN TIMESTAMP_MILLIS (1611413253148) AND TIMESTAMP_MILLIS (1614005253148) AND
  insert_date >= '2021-01-23 15:21:36' AND
  insert_date < '2021-02-22 15:21:36'
GROUP BY 1,2,2 
ORDER BY 1,2 LIMIT 2110"
```
And the parameters are not correctly casted : 
> Could not cast literal "2021-01-23 15:21:36" to type DATE

_Originally posted by @seuf in https://github.com/doitintl/bigquery-grafana/issues/309#issuecomment-783428388_

Table details: 

Table type Partitioned
Partitioned by Day
Partitioned on field log_date
Partition expiration 365 days
Partition filter Not required

![image](https://user-images.githubusercontent.com/630762/117469712-54d18e80-af56-11eb-9360-c55779d8f713.png)

The request contains at least these lines even with the timecolumn set to log_timestamp
WHERE
  log_date >= '2021-04-15 00:00:00' AND
  log_date < '2021-04-16 23:59:59'

**Comment by ofir5300** [comment]
Hi @zorel,
**Question**: For time ranging best practice, do you think a filter on the `partition field` should not be added if a `filter on the time field` already exist?
