### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by codeblooded** [doitintl/bigquery-grafana#342]
As Grafana moves to an AGPL license that requires anything depending on it, modifying it or serving it over a network to also adopt a copyleft license; can this project continue under the MIT License? Will it depend on any of the relicensed Grafana code that will cause the AGPL to be indirectly inherited by this project?

**Comment by spark2ignite** [comment]
Our intention is to continue with the MIT license for as long as possible. We hope Grafana will keep merging our plugin upstream under the current license.
