### ISSUE TITLE
Cannot find BigQuery data source after installing it

### ISSUE THREAD

**Issue by aalyousfi** [doitintl/bigquery-grafana#345]
## Expected Behavior
After installing the BigQuery data source plugin, I expect to see it in the list of data sources in my Grafana instance.

## Actual Behavior
After installing the BigQuery data source plugin, I'm not able to find it in the list of data sources in my Grafana instance.

A screenshot showing that the plugin has been installed:

<img width="1385" alt="Screen Shot 2021-06-16 at 3 41 06 PM" src="https://user-images.githubusercontent.com/84382548/122213306-e28b8c80-ceb9-11eb-9b3f-8a9836c82120.png">

A screenshot showing that I couldn't find BigQuery data source in my instance after plugin installation:

<img width="1360" alt="Screen Shot 2021-06-16 at 3 41 22 PM" src="https://user-images.githubusercontent.com/84382548/122213429-fdf69780-ceb9-11eb-85cd-08a2d594ef7d.png">

## Specifications
- Version: 2.0.1
- Platform: Grafana Cloud
- Grafana Version: 8.0.2

**Comment by ofir5300** [comment]
Hi @aalyousfi,
Please try installing version 2.0.2 and let me know if the issue persist.

**Comment by ofir5300** [comment]
> I have the same issue.

@k3vl4r7 Have you installed v2.0.2?

**Comment by k3vl4r7** [comment]
yes, @ofir5300 i installed v2.0.2

**Comment by k3vl4r7** [comment]
i am running grafana 8.2.3

**Comment by k3vl4rAtAirside** [comment]
runing on centos rel7

Linux ip-172-31-1-152.service.consul 3.10.0-1160.42.2.el7.x86_64 #1 SMP Tue Sep 7 14:49:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by k3vl4r7** [comment]
it works on my local instance of grafana running 8.0.2, but my companies grafana is running latest 8.2.3 and the data source doesnt show up.  must be a conflict somewhere

**Comment by ofir5300** [comment]
Please update to v2.0.3 (Available on [Grafana cloud](https://grafana.com/grafana/plugins/doitintl-bigquery-datasource/)) and let me know if it persist

**Comment by k3vl4rAtAirside** [comment]
this issue still persists with the latest versions 2.0.3 and grafana latest 8.4.5

**Comment by ofir5300** [comment]
We are retiring the [DoiT International BigQuery DataSource plugin](https://grafana.com/grafana/plugins/doitintl-bigquery-datasource/) for Grafana. We recommend that you migrate to the official [Google BigQuery data source](https://grafana.com/grafana/plugins/grafana-bigquery-datasource/) maintained by Grafana. In August 2022, we will cease all development and archive the GitHub project.

We are sorry for any inconvenience.
