### ISSUE TITLE
Authentication via service account failed

### ISSUE THREAD

**Issue by smm0864** [doitintl/bigquery-grafana#348]
## Expected Behavior
after following the installation guide, the authentication should work

## Actual Behavior
When using the service account (JWT) method, i get the following error when hitting "test"
![Bildschirmfoto 2021-06-30 um 08 40 44](https://user-images.githubusercontent.com/16778156/123921834-b971fe00-d987-11eb-988e-efc1e7ae1b89.png)
i tried multiple accounts (3 from scratch following the instruction + 2 existing ones), including one that is working with the google api which i used to connect to google sheets.

BigQuery API is enabled, i used the provisioning method, uploaded the JSON file via UI and also pasted the content of the file into the UI. All with the same result.

## Steps to Reproduce the Problem

1. Create a service account
2. C reate a "JSON-Key"
3. Copy the content of the file to the text field
4. click test

## Specifications

- Version: 2.0.1
- Platform: We host Grafana via Cloud Foundry
- Grafana Version: 7.1.5

NOTE: Regardless of the problem mentioned, i think such an issue shouldn't be displayed as a green message with an "OK-hook"

**Comment by ofir5300** [comment]
Hi @smm0864,
Sorry for validating but have you gave the service account the correct `Role`s? 
`BigQuery Data Viewer` and `BigQuery Job User`

In addition, please update to our most recent plugin (v2.0.2) and let me know if the issue still occurs.

**Comment by ofir5300** [comment]
If it is not solved, please open a new issue
