### ISSUE TITLE
Macros e.g. `$__timeFilter` ignore parameter value

### ISSUE THREAD

**Issue by sisidra** [doitintl/bigquery-grafana#356]
## Bug Report

When specifying raw sql query it is possible to use macros and [according to documentation](https://github.com/doitintl/bigquery-grafana/blob/bf6c8a47f7c10bb89e2e73976e1ab7951ded3ac2/src/partials/query.editor.html#L240-L243) they should expand based on parameter value.
E.g. `$__timeFrom(_PARTITIONTIME)` -> `_PARTITIONTIME` > '[ISO timestamp]'`

This is not what happens.

Parameter is ignored if `time column` parameter is not cleared from query builder.
Parameter is replaced with first value if multiple macros are used.

Example query:
```sql
SELECT event_time time, SUM(amount) amount
   FROM `p.d.t`
 WHERE $__timeFrom(_PARTITIONTIME)
    AND $__timeFilter(event_time)
```

## Expected Behavior

Generate:
```sql
SELECT event_time time, SUM(amount) amount
   FROM `p.d.t`
 WHERE _PARTITIONTIME >= '[ISO timestamp]'
    AND event_time BETWEEN '[ISO timestamp]' AND '[ISO timestamp]'
```

## Actual Behavior

```sql
SELECT event_time time, SUM(amount) amount
   FROM `p.d.t`
  WHERE `t` > TIMESTAMP_MILLIS (...)
      AND `t` BETWEEN TIMESTAMP_MILLIS (...) AND TIMESTAMP_MILLIS (...)
```

## Steps to Reproduce the Problem

1. Get commit https://github.com/doitintl/bigquery-grafana/commit/9f07cf23ce6a64561f0146d62bd70a2b31b7e23f
1. Run `npm test`

## Specifications

- Version: current master (commit: bf6c8a47f7c10bb89e2e73976e1ab7951ded3ac2)
- Platform: any
- Grafana Version: any

**Comment by sisidra** [comment]
For more real world consequences: this bug can be silent as a result picking wrong column in wrong macros and generating queries that process Terabytes of data instead of few Gigabytes.

**Comment by ilangoodman** [comment]
We have the same problem, with the same consequence. This was previously reported in #40 which was closed without a clear resolution.

**Comment by ofir5300** [comment]
We are retiring the [DoiT International BigQuery DataSource plugin](https://grafana.com/grafana/plugins/doitintl-bigquery-datasource/) for Grafana. We recommend that you migrate to the official [Google BigQuery data source](https://grafana.com/grafana/plugins/grafana-bigquery-datasource/) maintained by Grafana. In August 2022, we will cease all development and archive the GitHub project.

We are sorry for any inconvenience.
