### ISSUE TITLE
add support for firebase events exported to bigquery

### ISSUE THREAD

**Issue by carocad** [doitintl/bigquery-grafana#360]
## Feature Request

**Is your feature request related to a problem? Please describe.**
We have a firebase project with BigQuery integration where events from a mobile app are sent to big query. The exported  tables are named as events_YYYYMMDD (see [example queries](https://support.google.com/firebase/answer/9037342?hl=en#zippy=%2Cin-this-article)). So far none of the time macros create an sql query appropriate for big query format.

**Describe the solution you'd like**
A time macro (or flag on one of the existent one) to create the event suffix as 
```sql
$__timeFilter(_TABLE_SUFFIX, 'firebase')
# that should generate something like
# _TABLE_SUFFIX BETWEEN '20210713' AND '20210720'
```

**Describe alternatives you've considered**
An alternative is to expose the time range from Grafana as a variable (like `$__timeRangeStart` and `$__timeRangeEnd`). This way I could use sql functions to format those as strings without using a time macro.

**Comment by ofir5300** [comment]
We are retiring the [DoiT International BigQuery DataSource plugin](https://grafana.com/grafana/plugins/doitintl-bigquery-datasource/) for Grafana. We recommend that you migrate to the official [Google BigQuery data source](https://grafana.com/grafana/plugins/grafana-bigquery-datasource/) maintained by Grafana. In August 2022, we will cease all development and archive the GitHub project.

We are sorry for any inconvenience.
