### ISSUE TITLE
Macros do not work in alerts

### ISSUE THREAD

**Issue by briantopping** [doitintl/bigquery-grafana#361]
## Bug Report
Queries using [`$__` macros](https://github.com/doitintl/bigquery-grafana/blob/bf6c8a47f7c10bb89e2e73976e1ab7951ded3ac2/src/partials/query.editor.html#L240-L246) that work fine in the UI fail to work as alerts.

## Expected Behavior
We have a query that uses `$__timeFilter(COLUMN)` to constrain a query from terabytes of data down to just the data that is important for the query. It works as expected. When we set an alert with bounds on this query, the query fails because the `$__timeFilter()` is processed in the frontend (ie [here](https://github.com/doitintl/bigquery-grafana/blob/d5d369f3fd97a7dccc0611b3dc1778de093e6f96/src/bigquery_query.ts#L567-L571)), not the backend. 

## Steps to Reproduce the Problem

1. Create a query with any of the above macros
1. Set an alert on that query

## Notes
If there is a workaround to this, would love to discover it. One is obviously to manually expand the macro in every query. It does seem that the alerting UI should at least warn that there are components of the selected query that will not work as an alert.

**Comment by harishkashyap569** [comment]
I’m on the same boat as well! Looking for a solution workaround.

**Comment by ofir5300** [comment]
Hi @briantopping,
Please go to relevant alert, click on `test rule` and approve that the error you get is `Illegal input character "$" at.....` ?

**Comment by briantopping** [comment]
Hi @ofir5300, thanks for looking at this. That is the correct error.

**Comment by ofir5300** [comment]
@briantopping Fixed and merged to master.

Note that if you are running our plugin locally on a Mac machine, you can use it starting now. 
Simply adjust plugin source to use local repository (`bigquery-grafana/dist` includes the updated mac binary file), 
And of course `allow_loading_unsigned_plugins`.
Please let me know if you need more detailed instructions about how to use it locally.

Will be added to version 2.0.3 hopefully soon and then will be useful for everyone.

**Comment by briantopping** [comment]
That's great, thank you! I will pass along that a release is forthcoming. A lot of folks are eagerly awaiting. Thanks again for your efforts to resolve this!!
