### ISSUE TITLE
Cannot reset service account key

### ISSUE THREAD

**Issue by eunice98k** [doitintl/bigquery-grafana#365]
## Bug Report
Clicking the `Reset Service Account Key` button sends me to Grafana's Dashboard Home page and does not properly reset the configured service account key.
![image](https://user-images.githubusercontent.com/43913498/128249158-01df74af-73e8-4d49-affa-05623dc7b647.png)

## Expected Behavior
I expect the `Reset Service Account Key` to clear all of the existing key details and allow uploading a new key without having to delete the whole data source plugin.
![image](https://user-images.githubusercontent.com/43913498/128249212-bb5279eb-0b40-45fd-be55-80afd544db7a.png)

## Steps to Reproduce the Problem

1. Create a new Google BigQuery data source 
2. Upload a service account key file
3. Click Save & Test
4. Click Reset Service Account Key
5. Go back to Google BigQuery data source to see the key details still configured

## Specifications

- Version: 2.0.2
- Platform: Grafana Cloud
- Grafana Version: `main` branch

cc @alolita

**Comment by ofir5300** [comment]
Hi @eunice98k, tested your case and it seems to work just fine..
Tested it both before and after clicking `save & test` and got the expected result (cleaning details fields).

Are you positive that you are using the most updated version?

**Comment by nicolasigor** [comment]
I have the same issue. The button just redirect to "/#" (main page).
I am using Grafana v8.3.3 (30bb7a93c) and the Google BigQuery plugin v2.0.2

**Comment by ofir5300** [comment]
Please update to v2.0.3 (Available on [Grafana cloud](https://grafana.com/grafana/plugins/doitintl-bigquery-datasource/)) and let me know if it persist

**Comment by ofir5300** [comment]
We are retiring the [DoiT International BigQuery DataSource plugin](https://grafana.com/grafana/plugins/doitintl-bigquery-datasource/) for Grafana. We recommend that you migrate to the official [Google BigQuery data source](https://grafana.com/grafana/plugins/grafana-bigquery-datasource/) maintained by Grafana. In August 2022, we will cease all development and archive the GitHub project.

We are sorry for any inconvenience.
