### ISSUE TITLE
The following plugins are disabled and not shown in the list below: doitintl-bigquery-datasource

### ISSUE THREAD

**Issue by kevinsimper** [doitintl/bigquery-grafana#366]
I just tried installing the plugin and I get this error:

```
$ grafana-cli --pluginUrl https://github.com/doitintl/bigquery-grafana/archive/2.0.2.zip plugins install doitintl-bigquery-datasource
✔ Downloaded doitintl-bigquery-datasource v2.0.1 zip successfully

Please restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary.
```

![image](https://user-images.githubusercontent.com/1126497/129770377-4308f088-7777-49ea-baf7-0350887b5c6a.png)

```
Unsigned plugins were found during plugin initialization. Grafana Labs cannot guarantee the integrity of these plugins. We recommend only using signed plugins.

The following plugins are disabled and not shown in the list below:
doitintl-bigquery-datasource
Missing signature
 Read more about plugin signing
```

Using this to start grafana
```
  grafana:
    image: grafana/grafana:8.0.4
    ports:
      - "3000:3000"
```

and then docker exec into the container.

**Comment by ofir5300** [comment]
@kevinsimper  For some reason it seems like you downloaded version 2.0.1

Please try this and let me know if the issue still occurs:
1. Remove existing old version: `grafana-cli plugins remove doitintl-bigquery-datasource`
2. Installing latest version: `grafana-cli plugins install doitintl-bigquery-datasource`
