### ISSUE TITLE
Test rule in Alert tab' column type error

### ISSUE THREAD

**Issue by prcjsczllc** [doitintl/bigquery-grafana#367]
## Bug Report
Test rule in Alert tab fails due to column type error
## Expected Behavior
Rule is tested successfully
## Actual Behavior
`error:"request handler response error {unexpected type for field 'unique_success_rate': NUMERIC  A <nil> [] [] 0xc000c4a4e0}"
`## Steps to Reproduce the Problem

1. set up a query using raw sql successfully
2. be able to see the time series data in the dashboard
3. set up an alert using the config in the attachment
![Screen Shot 2021-08-24 at 8 47 29 AM](https://user-images.githubusercontent.com/3429951/130648544-90dcc73b-edb1-44fa-a2c1-3bbd72da2e84.png)
4. click on `test alert` button
5. fail and encounter this error
![Screen Shot 2021-08-24 at 8 52 08 AM](https://user-images.githubusercontent.com/3429951/130649081-3cf50a76-c21d-4906-8e21-7d49db8efa20.png)

## Specifications

- Version:
- Platform: grafana.net
- Grafana Version: 8.1.2

**Comment by kooinam-ridebeam** [comment]
Hi @prcjsczllc 
I have encountered similar error as yours
Would you mind sharing how do you resolve this issue?
