### ISSUE TITLE
Per-query Processing Locations are ignored

### ISSUE THREAD

**Issue by gaspo53** [doitintl/bigquery-grafana#368]
## Bug Report
per-query Processing location is ignored when having more than 1 query in a panel.

![image](https://user-images.githubusercontent.com/2250227/131914460-59603ff2-55ee-4ec9-a8c7-60fd2d861ccb.png)

## Expected Behavior
Each query should execute in the selected processing location

## Actual Behavior
All queries are executed in the processing location of the last query:

![image](https://user-images.githubusercontent.com/2250227/131914678-aeb62dd9-4607-4a02-a715-61b8b399cfe8.png)

## Steps to Reproduce the Problem

1. Create a query A to be processed in US
2. Create a query B to be processed in europe-west3
3. Execute and you'll see that query A is executing on europe-west3

## Specifications
- Grafana Version: 8 Cloud

**Comment by ofir5300** [comment]
Please update to v2.0.3 (Available on [Grafana cloud](https://grafana.com/grafana/plugins/doitintl-bigquery-datasource/)) and let me know if it persist

**Comment by ofir5300** [comment]
We are retiring the [DoiT International BigQuery DataSource plugin](https://grafana.com/grafana/plugins/doitintl-bigquery-datasource/) for Grafana. We recommend that you migrate to the official [Google BigQuery data source](https://grafana.com/grafana/plugins/grafana-bigquery-datasource/) maintained by Grafana. In August 2022, we will cease all development and archive the GitHub project.

We are sorry for any inconvenience.
