### ISSUE TITLE
invalidQuery: Unrecognized name: _PARTITIONTIME

### ISSUE THREAD

**Issue by JorritSalverda** [doitintl/bigquery-grafana#37]
## Bug Report

I have a partitioned table, for which the generated query uses pseudo column `_PARTITIONTIME`. However the pseudo column isn't available, probably because the table is partitioned on a specific field.

| Property | Value |
| --- | --- |
| Table type | Partitioned |
| Partitioned by | Day |
| Partitioned on field | EdgeStartTimestamp |
| Partition filter | Required |

The query generated by the graph I'm trying to construct looks like this

```sql
#standardSQL
SELECT
 $__timeGroupAlias(EdgeStartTimestamp,1h),
  EdgeRequestHost AS metric,
  count(CacheResponseStatus) AS CacheResponseStatus
FROM `***.cloudflare_logs.cloudflare_logs`
WHERE
  $__timeFilter(EdgeStartTimestamp) AND _PARTITIONTIME >= '2019-04-03 14:56:03' AND _PARTITIONTIME < '2019-04-10 14:56:03'
GROUP BY 1,2
ORDER BY 1,2
```

## Expected Behavior

The query to use the partition field `EdgeStartTimestamp` instead of pseudo column `_PARTITIONTIME`.

## Actual Behavior

The query returns following error:

```
invalidQuery: Unrecognized name: _PARTITIONTIME at [8:104]
```

## Specifications

Installed the plugin with `GF_INSTALL_PLUGINS=https://github.com/doitintl/bigquery-grafana/archive/0.3.0.zip;doitintl-bigquery-datasource`

  - Version: 0.3.0
  - Platform: Docker image grafana/grafana:6.1.3
  - Grafana Version: 6.1.3

**Comment by JorritSalverda** [comment]
See https://cloud.google.com/bigquery/docs/partitioned-tables for info on ways of partitioning tables.

**Comment by JorritSalverda** [comment]
I can get it to work by removing the `_PARTITIONTIME` column from the generated query where clause.

**Comment by spark2ignite** [comment]
@avivl I think this is a valid request made by @JorritSalverda. The Tables: get method provides the partition the `timePartitioning.field` [1] which (if set) the table partitioned by this field and not by `_PARTITIONTIME`

[1] https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#resource

**Comment by avivl** [comment]
@JorritSalverda Thanks for reporting this!
@spark2ignite I'm on vacation. It will be ready for the next milestone 0.4.0
