### ISSUE TITLE
$__timeGroup does not expand in subqueries

### ISSUE THREAD

**Issue by ptomasroos** [doitintl/bigquery-grafana#371]
When the macro $__timeGroup is inserted into a raw sql query, its not expanded when its placed inside a subquery. I would expect the timeGroup to be resolved / replaced anywhere in the query not just the outer query.

## Bug Report

```
#standardSQL
SELECT
  `time`,
  group
FROM (
SELECT
    $__timeGroup(timestamp, auto),
    group
  FROM
    `***`)
```
## Expected Behavior

I expect the $_timeGroup to expand into the regular expression of TIMESTAMP_SECONDS(DIV(UNIX_SECONDS(`timestamp`), x) * x) AS time,

## Actual Behavior

Its not expanded and query fails.

## Steps to Reproduce the Problem

1. Take a regular query with a raw sql $__timeGroup(timestamp, auto)
2. Put it inside a sub query and just wrap that query into a subquery

## Specifications

- Version:2.0.2
- Platform: *nix
- Grafana Version: 7.4.3

**Comment by ofir5300** [comment]
Please update to v2.0.3 (Available on [Grafana cloud](https://grafana.com/grafana/plugins/doitintl-bigquery-datasource/)) and let me know if it persist

**Comment by ofir5300** [comment]
We are retiring the [DoiT International BigQuery DataSource plugin](https://grafana.com/grafana/plugins/doitintl-bigquery-datasource/) for Grafana. We recommend that you migrate to the official [Google BigQuery data source](https://grafana.com/grafana/plugins/grafana-bigquery-datasource/) maintained by Grafana. In August 2022, we will cease all development and archive the GitHub project.

We are sorry for any inconvenience.
