### ISSUE TITLE
Add europe-west1 to list of processing regions

### ISSUE THREAD

**Issue by albrechtflo-hg** [doitintl/bigquery-grafana#374]
See title. 

BTW, you can query Google for the available regions. See https://cloud.google.com/compute/docs/regions-zones/viewing-regions-zones#viewing_a_list_of_available_regions

Yes, the service account needs `compute.regions.list` permission for that. But you could e.g. still use your list as a fallback if the service account is lacking that permission.

**Comment by ofir5300** [comment]
https://github.com/doitintl/bigquery-grafana/blob/8dc0fdc6d8f26fd00ac54290c7de283e80ba2ec0/src/config_ctrl.ts#L66-L67
