### ISSUE TITLE
Support the `BIGNUMERIC` column type

### ISSUE THREAD

**Issue by clementprevot** [doitintl/bigquery-grafana#377]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I recently stumble upon an issue when using a Big Query table to display a time serie.
I used `BIGNUMERIC` type column to store a file size that I wanted to graph. But I wasn't able to select this column (it wasn't even available in the "Column" field in the query builder).
When constructing the query manually, nothing was displayed. Using the query inspector show the query went fine but nothing was displayed.

Changing the column type to `INTEGER` make the query (and query builder) work fine and the data being displayed.

**Describe the solution you'd like**
Ideally we should be able to select `BIGNUMERIC` columns as if they were `INTEGER`.

**Comment by dprokop** [comment]
@clementprevot just a friendly heads up that this is now supported by official Grafana BigQuery plugin: https://github.com/grafana/google-bigquery-datasource/blob/main/CHANGELOG.md#0115

**Comment by clementprevot** [comment]
Thanks for letting me know, that's great!
