### ISSUE TITLE
Invalid Project ID Error in Query Inspector

### ISSUE THREAD

**Issue by sarahb511** [doitintl/bigquery-grafana#378]
## Bug Report
When using the Query Inspector, we are getting an error saying "Invalid project ID '%60' as pictured here:
![image](https://user-images.githubusercontent.com/51332153/136433443-33a3e7c6-1741-48ff-ba4a-fff29da6f192.png)

As you can see in the url for the GET request, there is a backtick (`). The URL encoding for a backtick is %60. Could the issue be something to do with that? Is there any way that we can resolve this?

We are able to get the data from BigQuery to a table. This is only occurring in the Query Inspector.

## Specifications

- Version: 2.0.1
- Platform: Self Hosted
- Grafana Version: 8.1.2

**Comment by ofir5300** [comment]
Please update to v2.0.3 (Available on [Grafana cloud](https://grafana.com/grafana/plugins/doitintl-bigquery-datasource/)) and let me know if it persist
