### ISSUE TITLE
Support BQ queries in variables

### ISSUE THREAD

**Issue by JorritSalverda** [doitintl/bigquery-grafana#38]
## Feature Request

**Is your feature request related to a problem? Please describe.**

I'd like to be able to get all values for a column in my BQ table (at least within the selected time range) and use that variable in the where clause of my graphs. Supporting all values or multi-select is a bonus.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

A variable based on Prometheus allows the following query for example:
```
label_values(timeline_serie_name,label_name)
```

Either having a special function like `$__timeFilter` to do a similar thing or be able to specify a full query would be nice.

**Describe alternatives you've considered**

If I use a query at this moment I get a `Template variables could not be initialized: e.metricFindQuery is not a function` error.

**Comment by spark2ignite** [comment]
Thanks for requesting this, @JorritSalverda. We will review this request early next week.

**Comment by ptomasroos** [comment]
Bumped into this as well! :-) Would be a great addition

**Comment by LukeDefeo** [comment]
this would be amazing to do something like `SELECT distinct topioc FROM `mytable` as to populate the values for my label

**Comment by ptomasroos** [comment]
🎉
