### ISSUE TITLE
bigquery datasource create alert occuring error

### ISSUE THREAD

**Issue by blackmidnight** [doitintl/bigquery-grafana#380]
## Bug Report
When create alert rule using bigquery datasource, after create  a query to be alerted on, then run query, a pop-up error message is displayed, as follows:
Failed to evaluate queries and expressions: failed to execute conditions: failed to execute query A: expected 'query.Location' or 'req.PluginContext.DataSourceInstanceSettings.JSONData.processingLocation' to be set

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version: v2.0.2
- Platform: macos 10.15.7
- Grafana Version: v8.2.0
![WechatIMG305](https://user-images.githubusercontent.com/29446499/136650232-723189db-58a5-4ae6-aa1c-36052de52d0e.png)

**Comment by blackmidnight** [comment]
![image](https://user-images.githubusercontent.com/29446499/136722753-dc36e54c-c47c-4b41-b72d-aa627d6d1d11.png)

**Comment by blackmidnight** [comment]
> Hi @blackmidnight, is this the same output you getting when trying to `test rule` as well?
It is normal on the query tab page, as shown in the figure below, there is a problem in the alert as the above error
![image](https://user-images.githubusercontent.com/29446499/138021938-1951cc18-8cb5-42ce-a150-79e86e6ce691.png)

I don’t know if the test rule you mentioned refers to preview alerts, but the same error is reported when trying to preview alerts
![image](https://user-images.githubusercontent.com/29446499/138021982-0ca0df67-7457-4a98-be15-1e0eea71d72f.png)

**Comment by ofir5300** [comment]
@blackmidnight Please set location on the query tab (as I can see `processing location` is empty in your first image) and try again.

**Comment by blackmidnight** [comment]
@ofir5300 Hi, is there any workaround for this problem

**Comment by ofir5300** [comment]
We are retiring the [DoiT International BigQuery DataSource plugin](https://grafana.com/grafana/plugins/doitintl-bigquery-datasource/) for Grafana. We recommend that you migrate to the official [Google BigQuery data source](https://grafana.com/grafana/plugins/grafana-bigquery-datasource/) maintained by Grafana. In August 2022, we will cease all development and archive the GitHub project.

We are sorry for any inconvenience.
