### ISSUE TITLE
Illegal input character "$" when trying to set up alerts

### ISSUE THREAD

**Issue by darist** [doitintl/bigquery-grafana#386]
## Bug Report
Looks like macros like $__timeFilter() are not being interpolated when the query is processed for alerts.

I have cycles to contribute a fix for this if someone else isn't already working on it. If you happen to know where the problem occurs or can point me to the code that handles queries for alerts, I'd be happy to give it a shot.

## Expected Behavior
Query string should be processed with same interpolation capabilities when used for alerts as when used for UI panel.

## Actual Behavior
Given a query that uses `$__timeFilter(timestamp)`, and works as expected for displaying the results on a panel, when I try to set up an alert and click the "Test rule" button, I get this error

```
error:"tsdb.HandleRequest() response error &{googleapi: Error 400: Syntax error: Illegal input character "$" at [6:3], invalidQuery googleapi: Error 400: Syntax error: Illegal input character "$" at [6:3], invalidQuery A <nil> [] [] 0xc001185e30}"
```

## Steps to Reproduce the Problem

1. Create a query using $__timeFilter()
1. Get it to work as expected to show a graph on a panel.
1. Create a new alert. Set a threshold value. Other options can stay with default values.
1. Click "test rule"

## Specifications

- ~~Version: 2.0.3 "prerelease" (Nov 22, 2021), commit: a988ba0~~
- Version: 2.0.3 "pre-release" on Nov 22, 2021 - latest change dist folder was  370b61a
- Platform: Docker (on linux)
- Grafana Version: 7.4.5

**Comment by darist** [comment]
Further investigation: if I build the linux binary (doitintl-bigquery-datasource_linux_amd64) from source in master, I don't see this problem. I wonder if the binary in the dist dir is old (both in master and the download zip in the 2.0.3 prerelease).

Can you point me to how the releases are built? I would like to try follow the same process on my end. Thanks!

**Comment by ofir5300** [comment]
Hi @darist. This issue has already been solved https://github.com/doitintl/bigquery-grafana/issues/361.
In order to use v2.0.3 pre-release please run
```
grafana-cli --pluginUrl https://github.com/doitintl/bigquery-grafana/releases/download/2.0.3/doitintl-bigquery-datasource-2.0.3.zip plugins install doitintl-bigquery-datasource
```

**Comment by darist** [comment]
Thanks, @ofir5300. I've run the plugin by installing it from the release/download zip and by just copying the dist dir. In both cases I can still see the issue on linux.

However, when I build the linux binary myself, I can see that the issue is resolved.

It looks to me like the linux binary in the 2.0.3 pre-release zip is not up to date.

I can be unblocked by using a locally build binary, but would like to at least build it the same way that you build your releases. Here's what I'm doing:

```
$ docker run --rm -v "$PWD":/usr/src/workspace -w /usr/src/workspace golang:1.17 go build -o dist/doitintl-bigquery-datasource_linux_amd64 -v ./pkg
```

Note: when I build directly with my local go installation (instead of using the golang docker container above) results in the wrong glibc.

How do you build the binaries?

**Comment by ofir5300** [comment]
Im using `go build`

**Comment by ofir5300** [comment]
@darist Did you try to test it using `go build`?

Also I understand that you didnt try to use `grafana-cli` as I suggested according to this quote, is that correct?

> I've run the plugin by installing it from the release/download zip and by just copying the dist dir. In both cases I can still see the issue on linux.

I just want to completely understand the issue before starting to re-build binaries and replacing the zip file on https://github.com/doitintl/bigquery-grafana/releases/download/2.0.3/doitintl-bigquery-datasource-2.0.3.zip

**Comment by ofir5300** [comment]
v2.0.3 is on Grafana cloud https://grafana.com/grafana/plugins/doitintl-bigquery-datasource/

**Comment by darist** [comment]
Hi @ofir5300, sorry I missed your message from Dec 5. I had tried both ways: 1. using the grafana-cli, and 2. copying the dist dir to the grafana plugins dir. I have not tried again since then. Did you end up re-building the zip?
