### ISSUE TITLE
Broken link to forum in CONTRIBUTING.md

### ISSUE THREAD

**Issue by darist** [doitintl/bigquery-grafana#387]
The link in:

"Please check [the forum](https://feedback.doit-intl.com/forums/933776-grafana-bigquery-plugin)"  takes me to a page with this text:

Record not found
We could not find the record you requested because either:

The record was deleted
You don't have permission to see the record
Return home or contact us

**Comment by ofir5300** [comment]
Tnx @darist.
If you have any feature request/suggestion - please create an issue on GitHub.
