### ISSUE TITLE
Create new buid please

### ISSUE THREAD

**Issue by JonasJacobsUserspace** [doitintl/bigquery-grafana#389]

**Comment by ofir5300** [comment]
@JonasJacobsUserspace Can you be more specific/provide explanation?

**Comment by JonasJacobsUserspace** [comment]
Thanks for your answer, it has been since April 4 ago that a release was made, since then some extra really needed features are implemented, such as new locations, which are essential to our operations. So when will there be a new release?

**Comment by bacheson** [comment]
+1

**Comment by ofir5300** [comment]
So there is an updated version (v2.0.3) which is useable by now.
I made a submission to Grafana labs 1 month ago and its currently pending their approval to become available on [Grafana Labs](https://grafana.com/grafana/plugins/doitintl-bigquery-datasource/).

Anyway, you can already install v2.0.3 using grafana cli:
```
grafana-cli --pluginUrl https://github.com/doitintl/bigquery-grafana/releases/download/2.0.3/doitintl-bigquery-datasource-2.0.3.zip plugins install doitintl-bigquery-datasource
```

**Comment by bacheson** [comment]
@ofir5300 I just contacted grafana cloud...they have responded to your submission already asking you to fix several warnings

I'm on gragana cloud and can't manually install this version

**Comment by ofir5300** [comment]
v2.0.3 is on grafana cloud https://grafana.com/grafana/plugins/doitintl-bigquery-datasource/
