### ISSUE TITLE
Respond to Grafana Review of 2.0.3

### ISSUE THREAD

**Issue by bacheson** [doitintl/bigquery-grafana#390]
Grafana has rejected your submission asking for several warnings to be fixed

**Comment by ofir5300** [comment]
Just letting you know that Grafana gave me no indication about such rejection. Im checking on it now.
Tnx for being involved.

**Comment by yuppii1** [comment]
![image](https://user-images.githubusercontent.com/51068787/147720956-c9d847aa-8fb5-474a-bdd2-d2a5ea93bad1.png)
with 2.0.3 Im facing issues when installed.

**Comment by yuppii1** [comment]
Grafana plugin 2.0.3 gives an error when loading on Safari. others work fine.
![Screen Shot 2022-01-06 at 2 24 33 PM](https://user-images.githubusercontent.com/51068787/148333093-f924f786-4800-40a6-9c09-abfa40bc5279.png)

**Comment by ofir5300** [comment]
@yuppii1 Will check on this. Tnx

**Comment by ofir5300** [comment]
@bacheson v2.0.3 is on Grafana cloud https://grafana.com/grafana/plugins/doitintl-bigquery-datasource/
