### ISSUE TITLE
$__timeFilter not being expanded in Grafana 8 alert rules

### ISSUE THREAD

**Issue by joelsdc** [doitintl/bigquery-grafana#391]
## Bug Report

When testing new Grafana 8 alert rules, using `$__timeFilter()` results in this error:

```
Failed to evaluate queries and expressions: failed to execute conditions: failed to execute query A: googleapi: Error 400: Syntax error: Illegal input character "$" at [6:3], invalidQuery
```

I don't seem to see the **query inspector** available so I can't really see what Grafana is sending but this is the query I'm using:

```
SELECT
  CURRENT_TIMESTAMP() as time,
  COUNT(column2) AS records
FROM `table`
WHERE
  $__timeFilter(column1) AND
  column2 = "something" AND
  column3 IN ('one', 'two', 'three')
```

## Expected Behavior

`$__timeFilter()` should be expanded to the appropriate time range.

For example:

$__timeFilter(column1) -> column1 BETWEEN '2017-04-21T05:01:17Z' AND '2017-04-21T05:01:17Z'

## Actual Behavior

Grafana shows an error that indicates that a 400 was returned by the Google BigQuery API, apparently the `$` being the cause.

## Steps to Reproduce the Problem

1. Install Grafana 8 (tested on v8.3.3).
2. Go to Alerting / +New alert rule.
3. Use `$__timeFilter()` in your alert query.

## Specifications

- Version: 2.0.3
- Platform:  GKE
- Grafana Version: 8.3.3

**Comment by ofir5300** [comment]
We are retiring the [DoiT International BigQuery DataSource plugin](https://grafana.com/grafana/plugins/doitintl-bigquery-datasource/) for Grafana. We recommend that you migrate to the official [Google BigQuery data source](https://grafana.com/grafana/plugins/grafana-bigquery-datasource/) maintained by Grafana. In August 2022, we will cease all development and archive the GitHub project.

We are sorry for any inconvenience.
