### ISSUE TITLE
Can I use this plugin to populate both text and value pairs of a Grafana variable for later graph scope selection?

### ISSUE THREAD

**Issue by GeoffMurray-chc** [doitintl/bigquery-grafana#394]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I'm trying to use a BigQuery table with has, let's say, both customer names, and customer IDs. The customer ID can be used to filter other Stackdriver related information, but I want the user to be able to select the human readable name, whereas the data stored in Stackdriver is really the customer ID.

**Describe the solution you'd like**
I'm trying to understand if there is a combination of BigQuery selection queries, along with whatever other Grafana settings are required to help Grafana understand the returned information better. 

**Describe alternatives you've considered**
The only way I've gotten this to work in the past is to hardcode the customer list in the Grafana dashboard JSON structure itself. Not ideal as customers change. 

**Teachability, Documentation, Adoption, Migration Strategy**
Not really sure - just looking for some advice, or maybe information that I'm barking up the wrong tree, so I don't keep trying. I've tried many combinations of things.

**Comment by Elyahou** [comment]
I also tried to add variable with different label and value with this plugin, but I think it is not supported... 

It will be good if it can be added to this plugin, like it exists in other SQL plugins: Generally, it work by specifying in the query two values for `__text`, and `__value`:

```
SELECT hostname AS __text, id AS __value FROM my_host
```

**Comment by ofir5300** [comment]
We are retiring the [DoiT International BigQuery DataSource plugin](https://grafana.com/grafana/plugins/doitintl-bigquery-datasource/) for Grafana. We recommend that you migrate to the official [Google BigQuery data source](https://grafana.com/grafana/plugins/grafana-bigquery-datasource/) maintained by Grafana. In August 2022, we will cease all development and archive the GitHub project.

We are sorry for any inconvenience.
