### ISSUE TITLE
GF_INSTALL_PLUGINS with docker image

### ISSUE THREAD

**Issue by zorel** [doitintl/bigquery-grafana#396]
## Bug Report
When using the GF_INSTALL_PLUGINS with the 7.4 docker image:

installing doitintl-bigquery-datasource @ 1.0.3
from: https://grafana.com/api/plugins/doitintl-bigquery-datasource/versions/1.0.3/download

## Expected Behavior
Install the last 2.0.3 available.

## Actual Behavior
Install the 1.0.3

I've tried to specify the version in the environment variable or the /download path, but it fails with a  404.

**Comment by zorel** [comment]
Hey, looks like it's solved. Could you tell me what happened? 

Anyway, thanks solving it.

**Comment by ofir5300** [comment]
Do you manage to have v2.0.3 now?

**Comment by zorel** [comment]
Yes it's working fine.
