### ISSUE TITLE
Alerting Queries only support raw SQL

### ISSUE THREAD

**Issue by dennis-tra** [doitintl/bigquery-grafana#398]
## Bug Report

I have the following query:

![PLI__prod__-_Grafana](https://user-images.githubusercontent.com/11836793/153833469-31e786d2-f79b-4a2f-bfe1-e100591b71aa.png)

And the following alert:

![PLI__prod__-_Grafana](https://user-images.githubusercontent.com/11836793/153833665-dcc7d4c5-23b8-4296-be2c-7df381a09025.png)

When clicking on `Test Alert` I receive the following error:

![PLI__prod__-_Grafana](https://user-images.githubusercontent.com/11836793/153833992-ce82f737-8897-46ef-a852-b46114e9afae.png)

## Expected Behavior

There is no error.

## Actual Behavior

There is the error message:

```
request handler response error {alerting queries only support raw sql  A <nil> [] [] 0xc002345110}
```

## Steps to Reproduce the Problem

See above.

## Specifications

- Version: 2.0.3
- Platform: ?
- Grafana Version: 8.3.3

--- 

A related but already closed issue https://github.com/doitintl/bigquery-grafana/issues/367

**Comment by ofir5300** [comment]
Hi @dennis-tra 
like mentioned in the given error - alert feature only available when using raw sql.
Please toggle to raw sql mode, generate a query equivalent to the one you have created using the sql builder and try to test your alert once again.

**Comment by jakubdziecielski** [comment]
Hi!
I have similar issue as the author despite using raw sql. When using `Test rule` sometimes I receive an error about raw sql support and sometimes I don't, meaning alert condition evaluates correctly. From alerting tab I can always see an error as on attached screenshot.

Version: 2.0.2

![Alert](https://user-images.githubusercontent.com/68186344/156591835-f4c29b11-add0-417d-af65-b7a96b908c3d.png)

**Comment by tommy071306** [comment]
> ## Bug Report
> 
> 
> 
> I have the following query:
> 
> 
> 
> ![PLI__prod__-_Grafana](https://user-images.githubusercontent.com/11836793/153833469-31e786d2-f79b-4a2f-bfe1-e100591b71aa.png)
> 
> 
> 
> And the following alert:
> 
> 
> 
> ![PLI__prod__-_Grafana](https://user-images.githubusercontent.com/11836793/153833665-dcc7d4c5-23b8-4296-be2c-7df381a09025.png)
> 
> 
> 
> When clicking on `Test Alert` I receive the following error:
> 
> 
> 
> ![PLI__prod__-_Grafana](https://user-images.githubusercontent.com/11836793/153833992-ce82f737-8897-46ef-a852-b46114e9afae.png)
> 
> 
> 
> 
> 
> ## Expected Behavior
> 
> 
> 
> There is no error.
> 
> 
> 
> ## Actual Behavior
> 
> 
> 
> There is the error message:
> 
> 
> 
> ```
> 
> request handler response error {alerting queries only support raw sql  A <nil> [] [] 0xc002345110}
> 
> ```
> 
> 
> 
> ## Steps to Reproduce the Problem
> 
> 
> 
> See above.
> 
> 
> 
> ## Specifications
> 
> 
> 
> - Version: 2.0.3
> 
> - Platform: ?
> 
> - Grafana Version: 8.3.3
> 
> 
> 
> 
> 
> --- 
> 
> 
> 
> A related but already closed issue https://github.com/doitintl/bigquery-grafana/issues/367

- [ ] @jakubdziecielski @ofir5300 @jakubdziecielski @

**Comment by ofir5300** [comment]
We are retiring the [DoiT International BigQuery DataSource plugin](https://grafana.com/grafana/plugins/doitintl-bigquery-datasource/) for Grafana. We recommend that you migrate to the official [Google BigQuery data source](https://grafana.com/grafana/plugins/grafana-bigquery-datasource/) maintained by Grafana. In August 2022, we will cease all development and archive the GitHub project.

We are sorry for any inconvenience.
