### ISSUE TITLE
Convert time filters to UTC does not work in Grafana 8

### ISSUE THREAD

**Issue by jayhding** [doitintl/bigquery-grafana#399]
Apologies if this bug should be reported to Grafana community instead.

## Bug Report
After upgraded our Grafana from 7 to 8.3.6 we found the dashboard using BQ datasource does not work well.
Upon checking looks like it is related to timer convert feature in this plugin.

Dashboard setting is like below
<img width="835" alt="image" src="https://user-images.githubusercontent.com/15888241/154391860-3cab34e1-c70f-4b23-b90f-1dde699253bf.png">

## Expected Behavior
Like in Grafana 7, below request should be sent

```
[request:Object]()
[data:Object]()
[location:"australia-southeast1"]()
[query:"select count(*) as Count, to_email_address as Email,
from <proj_name>\.xxxx_monitor.xxxx_bounces
where `timestamp` BETWEEN '2022-02-15 02:16:49' AND '2022-02-17 02:16:49'
group by to_email_address
order by Count DESC
LIMIT 20"]()
```

## Actual Behavior
Query inspection shows following request was sent to BQ

```
[Object]()
[request:Object]()
[data:Object]()
[location:"australia-southeast1"]()
[query:"select count(*) as Count, to_email_address as Email,
from <proj_name>\.xxxx_monitor.xxxx_bounces
where `datetime` BETWEEN TIMESTAMP_MILLIS (1644851604318) AND TIMESTAMP_MILLIS (1645024404318)
group by to_email_address
order by Count DESC
LIMIT 20"]()
```

## Specifications
- Version: 2.0.3/2.0.0
- Grafana Version: 8.3.6

**Comment by jayhding** [comment]
okay turned out the reason was because value of `timeColumn` cannot be changed when use SQL code as text edit mode. By default it is set as `-- time --` but the actual column name in our table is `timestamp`.

After I changed the `timeColumn` in JSON Model directly the query started to work again.

**Comment by ofir5300** [comment]
We are retiring the [DoiT International BigQuery DataSource plugin](https://grafana.com/grafana/plugins/doitintl-bigquery-datasource/) for Grafana. We recommend that you migrate to the official [Google BigQuery data source](https://grafana.com/grafana/plugins/grafana-bigquery-datasource/) maintained by Grafana. In August 2022, we will cease all development and archive the GitHub project.

We are sorry for any inconvenience.
