### ISSUE TITLE
Adding installation instructions for helm/k8s users

### ISSUE THREAD

**Issue by DaveTaboola** [doitintl/bigquery-grafana#4]
## Feature Request

**The problem**
People who choose kubernetes as the hosting platform of grafana and are using helm needs to define how the plugin will be installed, and as it's not part of the authorised plugins (yet) some adjustments needs to be done.
We/You should add that to the documentation part of the README so people would know :)

**How to **
Well thats the easy part in the official grafana helm chart, you can find the values file which specifies the plugins to be installed, instead of writting doit-bigquery-datasource, you'll need to specify the repo zip file:

> https://github.com/doitintl/bigquery-grafana/archive/master.zip;doit-bigquery-datasource

**Note**
This is relevant only until the grafana team will recognise the datasource officially, than specifying the name would be more than enough

**Comment by avivl** [comment]
@eranchetz would you mind helping on this?
