### ISSUE TITLE
Support Macro for variable query

### ISSUE THREAD

**Issue by Elyahou** [doitintl/bigquery-grafana#401]
## Feature Request

When defining a variable using query, the macros like `$__timeFilter` are not supported and return this error:
`Illegal input character "$"`

**Describe the solution you'd like**
Ability to use macros in variables as well

**Teachability, Documentation, Adoption, Migration Strategy**

When added, the documentation should be something like:

> To use time range dependent macros like $__timeFilter(column) in your query the refresh mode of the template variable needs to be set to On Time Range Change.
> ```
> SELECT event_name FROM event_log WHERE $__timeFilter(time_column)
> ```

**Comment by pedrounes1** [comment]
First, you need to set `time_column` into SELECT statement, as 
```
SELECT time_column as time, event name FROM event_log WHERE $__timeFilter(time_column).
```
But only this will not solve your issue. As a workaround, at least at this moment, you can use `$__from` and `$__to` beside `$__timefilter` as below:

```
SELECT time_field as time, event_name FROM event_log WHERE time_field between TIMESTAMP_MILLIS(${__from}) and TIMESTAMP_MILLIS(${__to})
```
More info about `$__from` and `$__to` on [grafana docs](https://grafana.com/docs/grafana/latest/variables/variable-types/global-variables/)

**Comment by ofir5300** [comment]
We are retiring the [DoiT International BigQuery DataSource plugin](https://grafana.com/grafana/plugins/doitintl-bigquery-datasource/) for Grafana. We recommend that you migrate to the official [Google BigQuery data source](https://grafana.com/grafana/plugins/grafana-bigquery-datasource/) maintained by Grafana. In August 2022, we will cease all development and archive the GitHub project.

We are sorry for any inconvenience.
