### ISSUE TITLE
Metric name in alerts is aways 'response'

### ISSUE THREAD

**Issue by pedrounes1** [doitintl/bigquery-grafana#403]
## Bug Report
Greetings!

I have an alert that do multiple queries on BigQuery and then is evaluated by a expression to send notification or not. Everything is working fine, but all metric name that I get into notification is called "response", thus, I cannot identify the origin of value.

![image](https://user-images.githubusercontent.com/11378696/157345001-72a4b03a-eaf5-48ed-9c70-3fe89142c30d.png)

I tried to change query name and column name, without success.

## Expected Behavior

Change metric name to query name  or column name. Thus, the return will be:
```
 [ metric='Query_A' labels={} value=0.91 ], [ metric='Query_B' labels={} value=0.89 ]
```

## Actual Behavior
 [ metric='response' labels={} value=0.91 ], [ metric='response' labels={} value=0.89 ]

## Steps to Reproduce the Problem

1.
2.
3.

## Specifications

- Version: 2.0.2
- Platform: Windows
- Grafana Version: 8.4.1

**Comment by ofir5300** [comment]
Hi @pedrounes1
First please update to version 2.0.3 to and check if the issues persists

**Comment by ofir5300** [comment]
Ok thanks for letting me know

**Comment by ofir5300** [comment]
We are retiring the [DoiT International BigQuery DataSource plugin](https://grafana.com/grafana/plugins/doitintl-bigquery-datasource/) for Grafana. We recommend that you migrate to the official [Google BigQuery data source](https://grafana.com/grafana/plugins/grafana-bigquery-datasource/) maintained by Grafana. In August 2022, we will cease all development and archive the GitHub project.

We are sorry for any inconvenience.
