### ISSUE TITLE
Support maximum bytes billed per query option

### ISSUE THREAD

**Issue by Jsturgeo** [doitintl/bigquery-grafana#406]
## Feature Request

**Is your feature request related to a problem? Please describe.**
We want to be able to control costs related to using a pay-per-data-scan project as a backend for Grafana. Costs can expand rapidly when a query that scans more data than expect is running on an auto-refreshing dashboard. 

**Describe the solution you'd like**
It would be nice to be able to set the maximum bytes billed per query when configuring the data source. https://cloud.google.com/bigquery/docs/best-practices-costs#limit_query_costs_by_restricting_the_number_of_bytes_billed

**Describe alternatives you've considered**
Unfortunately, BigQuery does not allow for limiting data scan per query to a project or service account specifically, so this needs to be done at the query level. 
It's possible to limit the total amount of data scanned, but this is not exactly the functionality we're looking for. We want to avoid cases where folks are trying to visualize a _lot_ of data in Grafana, especially where this data is auto-refreshing.

**Teachability, Documentation, Adoption, Migration Strategy**
I imagine this will be easiest to add as an option when configuring a BigQuery data source. Perhaps a text box for Maximum bytes billed per query that will be included in the BQ API call if specified.
<img width="1211" alt="Screen Shot 2022-03-28 at 9 47 58 AM" src="https://user-images.githubusercontent.com/15231536/160449789-0d5395e4-71d9-4590-8261-ff812b44938f.png">

**Comment by ofir5300** [comment]
We are retiring the [DoiT International BigQuery DataSource plugin](https://grafana.com/grafana/plugins/doitintl-bigquery-datasource/) for Grafana. We recommend that you migrate to the official [Google BigQuery data source](https://grafana.com/grafana/plugins/grafana-bigquery-datasource/) maintained by Grafana. In August 2022, we will cease all development and archive the GitHub project.

We are sorry for any inconvenience.
