### ISSUE TITLE
Issue with Google BigQuery datasource

### ISSUE THREAD

**Issue by GMoraesGarcia** [doitintl/bigquery-grafana#414]
Environment:

Grafana version: 9.0.1
OS Grafana is installed on: CentOS 7
Grafana plugins: Google BigQuery
doitintl-bigquery-datasource @ 2.0.3
Im having a problem with Google BigQuery datasource.

I made backup from this datasource, but when i restored, the connection didnt work, when i do a new connection with exacly the same JSON its works.

I try three differents ways:

1 - Using sqlite dump file
2 - With a backup tool, to save all configurations files (datasources and dashboards), this tool use Grafana API
3 - Simple copy from grafana.db and rewriting original grafana.db

All this ways works to restore, but with this Google BigQuery problem

**Comment by ofir5300** [comment]
Hi @GMoraesGarcia, unfortunately we are no longer maintaining this plugin:
https://docs.google.com/spreadsheets/d/1Y66augVRxfQWNgHy2QmxMjiL23rU3tzQxyOq1JqnKas/edit#gid=2119328863

**Comment by ofir5300** [comment]
Hi @GMoraesGarcia, unfortunately we are no longer maintaining this plugin:


https://github.com/doitintl/bigquery-grafana#we-have-retired-the-doit-international-bigquery-datasource-plugin-for-grafana-ceased-all-development-and-put-maintenance-on-indefinite-hold-we-recommend-you-migrate-to-the-official-google-bigquery-data-source-maintained-by-grafana
