### ISSUE TITLE
Support time shift per query

### ISSUE THREAD

**Issue by JorritSalverda** [doitintl/bigquery-grafana#58]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I want to be able to compare data from the current range to the previous range. Let's say I'm looking at the last month and I want to compare with the previous month.

Unfortunately Grafana doesn't allow to set a timeshift per query, only for a full panel. See https://github.com/grafana/grafana/issues/2093. They bounce you to the provider plugin for support.

**Describe the solution you'd like**

In the query builder to have a field for timeshift so I can set multiple queries with different time shift.

**Describe alternatives you've considered**

Handling this in the raw query; unfortunately the built in global variables like `$__timeFilter` don't seem to have any easy way to shift time, see https://grafana.com/docs/reference/templating/.

**Teachability, Documentation, Adoption, Migration Strategy**

In order to compare you graph to the previous period duplicate your query in a graph and shift it's time by `1h`, `1d` or `1w`; apply some additional styling - like dashes - to your shifted query graph so it's easy to keep it apart from the current values.

**Comment by avivl** [comment]
@JorritSalverda code is ready in the master branch.

**Comment by JorritSalverda** [comment]
Cool stuff. To test it in Grafana in a Docker container I guess I have to build the zip file, host it somewhere and reference it in the `GF_INSTALL_PLUGINS` envar? Or do you push nightlies somewhere?

**Comment by avivl** [comment]
You can close the repo to your plugin directory

**Comment by JorritSalverda** [comment]
Although the query issues to BQ is correct, it seems that the data returned still has to be 'shifted back' a similar amount of time so you can show the graph in the same time range as selected.

In the graph below I've selected the last 30 days and also added an extra query with a timeshift of 30 days. I would expect it to be showing the last 30 days with the -30d graph within that time range:

![grafana-bigquery-timeshift](https://user-images.githubusercontent.com/136472/58258005-3cb8d280-7d72-11e9-8b2a-a09c2484c2bc.png)

**Comment by avivl** [comment]
Can you share the original and shifter queries? You can find them in the console log

**Comment by JorritSalverda** [comment]
The original query is configured as

```sql
#standardSQL
SELECT
 $__timeGroupAlias(usage_start_time,1d),
  'Net' AS metric,
  sum(cost) + coalesce(sum((select sum(amount) from unnest(credits))),0) as cost
FROM `***.gce_billing.gcp_billing_export_v1_***`
WHERE
  $__timeFilter(usage_start_time)
GROUP BY 1,2
ORDER BY 1,2
```

And translated into the following when sent to BQ:

```sql
#standardSQL
SELECT
 TIMESTAMP_SECONDS(DIV(UNIX_SECONDS(usage_start_time), 86400) * 86400),
  'Net' AS metric,
  sum(cost) + coalesce(sum((select sum(amount) from unnest(credits))),0) as cost
FROM `***.gce_billing.gcp_billing_export_v1_***`
WHERE
  usage_start_time BETWEEN TIMESTAMP_MILLIS (1556440109760) AND TIMESTAMP_MILLIS (1559032109761)
GROUP BY 1,2
ORDER BY 1,2 LIMIT 1659
```

The shifted query looks like:

```sql
#standardSQL
SELECT
 $__timeGroupAlias(usage_start_time,1d),
  'Net shifted' AS metric,
  sum(cost) + coalesce(sum((select sum(amount) from unnest(credits))),0) as cost
FROM `***.gce_billing.gcp_billing_export_v1_***`
WHERE
  $__timeFilter(usage_start_time)
GROUP BY 1,2
ORDER BY 1,2
v
```

And turns into:

```sql
#standardSQL
SELECT
 TIMESTAMP_SECONDS(DIV(UNIX_SECONDS(usage_start_time), 86400) * 86400),
  'Net shifted' AS metric,
  sum(cost) + coalesce(sum((select sum(amount) from unnest(credits))),0) as cost
FROM `***.gce_billing.gcp_billing_export_v1_***`
WHERE
  usage_start_time BETWEEN TIMESTAMP_MILLIS (1553851671435) AND TIMESTAMP_MILLIS (1556440071435)
GROUP BY 1,2
ORDER BY 1,2
 LIMIT 1659
```

I couldn't figure out from code and help file where to put the `$__timeShifting(30d)` function so I just added it at the end. Perhaps that's what causes the incorrect behaviour?

**Comment by avivl** [comment]
Did you try to use the UI for adding the time shift?
![Grafana_BigQuery_Demo_-_Grafana](https://user-images.githubusercontent.com/3265061/58613058-3e781e00-82bd-11e9-89cc-0a07f7633709.png)

**Comment by avivl** [comment]
Did you try to use the UI for shifting  time?
![Grafana_BigQuery_Demo_-_Grafana](https://user-images.githubusercontent.com/3265061/58613094-5d76b000-82bd-11e9-810f-c8cf7b864fa2.png)

**Comment by JorritSalverda** [comment]
I've retried adding it via the UI, which gives me the following query - when viewing it with the query editor - but still has the same issue:

```sql
#standardSQL
SELECT
 $__timeGroupAlias(usage_start_time,1d),
  'Gross' AS metric,
  sum(cost) AS cost $__timeShifting(30d)
FROM `***`
WHERE
  $__timeFilter(usage_start_time)
GROUP BY 1,2
ORDER BY 1,2
```

It sends the following 2 queries to BQ:

```sql
#standardSQL
SELECT
 TIMESTAMP_SECONDS(DIV(UNIX_SECONDS(usage_start_time), 86400) * 86400),
  'Gross' AS metric,
  sum(cost) AS cost 
FROM `***`
WHERE
  usage_start_time BETWEEN TIMESTAMP_MILLIS (1557319805923) AND TIMESTAMP_MILLIS (1559911805923)
GROUP BY 1,2
ORDER BY 1,2 LIMIT 1659
```

```sql
#standardSQL
SELECT
 TIMESTAMP_SECONDS(DIV(UNIX_SECONDS(usage_start_time), 86400) * 86400),
  'Gross' AS metric,
  sum(cost) AS cost 
FROM `***`
WHERE
  usage_start_time BETWEEN TIMESTAMP_MILLIS (1554727805923) AND TIMESTAMP_MILLIS (1557319805923)
GROUP BY 1,2
ORDER BY 1,2 LIMIT 1659
```

of which the responses are rendered like

![20190607-grafana-bigquery-timeshift](https://user-images.githubusercontent.com/136472/59105307-fe0b4680-8933-11e9-82b3-bdf8d5b3f471.png)

**Comment by avivl** [comment]
This first query is between
Wednesday, May 8, 2019 12:50:05.923 PM and Friday, June 7, 2019 12:50:05.923 PM

The 2nd is between
Monday, April 8, 2019 12:50:05.923 PM and Wednesday, May 8, 2019 12:50:05.923 PM

The timeshift is 30 days.

Try to reduce the timeshift (It can not be the same of the period should be less)
