### ISSUE TITLE
Support maxDataPoints

### ISSUE THREAD

**Issue by avivl** [doitintl/bigquery-grafana#60]

**Comment by JorritSalverda** [comment]
This changes leads to a lot of 'truncated' graphs where a group by results in a lot of graphs.

![grafana-bigquery-truncated-graph](https://user-images.githubusercontent.com/136472/58257218-cbc4eb00-7d70-11e9-928f-b09bf033f991.png)

Can I disable or set the max number of data points?

**Comment by avivl** [comment]
#69

**Comment by PStump** [comment]
I have the same problem with 'truncated' graphs. Where can I set the maxDataPoints?

**Comment by avivl** [comment]
@PStump go to edit mode and you will see it on the lower left
![image](https://user-images.githubusercontent.com/3265061/61587590-8caaee80-ab95-11e9-84ac-b0042f05d397.png)
