### ISSUE TITLE
Plugin version in 0.5.0 zip is still 0.4.0

### ISSUE THREAD

**Issue by JorritSalverda** [doitintl/bigquery-grafana#63]
## Bug Report

The version number hasn't been updated in `plugin.json`, hence the Grafana ui still shows the old version.

## Expected Behavior

The Grafana `/plugins/doitintl-bigquery-datasource/` page to show version `0.5.0` when running with `GF_INSTALL_PLUGINS=
https://github.com/doitintl/bigquery-grafana/archive/0.5.0.zip;doitintl-bigquery-datasource`

## Actual Behavior

Show version `0.4.0` instead

**Comment by avivl** [comment]
#64
