### ISSUE TITLE
Feature Request: alerting queries

### ISSUE THREAD

**Issue by hoffoo** [doitintl/bigquery-grafana#67]
## Feature Request

**Is your feature request related to a problem? Please describe.**
We would like to utilize grafana alerting with this backend. Currently when trying to add an alert grafana reports that the datasource does not support it

**Describe the solution you'd like**
To be able to add an alert in grafana. One drawback might be cost but we are planning on having a long duration between runs. 

**Describe alternatives you've considered**
This is mainly for GCP billing alerts. Have had a difficult time finding alternatives that allow for more in depth analysis/alerting

**Teachability, Documentation, Adoption, Migration Strategy**
I hope this isnt too much of a niche feature! Also if you know an alternate way to trigger alerts om GCP billing id be very interested to hear :)

**Comment by spark2ignite** [comment]
@hoffoo For a data source to support alerting, it has to be implemented on Grafana backend. Grafana does not yet have support for backend plugins (although it’s on the roadmap [29](https://github.com/grafana/grafana/blob/master/ROADMAP.md)). This means for a custom data source to support alerting, it would have to be included in Grafana core.

Alerting support for custom plugins will be possible when [support for backend plugins](https://github.com/grafana/grafana/issues/6841) has been implemented.

In the meantime, we can recommend [reOptimize](www.reoptimize.io) as a tool to track your Google Cloud consumption as well as setup budgets and very flexible alerts.

**Comment by hoffoo** [comment]
Thank you!
