### ISSUE TITLE
Documentation: variables

### ISSUE THREAD

**Issue by LukeDefeo** [doitintl/bigquery-grafana#81]
## Help

I'm really interested in this project but it's quite hard to use with some sharp edges. Basically, I have a table with a bunch of error types and messages in a table broken down by topic. What I'm trying to achieve is a time series graph showing the counts of the errors over time. Id also like a variable to filter on a single topic. I managed to get this so far:

```
#standardSQL
SELECT
 $__timeGroupAlias(__Metadata.IngestedTimestamp,1d),
  Topic AS metric,
  count(*) AS count
  
  
FROM `table`
WHERE
  $__timeFilter(__Metadata.IngestedTimestamp) AND _PARTITIONTIME >= '2019-06-01 00:00:00' AND _PARTITIONTIME < '2019-06-30 23:59:59'
  
GROUP BY 1,2
ORDER BY 1,2
```
which gives me this:
![image](https://user-images.githubusercontent.com/2492575/59450548-55f8f000-8e01-11e9-968f-7cb0bd434fe0.png)

Good start. 

I managed to setup a grafana variable from doing a distinct on my metric (topic) and its populated so that is nice but I can't figure out how to use it in my query.

Ive tried lots of variations on below using ${} [] etc and no luck
```
#standardSQL
SELECT
 $__timeGroupAlias(__Metadata.IngestedTimestamp,1d),
  Topic AS metric,
  count(*) AS count
  
FROM `just-data.production_je_poisonmessages.justsaying_all_2019`
WHERE
  $__timeFilter(__Metadata.IngestedTimestamp) AND _PARTITIONTIME >= '2019-06-01 00:00:00' AND _PARTITIONTIME < '2019-06-30 23:59:59'
  and Topic like '%${topic}%'
GROUP BY 1,2,
ORDER BY 1,2
```

thanks

**Comment by avivl** [comment]
@LukeDefeo if your variable is named topic you can use it in the where clause
like this` Topic = $topic` or `Topic LIKE $topic` or `Topic IN ($topic)`

[Demo](https://youtu.be/BV41byM3Tlo)
