### ISSUE TITLE
Support multiple metric columns

### ISSUE THREAD

**Issue by LukeDefeo** [doitintl/bigquery-grafana#84]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I am trying to create a dashboard which displays error messages. The schema is roughly

```
errorType: String
topic: String
tenant: String
message: String
```
I want to create a table visualisation where the columns of the table correspond to the unique groupings of these dimension columns. The final column would be the count. The query ideally would look like this

```
#standardSQL
SELECT
 $__timeGroupAlias(__Metadata.IngestedTimestamp,1d),
 Topic,
 tenent,
errorType,
message, 
count(*) AS count,
  
FROM `just-data.production_je_poisonmessages.justsaying_all_2019`
WHERE
  $__timeFilter(__Metadata.IngestedTimestamp) AND _PARTITIONTIME >= '2019-06-01 00:00:00' AND _PARTITIONTIME < '2019-06-30 23:59:59'
GROUP BY 1,2,3.4,5
ORDER BY 1,2
```

**Describe the solution you'd like**
The ability to do a group by on any number of fields and for each field to be a column in the table view in grafana. I'm not familiar with grafana internals but I presume this is possible 

**Describe alternatives you've considered**

The closest way to get this behaviour is to stuff all these data in a column and call it metric like this:

```
#standardSQL
SELECT
 $__timeGroupAlias(__Metadata.IngestedTimestamp,1d),
  CONCAT(Topic,'    ',Tenant,'     ',ErrorMessage) AS metric,
  count(*) AS count,
  ErrorMessage as error
  
FROM `just-data.production_je_poisonmessages.justsaying_all_2019`
WHERE
  $__timeFilter(__Metadata.IngestedTimestamp) AND _PARTITIONTIME >= '2019-06-01 00:00:00' AND _PARTITIONTIME < '2019-06-30 23:59:59'
GROUP BY 1,2,4
ORDER BY 1,2
```

Here is my grafana table setup and output for reference
![image](https://user-images.githubusercontent.com/2492575/59512700-27d2e900-8eb1-11e9-9ee6-6fade6e935ef.png)

**Comment by avivl** [comment]
@LukeDefeo did you try to set the Table Transform to table?

**Comment by LukeDefeo** [comment]
I have but it immediately switches back to the previous setting. Seems similar to this behaviour

**Comment by avivl** [comment]
@LukeDefeo I'm not sure that I fully understand the issue.

Please take a look at[this video](https://youtu.be/Tj6XvrpGbSA) and LMK what am I missing.

**Comment by LukeDefeo** [comment]
I think you have the same thing I'm seeing. At 19 seconds in it switches from 'table' back to time series to rows. I would expect to see in table mode multiple columns from the query appear in the table

**Comment by avivl** [comment]
@LukeDefeo there is the visualtion table and data format table.
When you create/set a new visualization it defaults the datformat to time series. You need to change it to table.

**Comment by LukeDefeo** [comment]
@avivl i presume you mean this 
![image](https://user-images.githubusercontent.com/2492575/59690346-31be5a00-91d9-11e9-8385-2babaa1da95e.png)

when i set it to table i get the error `cannot read property search of undefined`

Also in the video you sent me you are actually using the timeseries to rows option which only allows a single metric column

**Comment by avivl** [comment]
The table issues are fixed in the latest version
`grafana-cli --pluginUrl https://github.com/doitintl/bigquery-grafana/archive/0.6.1.zip plugins install doitintl-bigquery-datasource`
