### ISSUE TITLE
Cannot read property 'v' of undefined

### ISSUE THREAD

**Issue by yabloki** [doitintl/bigquery-grafana#85]
The query seems to work

#standardSQL
SELECT
 timestamp AS time,
 price AS metric,
 exchange AS exchange
FROM `...
WHERE
  $__timeFilter(timestamp) AND
  quote = "USD"
GROUP BY timestamp, exchange,2
ORDER BY 1,2

query inspector shows data:

Array[3]
0:Object
v:"1.56083785975E9"
1:Object
v:"131.63300"
2:Object
v:"bittrex"

But can't make it show the graph.
Any advice?
Thanks

**Comment by avivl** [comment]
@yabloki Are you using a table format? If yes this is fixed in the latest version in master branch

**Comment by yabloki** [comment]
I've tried many visualisation formats and they all had this error. Thanks ill try later today. When are you planning next release?

**Comment by avivl** [comment]
Just released it
`grafana-cli --pluginUrl https://github.com/doitintl/bigquery-grafana/archive/0.6.1.zip plugins install doitintl-bigquery-datasource`
