### ISSUE TITLE
Broken link on the config page

### ISSUE THREAD

**Issue by daniellee** [doitintl/bigquery-grafana#88]
## Expected Behavior

Link on config page should go to the [plugin page on grafana.com](https://grafana.com/plugins/doitintl-bigquery-datasource) or the readme in the GitHub repo. 

## Actual Behavior

The link in the text `Detailed instructions on how to create a Service Account can be found in the documentation.` points to a non-existent docs page on the Grafana docs site: http://docs.grafana.org/datasources/BigQuery/

## Specifications

  - Version: 0.6.1
  - Platform: Ubuntu 16.04
  - Grafana Version: latest master

**Comment by avivl** [comment]
@daniellee   I'll stop maintaining this data source in a couple of weeks.
@Tamirklein and his team will take over.
I would also like to thank you for your involvement and contribution to this project
