### ISSUE TITLE
Nested fields aren't working properly

### ISSUE THREAD

**Issue by DaveTaboola** [doitintl/bigquery-grafana#9]
## Expected Behavior
Returning data for nested fields 

## Actual Behavior 
Returning non defined objects -  [object Object]

## Steps to Reproduce the Problem

  1. Create bigquery data source
  2. Create new table visualisation
  3.  Create a query of SELECT * FROM <table which consist with nested fields> (no time series) 

## Specifications

  - Version: 1.0 
  - Platform: container over k8s
  - Grafana Version: 5.4.2

**Comment by avivl** [comment]
same as #3
